// Human-reviewed English translations for accounts, profiles and messaging.
export const EN_ACCOUNTS: Record<string, string> = {
  "Las contraseñas no coinciden": "Passwords do not match",
  "La contraseña debe tener al menos 6 caracteres": "Your password must contain at least 6 characters",
  "Error al actualizar la contraseña": "Unable to update your password",
  "Nueva Contraseña": "New password",
  "Ingresa tu nueva contraseña": "Enter your new password",
  "Mínimo 6 caracteres": "At least 6 characters",
  "Confirmar Contraseña": "Confirm password",
  "Repite tu contraseña": "Enter your password again",
  "Actualizar Contraseña": "Update password",
  "¡Contraseña actualizada!": "Password updated!",
  "Tu contraseña ha sido actualizada exitosamente. Serás redirigido al inicio de sesión...": "Your password has been updated successfully. You will be redirected to the sign-in page...",
  "Error de Autenticación": "Authentication error",
  "Ha ocurrido un error al procesar tu solicitud": "An error occurred while processing your request",
  "Por favor intenta nuevamente o contacta al soporte si el problema persiste.": "Please try again or contact support if the problem persists.",
  "Registro": "Sign up",
  "Iniciar Sesión": "Sign in",
  "El email es requerido": "Email is required",
  "Email inválido": "Invalid email address",
  "La contraseña es requerida": "Password is required",
  "Error al iniciar sesión": "Unable to sign in",
  "Bienvenido": "Welcome",
  "Inicia sesión para acceder a tu cuenta": "Sign in to access your account",
  "Email": "Email",
  "tu@email.com": "you@email.com",
  "Contraseña": "Password",
  "¿Olvidaste tu contraseña?": "Forgot your password?",
  "Iniciando sesión...": "Signing in...",
  "O continúa con": "Or continue with",
  "¿No tienes cuenta?": "Do not have an account?",
  "Regístrate gratis": "Sign up for free",
  "Error al enviar el email": "Unable to send the email",
  "Recuperar Contraseña": "Reset password",
  "Ingresa tu email y te enviaremos un enlace para restablecer tu contraseña": "Enter your email and we will send you a link to reset your password",
  "Enviar enlace de recuperación": "Send password reset link",
  "Volver al inicio de sesión": "Back to sign in",
  "¡Email enviado!": "Email sent!",
  "Hemos enviado un enlace de recuperación a": "We have sent a password reset link to",
  ". Por favor revisa tu bandeja de entrada y sigue las instrucciones.": ". Please check your inbox and follow the instructions.",
  "¡Cuenta creada!": "Account created!",
  "Ya formas parte de Diime": "You are now part of Diime",
  "Ya solo te falta tu perfil profesional": "All you need now is your professional profile",
  "¿Vas a ofrecer servicios?": "Will you be offering services?",
  "Completa tu perfil profesional y elige los servicios y las provincias que cubres. Es lo que decide de qué demandas te avisamos, así que sin ello no recibirás ninguna.": "Complete your professional profile and choose the services and provinces you cover. These choices determine which requests we notify you about, so you will not receive any request alerts until you do.",
  "Crear mi perfil profesional": "Create my professional profile",
  "Si solo quieres contratar servicios, ya puedes:": "If you only want to hire professionals, you can already:",
  "Publicar una demanda y recibir ofertas": "Post a request and receive offers",
  "Hablar por el chat con los profesionales": "Chat with professionals",
  "Pagar de forma protegida, con el dinero en custodia": "Pay securely, with your payment held until release",
  "Publicar una demanda": "Post a request",
  "Si te pedimos verificar tu correo, revisa tu bandeja de entrada.": "If we ask you to verify your email, check your inbox.",
  "Debes aceptar los Términos y las Normas de la comunidad.": "You must accept the Terms and Community Guidelines.",
  "Para crear una cuenta debes confirmar que tienes 18 años o más.": "To create an account, you must confirm that you are at least 18 years old.",
  "Por favor ingresa el nombre de tu empresa": "Please enter your company name",
  "Indica tu DNI/NIE como persona que actúa en nombre de la empresa": "Enter your DNI/NIE as the person acting on behalf of the company",
  "Error al crear la cuenta": "Unable to create your account",
  "Crear Cuenta": "Create account",
  "Regístrate para contratar u ofrecer servicios profesionales": "Sign up to hire professionals or offer professional services",
  "Confirmo que tengo": "I confirm that I am",
  "18 años o más": "at least 18 years old",
  "y capacidad legal para contratar servicios.": "and have the legal capacity to enter into service contracts.",
  "Acepto los": "I accept the",
  "Términos": "Terms",
  ", la": ", the",
  "Política de privacidad": "Privacy Policy",
  "y las": "and the",
  "Normas de la comunidad": "Community Guidelines",
  "O regístrate con email": "Or sign up with email",
  "Nombre": "First name",
  "Juan": "John",
  "Apellidos": "Last name",
  "Pérez García": "Smith",
  "Tipo de Registro": "Account type",
  "Particular": "Individual",
  "Empresa": "Company",
  "Nombre de la Empresa": "Company name",
  "Mi Empresa S.L.": "My Company S.L.",
  "Código de Identificación Fiscal de tu empresa": "Your company's Spanish tax identification number",
  "Documento Nacional de Identidad o NIE": "Spanish national ID (DNI) or foreigner ID (NIE)",
  "Tu DNI/NIE (persona que actúa por la empresa)": "Your DNI/NIE (person acting on behalf of the company)",
  "Tu cargo (opcional)": "Your position (optional)",
  "Administrador, Gerente...": "Director, Manager...",
  "La empresa factura y contrata, pero necesitamos saber quién actúa en su nombre.": "The company issues invoices and enters into contracts, but we need to know who acts on its behalf.",
  "Token de Invitación (opcional)": "Invitation token (optional)",
  "Si te invitaron a una empresa...": "If you were invited to join a company...",
  "El vínculo se completa desde Mi Empresa, después de confirmar tu correo.": "Complete the link to your company in My Company after confirming your email.",
  "Teléfono (opcional)": "Phone number (optional)",
  "Provincia": "Province",
  "Selecciona tu provincia": "Select your province",
  "Repetir Contraseña": "Repeat password",
  "Creando cuenta...": "Creating account...",
  "¿Ya tienes cuenta?": "Already have an account?",
  "Inicia sesión": "Sign in",
  "Al registrarte, podrás contratar servicios y más adelante crear tu perfil profesional para ofrecer servicios.": "Once registered, you can hire professionals and later create your professional profile to offer services.",
  "Configuración - Diime": "Settings - Diime",
  "Gestiona tu cuenta y preferencias": "Manage your account and preferences",
  "Configuración": "Settings",
  "Cuenta": "Account",
  "Datos de acceso y tipo de cuenta": "Sign-in details and account type",
  "Correo electrónico": "Email address",
  "Sesión iniciada como": "Signed in as",
  "Verificado": "Verified",
  "Miembro desde": "Member since",
  "Convertirme en profesional": "Become a professional",
  "Avisos": "Alerts",
  "Cómo te avisamos de lo que pasa en tus proyectos": "How we keep you informed about your projects",
  "Mi actividad": "My activity",
  "Accede a tu perfil y tus solicitudes": "Access your profile and requests",
  "Mi Perfil": "My profile",
  "Mis Solicitudes": "My requests",
  "Seguridad": "Security",
  "Cambia la contraseña de tu cuenta": "Change your account password",
  "Notificaciones": "Notifications",
  "Cómo te avisamos de la actividad en tu cuenta": "How we notify you about your account activity",
  "Verás un contador en el menú y una vista previa cuando recibas un mensaje, una oferta o una novedad de tus proyectos.": "You will see a counter in the menu and a preview when you receive a message, an offer or a project update.",
  "Soporte": "Support",
  "¿Algo no funciona como esperabas?": "Is something not working as expected?",
  "Zona de peligro": "Danger zone",
  "Cerrar sesión o darte de baja": "Sign out or delete your account",
  "Cerrar sesión": "Sign out",
  "Cierra tu sesión para entrar con otra cuenta o registrar una nueva.": "Sign out to use another account or register a new one.",
  "Eliminar mi cuenta": "Delete my account",
  "Cierra tu cuenta al instante, sin pedírselo a soporte. Antes de confirmar te diremos exactamente qué pasa con tus demandas, tus trabajos en marcha y el dinero que haya de por medio.": "Close your account immediately without contacting support. Before you confirm, we will explain exactly what happens to your requests, ongoing work and any money involved.",
  "No se pudieron cargar los datos de tu empresa. Actualiza la página para volver a intentarlo.": "Unable to load your company details. Refresh the page to try again.",
  "Link copiado": "Link copied",
  "El link de invitación se ha copiado al portapapeles": "The invitation link has been copied to the clipboard",
  "Cargando...": "Loading...",
  "No se pudo guardar la empresa. Puedes volver a intentarlo.": "Unable to save the company. Please try again.",
  "Completar Mi Empresa": "Complete My Company",
  "Tu cuenta personal y tu empresa se completan en dos pasos. Confirma tu correo e inicia sesión para continuar.": "Your personal account and company are set up in two steps. Confirm your email and sign in to continue.",
  "Crea tu empresa o utiliza una invitación. Tu cuenta podrá contratar y ofrecer servicios en su nombre.": "Create your company or use an invitation. Your account will be able to hire professionals and offer services on its behalf.",
  "Iniciar sesión para continuar": "Sign in to continue",
  "Token de invitación (si te invitaron)": "Invitation token (if you were invited)",
  "Nombre de la empresa": "Company name",
  "CIF": "CIF (Spanish company tax ID)",
  "Tu DNI/NIE como representante": "Your DNI/NIE as the company representative",
  "Vincular mi empresa": "Link my company",
  "CIF:": "CIF:",
  "Tu cuenta ya representa a esta empresa": "Your account now represents this company",
  "Puedes contratar servicios y completar tu perfil profesional para ofrecerlos en su nombre.": "You can hire professionals and complete your professional profile to offer services on the company's behalf.",
  "Completar perfil profesional": "Complete professional profile",
  "Invitar Empleados": "Invite employees",
  "Comparte este link con tus empleados para que se unan a la empresa": "Share this link with your employees so they can join the company",
  "Link de Invitación": "Invitation link",
  "Los empleados completarán la invitación desde Mi Empresa después de confirmar su correo.": "Employees will complete the invitation in My Company after confirming their email.",
  "Miembros de la Empresa (": "Company members (",
  "Solicita y completa la eliminación de tu cuenta de Diime y de los datos asociados.": "Request and complete the deletion of your Diime account and associated data.",
  "Eliminar una cuenta de Diime": "Delete a Diime account",
  "Esta página permite solicitar y completar el borrado de la cuenta y de los datos que no debamos conservar por obligaciones legales, contables o por reclamaciones abiertas.": "Use this page to request and complete the deletion of your account and any data we are not required to retain for legal or accounting obligations or unresolved claims.",
  "El perfil público, las publicaciones abiertas, el portfolio y el acceso a la cuenta se eliminan. Antes de confirmar verás qué ocurre con trabajos, pagos o disputas pendientes.": "Your public profile, open listings, portfolio and account access will be removed. Before you confirm, you will see what happens to pending work, payments or disputes.",
  "El proceso requiere iniciar sesión para comprobar que la solicitud pertenece realmente al titular.": "You must sign in so we can verify that the request comes from the account holder.",
  "Has iniciado sesión como": "You are signed in as",
  "Iniciar sesión y eliminar mi cuenta": "Sign in and delete my account",
  "Pedir ayuda a soporte": "Ask support for help",
  "Consulta los detalles sobre conservación y tus derechos en la": "Read about data retention and your rights in the",
  "política de privacidad": "privacy policy",
  "Cualquier presupuesto": "Any budget",
  "24 horas": "24 hours",
  "Profesional Verificado": "Verified professional",
  "No disponible": "Unavailable",
  "No autenticado": "Not signed in",
  "No se pudo subir la imagen.": "Unable to upload the image.",
  "Campos requeridos": "Required fields",
  "Completa título y descripción.": "Enter a title and description.",
  "Proyecto actualizado": "Project updated",
  "Proyecto añadido": "Project added",
  "Ya aparece en tu portfolio.": "It now appears in your portfolio.",
  "No se pudieron cargar tus trabajos": "Unable to load your jobs",
  "Proyecto eliminado": "Project deleted",
  "Se ha quitado de tu portfolio.": "It has been removed from your portfolio.",
  "Elige tus servicios": "Choose your services",
  "Marca al menos una categoría para que te lleguen las demandas que te interesan.": "Select at least one category to receive the requests you are interested in.",
  "Elige tu zona": "Choose your area",
  "Marca al menos una provincia en la que quieras cubrir demandas.": "Select at least one province where you want to offer your services.",
  "Perfil actualizado": "Profile updated",
  "Tu información ha sido guardada correctamente.": "Your information has been saved successfully.",
  "Foto actualizada": "Photo updated",
  "Tu foto de perfil se ha subido correctamente.": "Your profile photo has been uploaded successfully.",
  "No se pudo subir la imagen. Inténtalo de nuevo.": "Unable to upload the image. Please try again.",
  "Portada actualizada": "Cover photo updated",
  "Tu imagen de portada se ha subido correctamente.": "Your cover photo has been uploaded successfully.",
  "Tu foto de perfil": "Your profile photo",
  "Cliente": "Client",
  "Guardar cambios": "Save changes",
  "Cancelar": "Cancel",
  "Editar perfil": "Edit profile",
  "Foto de perfil": "Profile photo",
  "Subiendo foto...": "Uploading photo...",
  "Teléfono": "Phone number",
  "No especificado": "Not specified",
  "Elige tu provincia": "Choose your province",
  "No especificada": "Not specified",
  "Sobre mí": "About me",
  "Cuéntanos algo sobre ti.": "Tell us about yourself.",
  "No has añadido una descripción todavía.": "You have not added a description yet.",
  "También puedes ofrecer servicios": "You can also offer services",
  "Completa tu perfil de proveedor para enviar ofertas. Podrás seguir contratando servicios con esta misma cuenta.": "Complete your provider profile to send offers. You can continue hiring professionals with this same account.",
  "Crear perfil de proveedor": "Create provider profile",
  "Cover": "Cover photo",
  "Cambiar portada": "Change cover photo",
  "Título profesional (ej: Maestro Albañil)": "Professional title (e.g. Master bricklayer)",
  "Sin título profesional": "No professional title",
  "Sin ubicación": "No location",
  "proyectos": "projects",
  "Responde en": "Responds within",
  "valoraciones)": "reviews)",
  "Cerrar sesion": "Sign out",
  "Enviar mensaje": "Send message",
  "Contactar": "Contact",
  "Portfolio": "Portfolio",
  "Valoraciones": "Reviews",
  "Descripción": "Description",
  "Describe tu experiencia, especialización y qué te hace único...": "Describe your experience, specialism and what makes you unique...",
  "Información Profesional": "Professional information",
  "Tarifa por hora (€)": "Hourly rate (€)",
  "Años de experiencia": "Years of experience",
  "Contacto": "Contact",
  "Avisos de nuevas demandas": "New request alerts",
  "Elige qué servicios, provincias y presupuestos te interesan. Solo te avisaremos de las demandas que encajen con estos filtros.": "Choose the services, provinces and budgets you are interested in. We will only notify you about requests that match these filters.",
  "No estás recibiendo avisos de demandas": "You are not receiving request alerts",
  "Elige tus servicios y tus provincias": "Choose your services and provinces",
  "(pulsa «Editar perfil»)": "(select “Edit profile”)",
  "para empezar a recibirlas.": "to start receiving them.",
  "Servicios que ofreces": "Services you offer",
  "Todavía no has elegido servicios.": "You have not chosen any services yet.",
  "Provincias que cubres": "Provinces you cover",
  "Todavía no has elegido provincias.": "You have not chosen any provinces yet.",
  "Presupuesto total del proyecto": "Total project budget",
  "Las demandas con presupuesto «A convenir» también se incluyen.": "Requests with a “To be agreed” budget are also included.",
  "Habilidades": "Skills",
  "No has añadido habilidades todavía.": "You have not added any skills yet.",
  "Nueva habilidad...": "New skill...",
  "Certificaciones": "Certifications",
  "Declaradas por el proveedor": "Declared by the provider",
  "No has añadido certificaciones todavía.": "You have not added any certifications yet.",
  "Nueva certificación...": "New certification...",
  "Idiomas": "Languages",
  "No has añadido idiomas todavía.": "You have not added any languages yet.",
  "Nuevo idioma (ej: Español - Nativo)...": "New language (e.g. English - Native)...",
  "Añadir proyecto": "Add project",
  "No tienes proyectos en tu portfolio todavía.": "You do not have any projects in your portfolio yet.",
  "Verificado por Diime": "Verified by Diime",
  "Aporte del profesional": "Professional's contribution",
  "Coste publicado aproximado:": "Approximate published cost:",
  "valoraciones": "reviews",
  "Aún no tienes valoraciones.": "You do not have any reviews yet.",
  "Las valoraciones aparecerán aquí cuando completes proyectos.": "Reviews will appear here when you complete projects.",
  "Estadísticas": "Statistics",
  "Proyectos completados": "Completed projects",
  "Tarifa por hora": "Hourly rate",
  "Tiempo de respuesta": "Response time",
  "Editar proyecto del portfolio": "Edit portfolio project",
  "Añadir proyecto al portfolio": "Add project to portfolio",
  "Muestra un trabajo que ya hayas realizado. Aparecerá en tu perfil público.": "Showcase work you have completed. It will appear on your public profile.",
  "¿Ya hiciste este trabajo en Diime?": "Did you complete this job through Diime?",
  "Importa sus datos y añádelo como trabajo verificado.": "Import its details and add it as verified work.",
  "Seleccionar trabajo": "Select job",
  "Cargando trabajos…": "Loading jobs…",
  "Aún no tienes trabajos finalizados en Diime.": "You do not have any completed jobs on Diime yet.",
  "Trabajo verificado por Diime": "Work verified by Diime",
  "Título de la demanda": "Request title",
  "Título del proyecto *": "Project title *",
  "Ej: Reforma integral de cocina": "E.g. Complete kitchen renovation",
  "Descripción de la demanda": "Request description",
  "Descripción *": "Description *",
  "Describe el proyecto, los retos y el resultado...": "Describe the project, challenges and result...",
  "Este texto lo publicó el cliente y se muestra tal cual en el portfolio.": "This text was published by the client and is displayed unchanged in the portfolio.",
  "Tu aporte al trabajo": "Your contribution to the work",
  "Explica cómo lo realizaste, materiales empleados, retos resueltos o el resultado conseguido...": "Explain how you carried out the work, the materials used, challenges you overcame or the result achieved...",
  "Se mostrará separado de la descripción original de la demanda.": "This will be shown separately from the original request description.",
  "Adjuntar archivos": "Attach files",
  "Vista previa del proyecto": "Project preview",
  "Quitar archivo": "Remove file",
  "Subiendo archivo…": "Uploading file…",
  "Añade una imagen para enseñar el resultado (opcional).": "Add an image to show the result (optional).",
  "Servicio": "Service",
  "Selecciona un servicio": "Select a service",
  "Fecha de finalización": "Completion date",
  "Ubicación": "Location",
  "Selecciona una provincia": "Select a province",
  "Duración": "Duration",
  "2 semanas": "2 weeks",
  "Presupuesto (€)": "Budget (€)",
  "Guardando...": "Saving...",
  "Guardar proyecto": "Save project",
  "Es tu propio perfil": "This is your own profile",
  "No puedes enviarte un mensaje a ti mismo.": "You cannot send yourself a message.",
  "No se pudo abrir el chat.": "Unable to open the chat.",
  "Sin teléfono": "No phone number",
  "Este profesional no ha publicado un teléfono de contacto.": "This professional has not published a contact phone number.",
  "Cuenta eliminada": "Account deleted",
  "Esta persona ha cerrado su cuenta en Diime. No se la puede contactar ni contratar. Su perfil se mantiene visible sin datos de contacto para quienes trabajaron con ella.": "This person has closed their Diime account. They can no longer be contacted or hired. Their profile remains visible without contact details to people who worked with them.",
  "La interacción con este usuario está bloqueada. No podéis iniciar ni continuar conversaciones.": "Interaction with this user is blocked. You cannot start or continue conversations with each other.",
  "Reportar": "Report",
  "Tarifa": "Rate",
  "Años exp.": "Years' exp.",
  "Valoración": "Rating",
  "Portfolio (": "Portfolio (",
  "Valoraciones (": "Reviews (",
  "Certificaciones declaradas": "Declared certifications",
  "Información aportada por el proveedor. La insignia del perfil no acredita cada titulación.": "Information provided by the provider. The profile badge does not verify each qualification.",
  "Este profesional aún no ha añadido trabajos a su portfolio.": "This professional has not added any work to their portfolio yet.",
  "Tiempo:": "Time:",
  "Coste aprox.:": "Approx. cost:",
  "Ver detalles": "View details",
  "Todavía no hay valoraciones.": "There are no reviews yet.",
  "Detalles de un trabajo completado por": "Details of work completed by",
  "Completado": "Completed",
  "Coste orientativo": "Indicative cost",
  "El precio exacto del encargo es privado.": "The exact price of the job is private.",
  "Descripción del trabajo": "Job description",
  "Contrata a": "Hire",
  "de forma segura con pagos protegidos por Diime.": "securely with payments protected by Diime.",
  "No se pudo enviar el mensaje. Inténtalo de nuevo.": "Unable to send the message. Please try again.",
  "No se puede valorar todavía": "You cannot leave a review yet",
  "Valoración enviada": "Review submitted",
  "Gracias por valorar a este profesional.": "Thank you for reviewing this professional.",
  "No se pudo enviar": "Unable to send",
  "No se pudo subir el archivo": "Unable to upload the file",
  "Inténtalo de nuevo en unos segundos.": "Try again in a few seconds.",
  "Mié": "Wed",
  "Sáb": "Sat",
  "En progreso": "In progress",
  "Pago pendiente": "Payment pending",
  "Por confirmar": "Awaiting confirmation",
  "En disputa": "In dispute",
  "Cargando conversaciones...": "Loading conversations...",
  "Buscar conversaciones...": "Search conversations...",
  "Todos": "All",
  "No leídos": "Unread",
  "Archivados": "Archived",
  "No hay mensajes sin leer": "No unread messages",
  "No hay chats archivados": "No archived chats",
  "No tienes conversaciones": "You do not have any conversations",
  "Ver ficha administrativa del usuario": "View the user's administrative record",
  "Ver perfil y proyectos con este usuario": "View profile and projects with this user",
  "· Tú:": "· You:",
  "Fijar conversación": "Pin conversation",
  "Archivar": "Archive",
  "Eliminar chat": "Delete chat",
  "No hay mensajes aún": "No messages yet",
  "Envía el primer mensaje": "Send the first message",
  "• Haz clic para abrir": "• Click to open",
  "Adjuntar archivo": "Attach file",
  "Escribe un mensaje": "Write a message",
  "Escribe un mensaje...": "Write a message...",
  "Tus mensajes": "Your messages",
  "Selecciona una conversación de la lista para ver los mensajes": "Select a conversation from the list to view messages",
  "Perfil": "Profile",
  "Cerrar": "Close",
  "reseñas)": "reviews)",
  "Ver ficha del usuario": "View user record",
  "Ver perfil": "View profile",
  "Valorar": "Leave a review",
  "Acerca de": "About",
  "Proyecto activo": "Active project",
  "Progreso": "Progress",
  "Ver detalles del proyecto": "View project details",
  "Proyectos con este usuario (": "Projects with this user (",
  "Esperando pago": "Awaiting payment",
  "Ver justificante y términos": "View payment receipt and terms",
  "Archivos compartidos": "Shared files",
  "Aún no hay archivos compartidos": "No shared files yet",
  "Valorar al profesional": "Review the professional",
  "Valora el trabajo \"": "Review the job “",
  "\". Tu opinión ayuda a otros clientes.": "”. Your review helps other clients.",
  "Puntuación": "Rating",
  "Comentario": "Comment",
  "Describe tu experiencia con este profesional...": "Describe your experience with this professional...",
  "Enviar valoración": "Submit review",
  "Abrir mensajes": "Open messages",
  "Contraseña demasiado corta": "Password too short",
  "Usa al menos 6 caracteres.": "Use at least 6 characters.",
  "No se pudo cambiar la contraseña": "Unable to change your password",
  "Contraseña actualizada": "Password updated",
  "Ya puedes usarla en tu próximo inicio de sesión.": "You can use it the next time you sign in.",
  "Nueva contraseña": "New password",
  "Confirmar contraseña": "Confirm password",
  "Repite la contraseña": "Repeat password",
  "Actualizar contraseña": "Update password",
  "Se borrará tu demanda publicada, junto con las ofertas que hayas recibido en ella.": "Your published request will be deleted, along with any offers you received for it.",
  "Se retirará tu puja pendiente: nadie podrá aceptártela.": "Your pending bid will be withdrawn: nobody will be able to accept it.",
  "Desaparecerás de la sección de Profesionales y dejarás de recibir avisos de demandas.": "You will be removed from the Professionals section and will no longer receive request alerts.",
  "Perderás el acceso: no podrás volver a entrar con esta cuenta ni recuperarla.": "You will lose access: you will not be able to sign in with this account again or recover it.",
  "No se pudo comprobar tu cuenta. Cierra esta ventana y vuelve a intentarlo.": "Unable to check your account. Close this window and try again.",
  "Hemos cerrado tu cuenta y tu sesión.": "We have closed your account and signed you out.",
  "Vas a eliminar tu cuenta": "You are about to delete your account",
  "Léelo entero antes de confirmar. Esto no se puede deshacer y afecta a otras personas.": "Read everything before confirming. This cannot be undone and affects other people.",
  "Comprobando qué tienes pendiente...": "Checking your pending activity...",
  "Ahora mismo no puedes darte de baja": "You cannot delete your account right now",
  "Primero finaliza o cancela de mutuo acuerdo tus contratos, resuelve las disputas y completa los cobros o reembolsos pendientes. Conservas el acceso para hacerlo desde": "First, complete your contracts or cancel them by mutual agreement, resolve disputes and complete outstanding payments or refunds. You retain access to do this from",
  "Mis trabajos": "My jobs",
  "Mis solicitudes": "My requests",
  "y": "and",
  "Cobros": "Payouts",
  ". Si un pago está bloqueado, contacta con soporte.": ". If a payment is blocked, contact support.",
  "Qué va a pasar": "What will happen",
  "Qué se conserva, y por qué": "What is retained, and why",
  "Tu nombre y tus datos de facturación seguirán apareciendo en los trabajos y facturas ya cerrados, y las personas con las que trabajaste podrán seguir viéndolos. Es obligatorio conservar los registros contables, y es lo que permite reclamar a cualquiera de las dos partes si algo acaba en los tribunales. Lo que desaparece de la web es tu perfil: foto, descripción, ficha profesional y publicaciones.": "Your name and billing details will remain on completed jobs and invoices, and the people you worked with will still be able to see them. Accounting records must be retained, and they allow either party to bring a claim if a matter goes to court. Your profile is removed from the website: photo, description, professional details and listings.",
  "He leído lo de arriba, entiendo que no tiene vuelta atrás y que no podré recuperar la cuenta.": "I have read the information above and understand that this is irreversible and I will not be able to recover my account.",
  "Escribe": "Type",
  "para confirmar": "to confirm",
  "Eliminando...": "Deleting...",
  "Acepta los Términos y las Normas de la comunidad para crear una cuenta.": "Accept the Terms and Community Guidelines to create an account.",
  "Confirma que tienes 18 años o más para crear una cuenta.": "Confirm that you are at least 18 years old to create an account.",
  "Continuar con Google": "Continue with Google",
  "Continuar con Apple": "Continue with Apple",
  "Confirma que eres mayor de edad": "Confirm that you are an adult",
  "Diime permite contratar, cobrar y asumir obligaciones económicas. Por eso la cuenta solo puede utilizarla una persona de 18 años o más con capacidad legal para contratar.": "Diime allows users to enter into contracts, receive payments and take on financial obligations. Therefore, the account may only be used by a person aged 18 or over with legal capacity to enter into contracts.",
  "Confirmo que tengo 18 años o más y acepto esta condición de los": "I confirm that I am at least 18 years old and accept this requirement in the",
  "Términos de Diime": "Diime Terms",
  "Guardamos la fecha de esta confirmación, no tu fecha de nacimiento. Consulta la": "We store the date of this confirmation, not your date of birth. Read the",
  "Confirmar y continuar": "Confirm and continue",
  "No se pudo guardar": "Unable to save",
  "Comprueba tu conexión y vuelve a intentarlo.": "Check your connection and try again.",
  "Avisos por correo activados": "Email alerts enabled",
  "Avisos por correo desactivados": "Email alerts disabled",
  "Recibirás las categorías que tienes seleccionadas.": "You will receive alerts for your selected categories.",
  "Seguirás viendo todos los avisos dentro de Diime.": "You will still see all alerts within Diime.",
  "Categoría activada": "Category enabled",
  "Categoría desactivada": "Category disabled",
  "Avisos por correo": "Email alerts",
  "Elige qué novedades quieres recibir también en tu correo.": "Choose which updates you also want to receive by email.",
  "No recibes correos. Todos los avisos siguen apareciendo dentro de Diime.": "You are not receiving emails. All alerts still appear within Diime.",
  "Desactivar todo": "Disable all",
  "Activar": "Enable",
  "Los mensajes de chat no generan un correo por cada mensaje; siguen llegando dentro de Diime y mediante las notificaciones del dispositivo.": "Chat messages do not generate an email for every message; you still receive them within Diime and through device notifications.",
  "El iPhone no devolvió el token de notificaciones": "The iPhone did not return a notification token",
  "Notificaciones activadas": "Notifications enabled",
  "Este dispositivo ya puede recibir avisos de Diime.": "This device can now receive Diime alerts.",
  "No se pudieron activar": "Unable to enable notifications",
  "Vuelve a intentarlo.": "Please try again.",
  "No se pudo enviar la prueba": "Unable to send the test",
  "Prueba enviada": "Test sent",
  "Deberías recibir el aviso en unos segundos.": "You should receive the alert within a few seconds.",
  "Las notificaciones push se configuran desde la app de iPhone o Android.": "Push notifications are configured in the iPhone or Android app.",
  "Notificaciones bloqueadas en el sistema": "Notifications blocked in system settings",
  "No se pudo registrar este dispositivo": "Unable to register this device",
  "Avisos en este dispositivo": "Alerts on this device",
  "Abre Ajustes → Diime → Notificaciones y activa Permitir notificaciones, Previsualizaciones y Sonidos.": "Open Settings → Diime → Notifications and enable Allow Notifications, Show Previews and Sounds.",
  "Los mensajes muestran el remitente y parte del texto, también con la app cerrada.": "Messages show the sender and part of the text, even when the app is closed.",
  "Enviar prueba": "Send test",
  "Hemos recibido tu solicitud. Diime se pondrá en contacto contigo para revisarla.": "We have received your request. Diime will contact you to review it.",
  "Diime está revisando tu perfil. Consulta tus mensajes para responder si necesitamos más información.": "Diime is reviewing your profile. Check your messages and reply if we need more information.",
  "Diime ha verificado tu perfil profesional. La insignia se muestra en tu perfil.": "Diime has verified your professional profile. The badge is displayed on your profile.",
  "Revisa el comentario de Diime y envía una nueva solicitud cuando hayas realizado los cambios necesarios.": "Read Diime's comment and submit a new request once you have made the necessary changes.",
  "La verificación de tu perfil se ha retirado. Revisa el comentario de Diime antes de volver a solicitarla.": "Your profile verification has been withdrawn. Read Diime's comment before applying again.",
  "No se pudo cargar el estado de tu verificación.": "Unable to load your verification status.",
  "No se pudo cargar el estado de tu verificación. Inténtalo de nuevo.": "Unable to load your verification status. Please try again.",
  "No se pudo enviar la solicitud. Inténtalo de nuevo.": "Unable to submit your request. Please try again.",
  "Solicitud enviada. Diime se pondrá en contacto contigo para revisar tu perfil.": "Request submitted. Diime will contact you to review your profile.",
  "No se pudo confirmar el envío. Actualiza el estado antes de volver a intentarlo.": "Unable to confirm submission. Refresh the status before trying again.",
  "Verificación por Diime": "Verification by Diime",
  "Solicita la revisión de tu perfil profesional. Diime te contactará por chat, correo electrónico o teléfono.": "Request a review of your professional profile. Diime will contact you by chat, email or phone.",
  "Cargando verificación…": "Loading verification…",
  "Perfil vinculado a": "Profile linked to",
  "Comentario de Diime": "Comment from Diime",
  "Mensaje para Diime (opcional)": "Message for Diime (optional)",
  "Cuéntanos qué servicios ofreces o añade información útil para revisar tu perfil.": "Tell us which services you offer or add useful information for reviewing your profile.",
  "caracteres": "characters",
  "Volver a solicitar verificación": "Request verification again",
  "Solicitar verificación": "Request verification",
  "Ver mensajes": "View messages",
  "Actualizar estado": "Refresh status",
  "No se pudo desbloquear": "Unable to unblock",
  "Usuario desbloqueado": "User unblocked",
  "No se pudo bloquear": "Unable to block",
  "Usuario bloqueado": "User blocked",
  "Ya no podréis iniciar ni continuar conversaciones.": "You can no longer start or continue conversations with each other.",
  "Desbloquear": "Unblock",
  "Bloquear": "Block",
  "¿Bloquear a este usuario?": "Block this user?",
  "No podréis iniciar ni continuar conversaciones. Puedes desbloquearlo más adelante desde su perfil. Si ha infringido las normas, repórtalo también para que el equipo de Diime pueda revisarlo.": "You will not be able to start or continue conversations with each other. You can unblock them later from their profile. If they have broken the rules, also report them so the Diime team can review it.",
  "Bloquear usuario": "Block user",
  "No se pudo abrir el chat": "Unable to open the chat",
  "Ha ocurrido un error inesperado. Inténtalo de nuevo.": "An unexpected error occurred. Please try again.",
  "Chatear con el usuario": "Chat with the user",
  "Chatear con usuario": "Chat with user",
  "Perfil profesional en Diime": "Professional profile on Diime",
  "Consulta este perfil profesional en Diime": "View this professional profile on Diime",
  "Compartir perfil": "Share profile",
  "Información Rápida": "Quick information",
  "Portfolio de Trabajos Completados": "Portfolio of completed work",
  "Completado:": "Completed:",
  "Duración:": "Duration:",
  "Presupuesto:": "Budget:",
  "Por favor completa todos los campos": "Please complete all fields",
  "Reseña enviada": "Review submitted",
  "Tu valoración ha sido publicada": "Your review has been published",
  "Valoraciones y Opiniones de Clientes": "Client ratings and reviews",
  "reseñas": "reviews",
  "Dejar Reseña": "Leave a review",
  "Dejar una Valoración": "Leave a review",
  "Comparte tu experiencia con este profesional": "Share your experience with this professional",
  "Tipo de Proyecto": "Project type",
  "Ej: Instalación Eléctrica": "E.g. Electrical installation",
  "Comparte los detalles de tu experiencia...": "Share details of your experience...",
  "Publicar Reseña": "Publish review",
  "Valoración Media": "Average rating",
  "Basado en": "Based on",
  "opiniones verificadas": "verified reviews",
  "Distribución de Valoraciones": "Rating distribution",
  "Valoraciones por Tipo de Proyecto": "Ratings by project type",
  "Opiniones de Clientes (": "Client reviews (",
  "Marcado como útil": "Marked as helpful",
  "Útil": "Helpful",
  "Proyectos Completados": "Completed projects",
  "Opiniones de Clientes": "Client reviews",
  "reseñas verificadas": "verified reviews",
  "Años de Experiencia": "Years of experience",
  "años en el sector": "years in the industry",
  "Tiempo de Respuesta": "Response time",
  "Nivel Profesional": "Professional level",
  "Valoración media": "Average rating",
  "Abriendo soporte…": "Opening support…",
  "Abrir chat de soporte": "Open support chat",
  "Actualizando...": "Updating...",
  "Enviando...": "Sending...",
  "Profesional": "Professional",
  "Reportar un problema": "Report a problem",
  "Disponible": "Available",
  "Error": "Error",
  "Subiendo...": "Uploading...",
  "Presupuesto de la demanda": "Request budget",
  "Ahora": "Now",
  "Dom": "Sun",
  "Lun": "Mon",
  "Mar": "Tue",
  "Jue": "Thu",
  "Vie": "Fri",
  "Hoy": "Today",
  "Ayer": "Yesterday",
  "Pendiente": "Pending",
  "Cancelado": "Cancelled",
  "Abierta": "Open",
  "Adjudicada": "Awarded",
  "Completada": "Completed",
  "Cerrada": "Closed",
  "Cancelada": "Cancelled",
  "Mensajes": "Messages",
  "Proveedor": "Provider",
  "un usuario": "a user",
  "Entregado": "Delivered",
  "Rechazado": "Rejected",
  "Archivo": "File",
  "Entendido": "Understood",
  "Enviando…": "Sending…",
  "Reintentar": "Retry",
  "Chat": "Chat",
  "trabajos finalizados": "completed jobs",
  "respuesta media": "average response",
  "Eliminar una cuenta | Diime": "Delete an account | Diime",
  "Idioma": "Language",
  "Elige el idioma de Diime": "Choose your Diime language",
  "Por favor ingresa tu {documento}": "Please enter your {documento}",
  "Desde {precio}": "From {precio}",
  "Hasta {precio}": "Up to {precio}",
  "No se pudo actualizar el perfil: {error}": "Unable to update your profile: {error}",
  "Eliminar certificación {certificacion}": "Delete certification {certificacion}",
  "Editar {titulo}": "Edit {titulo}",
  "Eliminar {titulo}": "Delete {titulo}",
  "Reporte sobre {nombre}": "Report about {nombre}",
  "Ver detalles de {titulo}": "View details of {titulo}",
  "Se borrarán tus {n} demandas publicadas, junto con las ofertas que hayas recibido en ellas.": "Your {n} published requests will be deleted, along with any offers you received for them.",
  "Se retirarán tus {n} pujas pendientes: nadie podrá aceptártelas.": "Your {n} pending bids will be withdrawn: nobody will be able to accept them.",
  "Error al continuar con {proveedor}": "Unable to continue with {proveedor}",
  "Chatear con {nombre}": "Chat with {nombre}",
  "{n} valoraciones": "{n} reviews",
  "En revisión": "Under review",
  "Necesita corrección": "Changes required",
  "Verificación retirada": "Verification withdrawn",
  "Nuevas solicitudes compatibles": "New matching requests",
  "Demandas que encajan con tus servicios, provincias y presupuesto.": "Requests that match your services, provinces and budget.",
  "Ofertas y pujas": "Offers and bids",
  "Nuevas ofertas y cambios en las pujas en las que participas.": "New offers and updates to bids you are involved in.",
  "Proyectos y entregas": "Projects and deliveries",
  "Avances, entregas y cambios importantes durante un trabajo.": "Progress, deliveries and important changes during a job.",
  "Pagos y reembolsos": "Payments and refunds",
  "Cobros confirmados, pagos liberados y devoluciones.": "Confirmed payments, released funds and refunds.",
  "Disputas y cancelaciones": "Disputes and cancellations",
  "Aperturas, cambios y resoluciones que requieren atención.": "New cases, updates and resolutions that need attention.",
  "Cuenta y soporte": "Account and support",
  "Verificación del perfil y resolución de incidencias.": "Profile verification and support issue resolution.",
  "Usa «Añadir proyecto» para mostrar tus trabajos a los clientes.": "Use “Add project” to show clients your work.",
  "ELIMINAR": "DELETE",
  "España": "Spain",
  "Francia": "France",
  "Reino Unido": "United Kingdom",
  "Alemania": "Germany",
  "Italia": "Italy",
  "Estados Unidos": "United States",
  "México": "Mexico",
  "Perú": "Peru",
  "Brasil": "Brazil"
}
