export const EN_ADMIN_PAGOS: Record<string, string> = {
  "Pagos y cobros": "Payments and payouts",
  "Consulta cada pago, el reembolso registrado y su estado en Stripe.": "Review each payment, its recorded refund and its status in Stripe.",
  "Reembolso registrado": "Recorded refund",
  "Pago original": "Original payment",
  "Comisiones de Diime": "Diime fees",
  "Neto del profesional": "Professional's net amount",
  "Neto transferido a profesionales": "Net transferred to professionals",
  "No se pudieron cargar los pagos. Actualiza para volver a intentarlo.": "Payments could not be loaded. Refresh to try again.",
  "No se pudo comprobar el reembolso en Stripe.": "The refund could not be checked in Stripe.",
  "Mostrando el caso seleccionado": "Showing the selected case",
  "Ver todos los pagos": "View all payments",
  "Ver usuario": "View user",
  "No consta": "Not recorded",
  "Buscar por trabajo, cliente, profesional o referencia...": "Search by job, client, professional or reference...",
  "Detalle": "Details",
  "Ver detalle": "View details",
  "Detalle del pago": "Payment details",
  "Importes y estado registrados para esta transacción.": "Amounts and status recorded for this transaction.",
  "Fecha del reembolso registrado": "Recorded refund date",
  "Estado del reembolso registrado": "Recorded refund status",
  "Reembolso procesado por Stripe": "Refund processed by Stripe",
  "Reembolso pendiente en Stripe": "Refund pending in Stripe",
  "Reembolso requiere revisión": "Refund requires review",
  "Reembolso fallido": "Refund failed",
  "Reembolso cancelado": "Refund cancelled",
  "Referencia del reembolso": "Refund reference",
  "Un reembolso procesado por Stripe puede tardar en reflejarse en el banco del cliente. Esta pantalla no confirma su abono bancario.": "A refund processed by Stripe may take time to appear at the client's bank. This screen does not confirm that the bank has credited it.",
  "Abrir este pago en Stripe": "Open this payment in Stripe",
  "Ver incidencias del cliente": "View the client's issues",
  "Comprobar reembolso en Stripe": "Check refund in Stripe",
  "Última comprobación en Stripe": "Latest check in Stripe",
  "Creado el": "Created on",
  "Referencia bancaria para seguimiento": "Bank tracking reference",
  "Stripe todavía no facilita una referencia bancaria para seguimiento.": "Stripe does not yet provide a bank tracking reference.",
  "Estado de la referencia": "Reference status",
  "Modo de pruebas de Stripe": "Stripe test mode",
  "Pago tardío pendiente de revisar": "Late payment awaiting review",
  "Incidencias de este usuario": "This user's issues",
  "La incidencia del aviso no está disponible. Actualiza la lista o revisa el resto de incidencias.": "The issue in this notification is not available. Refresh the list or review the other issues.",
  "Buscar por asunto, nombre, email o referencia...": "Search by subject, name, email or reference...",
  "Revisar pagos y cobros": "Review payments and payouts",
  "Respuesta y resolución para el usuario": "Response and resolution for the user",
  "Esta respuesta es visible para quien reportó la incidencia. Resolver la incidencia no ejecuta un cobro ni un reembolso.": "This response is visible to the person who reported the issue. Resolving the issue does not charge or refund a payment.",
  "Revisar pago": "Review payment",
  "Pago no válido": "Invalid payment",
  "No se pudo consultar el pago": "The payment could not be retrieved",
  "Este pago no tiene un reembolso registrado en Stripe": "This payment has no refund recorded in Stripe",
  "El reembolso no corresponde al pago registrado. Revisa el caso en Stripe.": "The refund does not match the recorded payment. Review the case in Stripe.",
  "No se pudo consultar el reembolso en Stripe. Vuelve a intentarlo.": "The refund could not be retrieved from Stripe. Please try again.",
}
