export const EN_AVISOS: Record<string, string> = {
  "Notificaciones pendientes: {count}": "Unread notifications: {count}",
  "Novedades de esta sección": "Updates in this section",
  "Cada aviso indica qué ha cambiado. Ábrelo o márcalo como visto cuando lo hayas revisado.": "Each notice explains what has changed. Open it or mark it as seen when you have reviewed it.",
  "Marcar como visto": "Mark as seen",
  "Ver trabajo": "View job",
  "Ver detalle": "View details",
  "Ver todas": "View all",
  "Ver todas las novedades": "View all updates",
  "Mostrar menos": "Show less",
  "Sin leer": "Unread",
  "No tienes notificaciones pendientes": "You have no unread notifications",
  "No se pudieron cargar las notificaciones": "Notifications could not be loaded",
  "No se pudieron marcar las notificaciones": "Notifications could not be marked as seen",
  "Notificaciones no válidas": "Invalid notifications",
  "Consulta el trabajo y el motivo de cada aviso, incluidos los de tu perfil e incidencias.": "See the job and reason for each notice, including profile and support updates.",
  "Nueva solicitud": "New request",
  "Puja": "Bid",
  "Solicitud": "Request",
  "Cancelación": "Cancellation",
  "Disputa": "Dispute",
  "Pago": "Payment",
  "Entrega": "Delivery",
  "Progreso": "Progress",
  "Verificación": "Verification",
  "Incidencia": "Support issue",
  "Actualización": "Update",
  "Cargar más": "Load more",
  "Mensajes pendientes de soporte": "Unread support messages",
  "Mensajes sin leer": "Unread messages",
  "Abrir conversación": "Open conversation",
  "Ver mensajes pendientes": "View unread messages",
  "Revisa los mensajes de soporte y los avisos de administración con su contexto.": "Review support messages and administration notifications with their context.",
  "No hay notificaciones en el historial": "There are no notifications in the history",
  "No se pudo cargar la conversación. Vuelve a intentarlo.": "The conversation could not be loaded. Please try again.",
  "No se pudieron marcar los mensajes como leídos": "Messages could not be marked as read",
}
