export const EN_COBROS: Record<string, string> = {
  "Cuenta personal anterior": "Previous personal account",
  "Consulta el saldo y los ingresos de tu cuenta personal anterior.": "View the balance and payouts from your previous personal account.",
  "Tu perfil está vinculado a una empresa, pero esta cuenta de Stripe es personal. Puedes consultar tu saldo y tus ingresos anteriores. Contacta con soporte para regularizar la titularidad antes de aceptar nuevos cobros de empresa.": "Your profile is linked to a company, but this Stripe account is personal. You can view your balance and previous payouts. Contact support to resolve account ownership before accepting new payments for the company.",
  "Saldo de tu cuenta personal": "Personal account balance",
  "Disponible en tu cuenta personal": "Available in your personal account",
  "Abrir mi cuenta personal en Stripe": "Open my personal Stripe account",
  "El panel abre tu cuenta personal en una página segura de Stripe.": "The dashboard opens your personal account on a secure Stripe page.",
  "Los nuevos cobros de empresa requieren revisar la titularidad.": "Account ownership must be reviewed before accepting new company payments.",
  "Ver detalle en Cobros": "View details in Payouts",
  "No se pudo consultar Stripe. Comprueba tu conexión y vuelve a intentarlo.": "Stripe could not be reached. Check your connection and try again.",
  "Comprueba tu conexión y vuelve a intentarlo.": "Check your connection and try again.",
  "Cobros de la empresa": "Company payments",
  "Cuenta bancaria y cobros propios de la empresa.": "The company’s own bank account and payments.",
  "El responsable principal gestiona la cuenta bancaria y los datos de Stripe.": "The principal account holder manages bank details and Stripe information.",
  "Abrir cuenta de la empresa en Stripe": "Open the company account in Stripe",
  "Realizar pago protegido": "Make a protected payment",
  "Servicio contratado": "Contracted service",
  "Proveedor del contrato": "Contractual provider",
  "Confirmar entrega y liberar el pago": "Confirm delivery and release payment",
  "Confirma que el servicio está terminado y conforme. El pago retenido se liquidará al proveedor según los importes acordados.": "Confirm that the service is complete and satisfactory. The held payment will be settled with the provider at the agreed amounts.",
  "Confirmar y liberar pago": "Confirm and release payment",
  "No se pudo confirmar la entrega. Vuelve a intentarlo.": "Delivery could not be confirmed. Please try again.",
  "Los pagos no están disponibles en este momento. Inténtalo más tarde.": "Payments are currently unavailable. Please try again later.",
}
