// Shared interface and taxonomy translations.
export const EN_COMMON: Record<string, string> = {
  "Abrir chat": "Open chat",
  "Abrir": "Open",
  "Profesionales": "Professionals",
  "Solicitudes de terceros": "Other users’ requests",
  "Mis Solicitudes": "My requests",
  "Mis pujas enviadas": "My submitted bids",
  "Mis Pujas": "My bids",
  "Mis pujas": "My bids",
  "Gestión de proyectos": "Project management",
  "Mensajes": "Messages",
  "Cuenta": "Account",
  "Perfil": "Profile",
  "Mi cuenta": "My account",
  "Gestionar cobros": "Manage payouts",
  "Mi Perfil": "My profile",
  "Incidencias": "Reported issues",
  "Mi empresa": "My company",
  "Configuración": "Settings",
  "Cerrar sesión": "Sign out",
  "Entrar": "Sign in",
  "Registrarse": "Sign up",
  "Mi perfil": "My profile",
  "Entrar o acceder a mi perfil": "Sign in or open my profile",
  "Cerrar menú": "Close menu",
  "Abrir menú": "Open menu",
  "Abrir menú, {count} avisos pendientes": "Open menu, {count} unread notifications",
  "Cobros profesionales": "Professional payouts",
  "Configuracion": "Settings",
  "Cerrar Sesion": "Sign out",
  "Publicar demanda": "Post a request",
  "Navegación principal de la app": "Main app navigation",
  "Buscar profesionales": "Find professionals",
  "Ver demandas": "Browse requests",
  "Publicar proyecto": "Post a project",
  "Crear perfil": "Create a profile",
  "Mis trabajos": "My jobs",
  "Calendario": "Calendar",
  "Sobre nosotros": "About us",
  "Contacto": "Contact",
  "Centro de ayuda": "Help centre",
  "Aviso legal": "Legal notice",
  "Términos y condiciones": "Terms and conditions",
  "Normas de la comunidad": "Community guidelines",
  "Política de privacidad": "Privacy policy",
  "Política de cookies": "Cookie policy",
  "Eliminar una cuenta": "Delete an account",
  "La plataforma que conecta profesionales cualificados con clientes que buscan calidad y confianza.": "The platform that connects qualified professionals with clients looking for quality and trust.",
  "Pagos protegidos hasta la entrega": "Payments protected until delivery",
  "Plataforma": "Platform",
  "Empresa": "Company",
  "Legal": "Legal",
  "Diime. Todos los derechos reservados.": "Diime. All rights reserved.",
  "Hecho con": "Made with",
  "en España": "in Spain",
  "a qué te dedicas ni dónde trabajas": "what services you offer or where you work",
  "a qué te dedicas": "what services you offer",
  "dónde trabajas": "where you work",
  "No te estamos avisando de demandas nuevas": "You are not receiving new request alerts",
  "Todavía no nos has dicho": "You have not yet told us",
  ", y es lo que usamos para saber qué demandas mandarte. Hasta que lo completes no recibirás ninguna.": ", which we use to choose the requests to send you. You will not receive any until you complete this information.",
  "Completar mi perfil": "Complete my profile",
  "Nuevo aviso": "New notification",
  "¡Pago liberado!": "Payment released!",
  "Has cobrado un trabajo": "You have been paid for a job",
  "Ver mis cobros": "View my payouts",
  "¡Cobro protegido, a por ello!": "Payment protected — you’re ready to go!",
  "El cliente ha pagado: ya puedes empezar": "The client has paid: you can start now",
  "Ver el trabajo": "View the job",
  "¡Trabajo entregado!": "Work delivered!",
  "Tienes una entrega lista": "A delivery is ready for you",
  "Revisar la entrega": "Review the delivery",
  "Disputa resuelta a tu favor": "Dispute resolved in your favour",
  "El equipo de Diime te ha dado la razón": "The Diime team has found in your favour",
  "Ver la disputa": "View the dispute",
  "Disputa resuelta en tu contra": "Dispute resolved against you",
  "El equipo de Diime ha resuelto la disputa": "The Diime team has resolved the dispute",
  "Disputa resuelta": "Dispute resolved",
  "Cerrar": "Close",
  "Mensajes y avisos": "Messages and notifications",
  "Mensajes, ofertas y novedades importantes de Diime": "Messages, offers and important updates from Diime",
  "Cargando Diime": "Loading Diime",
  "Conectando talento y proyectos": "Connecting talent and projects",
  "Perfil revisado y verificado por el equipo de Diime": "Profile reviewed and verified by the Diime team",
  "Verificado por Diime": "Verified by Diime",
  "Sin valoraciones": "No reviews yet",
  "Profesional cualificado": "Qualified professional",
  "España": "Spain",
  "Ver todos": "View all",
  "Filtros": "Filters",
  "Restablecer": "Reset",
  "Buscar": "Search",
  "Buscar servicios...": "Search services...",
  "Provincia": "Province",
  "Selecciona una provincia": "Select a province",
  "Todas las provincias": "All provinces",
  "Categoría": "Category",
  "Rango de Precio (€/h)": "Price range (€/hour)",
  "Tarifa por hora": "Hourly rate",
  "Inicia sesión": "Sign in",
  "Necesitas una cuenta para escribir a un profesional.": "You need an account to message a professional.",
  "Eres tú": "This is you",
  "No puedes escribirte a ti mismo.": "You cannot send yourself a message.",
  "No se pudo abrir el chat.": "The chat could not be opened.",
  "Profesional en Diime": "Professional on Diime",
  "Mostrando": "Showing",
  "resultados": "results",
  "en": "in",
  "Ordenar por": "Sort by",
  "Recomendados": "Recommended",
  "Precio: Menor a Mayor": "Price: low to high",
  "Precio: Mayor a Menor": "Price: high to low",
  "Mejor Valorados": "Highest rated",
  "Más Recientes": "Newest",
  "Vista de cuadrícula": "Grid view",
  "Vista de lista": "List view",
  "No se encontraron profesionales": "No professionals found",
  "Prueba a cambiar los filtros o seleccionar otra provincia.": "Try changing the filters or selecting another province.",
  "Desde": "From",
  "Mensaje": "Message",
  "Ver Detalles": "View details",
  "Cerrando sesion...": "Signing out...",
  "Cerrar sesion": "Sign out",
  "Se necesita:": "Needed:",
  "El cliente necesita el trabajo: {plazo}": "The client needs the work: {plazo}",
  "el {fecha}": "on {fecha}",
  "{etiqueta} mínimo": "Minimum {etiqueta}",
  "{etiqueta} máximo": "Maximum {etiqueta}",
  "Presupuesto": "Budget",
  " o más": " or more",
  "a": "to",
  "Notificaciones": "Notifications",
  "Marcar todas como leídas": "Mark all as read",
  "No tienes notificaciones": "You have no notifications",
  "Selecciona un servicio": "Select a service",
  "Todas las categorías": "All categories",
  "Buscar servicio...": "Search services...",
  "Ningún servicio coincide.": "No matching services.",
  "Toda España": "All of Spain",
  "Buscar provincia...": "Search provinces...",
  "Ninguna provincia coincide.": "No matching provinces.",
  "Ninguna": "None",
  "Disponible Ahora": "Available now",
  "Próximamente": "Coming soon",
  "Verificación de Habilidades Profesionales": "Professional skills verification",
  "Para garantizar que solo profesionales cualificados estén en nuestra plataforma, requerimos que todos los profesionales pasen una prueba de verificación de habilidades en su campo elegido.": "To ensure that our platform includes only qualified professionals, we require all professionals to pass a skills verification test in their chosen field.",
  "Lanzamiento en:": "Launching in:",
  "Días": "Days",
  "Horas": "Hours",
  "Minutos": "Minutes",
  "Segundos": "Seconds",
  "Pruebas de Verificación Disponibles": "Verification tests available",
  "Realiza una prueba de verificación de habilidades en tu campo para obtener una insignia verificada y aumentar tu visibilidad ante los clientes.": "Take a skills verification test in your field to earn a verified badge and increase your visibility to clients.",
  "Verificación de habilidades": "Skills verification",
  "Qué esperar:": "What to expect:",
  "Pruebas específicas para cada categoría (Electricidad, Fontanería, Carpintería, etc.)": "Tests specific to each category (electrical work, plumbing, carpentry, etc.)",
  "Evaluaciones prácticas que miden tus habilidades del mundo real": "Practical assessments that measure your real-world skills",
  "Insignia verificada en tu perfil al completar exitosamente": "A verified badge on your profile when you pass",
  "Beneficios de la Verificación": "Benefits of verification",
  "Los profesionales verificados reciben prioridad en los resultados de búsqueda, mayor visibilidad ante los clientes y acceso a proyectos exclusivos mejor remunerados.": "Verified professionals receive priority in search results, greater visibility to clients and access to exclusive, better-paid projects.",
  "Realizar Prueba de Verificación": "Take the verification test",
  "Notificarme Cuando Esté Disponible": "Notify me when available",
  "Cambiar tema": "Change theme",
  "Activar modo claro": "Switch to light mode",
  "Activar modo oscuro": "Switch to dark mode",
  "Testimonios": "Testimonials",
  "Testimonio anterior": "Previous testimonial",
  "Siguiente testimonio": "Next testimonial",
  "Urgente (1-3 días)": "Urgent (1–3 days)",
  "Urgente": "Urgent",
  "Esta semana": "This week",
  "Este mes": "This month",
  "Flexible": "Flexible",
  "Reformas y Construcción": "Renovation and construction",
  "Estructura y obra civil": "Structural work and civil engineering",
  "Reformas integrales": "Full renovations",
  "vivienda completa, reforma parcial, locales y oficinas": "whole homes, partial renovations, commercial premises and offices",
  "Albañilería": "Masonry",
  "Albañil": "Mason",
  "tabiquería, muros, enlucidos, obra menor": "partitions, walls, plastering, minor building work",
  "Demoliciones y desescombro": "Demolition and rubble removal",
  "retirada de escombros, contenedores, vaciados": "rubble removal, skips, property clearance",
  "Fachadas": "Façades",
  "rehabilitación, SATE, revestimientos": "restoration, external wall insulation, cladding",
  "Tejados y cubiertas": "Roofs and roofing",
  "reparación, canalones, tejas": "repairs, gutters, roof tiles",
  "Instalaciones técnicas": "Building services",
  "Fontanería": "Plumbing",
  "instalación, averías y fugas, calentadores/termos, saneamiento": "installation, faults and leaks, water heaters, drainage",
  "Electricidad": "Electrical work",
  "instalaciones, boletines, cuadros eléctricos, iluminación": "installations, electrical certificates, distribution boards, lighting",
  "Climatización": "Heating and air conditioning",
  "aire acondicionado, calefacción, calderas, suelo radiante": "air conditioning, heating, boilers, underfloor heating",
  "Instalación de gas": "Gas installation",
  "calderas, butano/propano, boletines de gas": "boilers, butane/propane, gas certificates",
  "Domótica e instalaciones inteligentes": "Home automation and smart installations",
  "automatización del hogar, seguridad integrada": "home automation, integrated security",
  "Acabados e interiorismo": "Finishing and interior design",
  "Pintura y decoración": "Painting and decorating",
  "interior, exterior, papel pintado, estucos, microcemento": "interior, exterior, wallpaper, stucco, microcement",
  "Carpintería": "Carpentry and joinery",
  "madera a medida, puertas, armarios empotrados, PVC, aluminio": "bespoke woodwork, doors, fitted wardrobes, PVC, aluminium",
  "Solados y alicatados": "Flooring and tiling",
  "suelos (parquet, tarima, gres, mármol), azulejos": "flooring (parquet, wood, stoneware, marble), wall tiles",
  "Techos y falsos techos": "Ceilings and suspended ceilings",
  "pladur, escayola, techos técnicos": "plasterboard, plaster, technical ceilings",
  "Ventanas y cerramientos": "Windows and enclosures",
  "PVC, aluminio, climalit, persianas, mosquiteras": "PVC, aluminium, double glazing, shutters, insect screens",
  "Vidrio y cristalería a medida": "Bespoke glass and glazing",
  "mamparas, espejos, vidrio de seguridad": "screens, mirrors, safety glass",
  "Cocinas": "Kitchens",
  "diseño, montaje, encimeras, electrodomésticos integrados": "design, installation, worktops, integrated appliances",
  "Baños": "Bathrooms",
  "diseño, platos de ducha, mamparas, sanitarios y grifería": "design, shower trays, screens, sanitaryware and taps",
  "Aislamiento, eficiencia y patologías": "Insulation, efficiency and building defects",
  "Aislamiento e impermeabilización": "Insulation and waterproofing",
  "térmico, acústico, cubiertas, terrazas, humedades": "thermal, acoustic, roofs, terraces, damp",
  "Energía y eficiencia": "Energy and efficiency",
  "placas solares, aerotermia, mejora de calificación energética": "solar panels, air source heat pumps, energy rating improvements",
  "Detección de fugas y humedades": "Leak and damp detection",
  "cámara termográfica, diagnóstico previo": "thermal imaging, initial diagnosis",
  "Tratamiento de madera": "Timber treatment",
  "carcoma, termitas": "woodworm, termites",
  "Seguridad y accesibilidad": "Security and accessibility",
  "Cerrajería": "Locksmith services",
  "cerraduras, puertas blindadas/acorazadas, rejas y vallado": "locks, reinforced/security doors, grilles and fencing",
  "Accesibilidad": "Accessibility",
  "ascensores, salvaescaleras, rampas": "lifts, stairlifts, ramps",
  "Proyecto y gestión": "Design and project management",
  "Arquitectura e interiorismo": "Architecture and interior design",
  "proyectos, planos, dirección de obra, render 3D": "designs, plans, site supervision, 3D rendering",
  "Certificados y gestión de obra": "Certificates and construction management",
  "certificado energético, licencia de obra, ITE, cédula de habitabilidad": "energy certificates, building permits, building inspections (ITE), certificates of habitability",
  "Hogar y mantenimiento": "Home and maintenance",
  "Limpieza": "Cleaning",
  "hogar, oficinas, fin de obra, cristales, tapicerías": "homes, offices, post-construction, windows, upholstery",
  "Montaje de muebles": "Furniture assembly",
  "Restauración y tapicería de muebles": "Furniture restoration and upholstery",
  "\"Manitas\" / pequeñas reparaciones": "Handyperson / minor repairs",
  "Control de plagas": "Pest control",
  "Mudanzas, portes y guardamuebles": "Removals, transport and storage",
  "Exteriores y jardín": "Outdoors and gardens",
  "Jardinería y poda": "Gardening and pruning",
  "Diseño de jardines y paisajismo": "Garden design and landscaping",
  "Riego automático": "Automatic irrigation",
  "Piscinas": "Swimming pools",
  "construcción, reforma y mantenimiento": "construction, renovation and maintenance",
  "Toldos, pérgolas y protección solar": "Awnings, pergolas and sun protection",
  "Vallados y cerramientos exteriores": "Fencing and outdoor enclosures",
  "Automoción": "Automotive services",
  "Mecánica general": "General vehicle mechanics",
  "Chapa y pintura": "Vehicle bodywork and painting",
  "Neumáticos": "Tyres",
  "Lavado y detailing": "Car washing and detailing",
  "Asistencia en carretera": "Roadside assistance",
  "Tecnología y electrónica": "Technology and electronics",
  "Reparación de móviles y ordenadores": "Mobile phone and computer repairs",
  "Reparación de electrodomésticos": "Appliance repairs",
  "Instalación de TV, antenas y fibra": "TV, aerial and fibre installation",
  "Soporte informático a domicilio": "Home IT support",
  "Alarmas y videovigilancia": "Alarms and video surveillance",
  "Eventos": "Events",
  "Catering": "Catering",
  "Fotografía y vídeo": "Photography and video",
  "Música y DJ": "Music and DJs",
  "Decoración de eventos": "Event decoration",
  "Animación infantil": "Children’s entertainment",
  "Moda y textil": "Fashion and textiles",
  "Arreglos de ropa y costura": "Clothing alterations and sewing",
  "Modistas a medida": "Bespoke dressmaking",
  "Otros": "Other",
  "servicios no incluidos en las demás categorías": "services not covered by the other categories",
  "Imagen": "Image",
  "Documento": "Document",
  "Profesional": "Professional",
  "Ir al testimonio {count}": "Go to testimonial {count}",
  "Propietaria, Madrid": "Homeowner, Madrid",
  "Electricista profesional": "Professional electrician",
  "Cliente, Barcelona": "Client, Barcelona",
  "Consultar": "Enquire",
  "Servicios Generales": "General services",
  "Perfil verificado por el equipo de Diime": "Profile verified by the Diime team",
  "Clienta sonriendo": "Smiling client",
  "Profesional de la construcción en una obra": "Construction professional at a building site",
  "Consentimiento de cookies": "Cookie consent",
  "Solicitud no válida": "Invalid request",
  "Faltan datos del mensaje": "Message details are missing",
  "Adjunto no válido": "Invalid attachment",
  "Encontre al fontanero perfecto para mi reforma en menos de 24 horas. El trabajo quedo impecable y el precio fue muy competitivo. Volvere a usar Diime sin duda.": "I found the perfect plumber for my renovation in under 24 hours. The work was impeccable and the price was very competitive. I will definitely use Diime again.",
  "Como electricista, Diime me ha permitido encontrar clientes de calidad de forma constante. La plataforma es muy intuitiva y los pagos siempre llegan a tiempo.": "As an electrician, Diime has helped me find good clients consistently. The platform is very intuitive and payments always arrive on time.",
  "El sistema de pagos seguros me da mucha tranquilidad. Contrate a un pintor y no se libero el pago hasta que el trabajo estuvo terminado a mi gusto. Recomendado al 100%.": "The secure payment system gives me real peace of mind. I hired a painter and the payment was not released until the work was completed to my satisfaction. I fully recommend it.",
  "Tras anos buscando trabajos por mi cuenta, Diime me ha simplificado todo. Ahora puedo centrarme en lo que mejor hago: ofrecer servicios de calidad a mis clientes.": "After years of finding jobs on my own, Diime has made everything simpler. Now I can focus on what I do best: providing quality services to my clients."
}
