export const EN_DEMANDAS: Record<string, string> = {
  "Filtros guardados": "Saved filters",
  "Guardar filtros": "Save filters",
  "Gestionar filtros guardados": "Manage saved filters",
  "Volver a aplicar": "Apply again",
  "Actualizar con los filtros actuales": "Update with current filters",
  "Filtros actualizados": "Filters updated",
  "Cambiar nombre": "Rename",
  "Eliminar filtros guardados": "Delete saved filters",
  "Filtros eliminados": "Filters deleted",
  "Nombre actualizado": "Name updated",
  "Escribe un nombre para estos filtros.": "Enter a name for these filters.",
  "Ya tienes unos filtros guardados con este nombre.": "You already have saved filters with this name.",
  "No se pudieron guardar los filtros": "Could not save filters",
  "Puedes guardar hasta {count} búsquedas.": "You can save up to {count} searches.",
  "Comprueba que el navegador permita guardar datos en este dispositivo.": "Check that your browser allows data to be saved on this device.",
  "Este navegador no permite guardar tus filtros.": "This browser does not allow your filters to be saved.",
  "Has cambiado los filtros. La búsqueda guardada conserva su configuración anterior.": "You have changed the filters. Your saved search keeps its previous settings.",
  "Tus búsquedas se guardan para tu cuenta en este dispositivo.": "Your searches are saved for your account on this device.",
  "Guarda la categoría, ubicación, presupuesto, plazo, búsqueda y orden actuales para aplicarlos con un clic.": "Save the current category, location, budget, date range, search and sort order to apply them in one click.",
  "Nombre de la búsqueda": "Search name",
  "Por ejemplo: Reformas en Madrid": "For example: Renovations in Madrid",
  "Esta solicitud ya no está disponible": "This request is no longer available",
  "Puede haberse cerrado o eliminado. El aviso conserva el contexto de la solicitud.": "It may have been closed or deleted. The notification keeps the request's context.",
  "Solo con novedades": "Unread updates only",
  "Las tarjetas resaltadas muestran qué ha cambiado en cada solicitud.": "Highlighted cards show what has changed in each request.",
}
