// Company UI and server messages. Names, roles entered by users, bios and reviews keep their original language.
export const EN_EMPRESAS: Record<string, string> = {
  "Listo": "Done",
  "Revisa los servicios anteriores antes de guardar.": "Review the previous services before saving.",
  "Estos servicios anteriores no coinciden con la lista actual. Revisa la selección antes de guardar.": "These previous services do not match the current list. Review the selection before saving.",
  "He revisado los servicios seleccionados.": "I have reviewed the selected services.",
  "Selecciona al menos una provincia válida de la lista.": "Select at least one valid province from the list.",
  "Selecciona al menos un servicio válido de la lista.": "Select at least one valid service from the list.",
  "Esta identidad no está disponible en la prueba local.": "This identity is unavailable in the local test.",
  "No tienes permiso para realizar esta acción en nombre de la empresa.": "You do not have permission to perform this action on behalf of the company.",
  "Solo el responsable principal puede presentar la verificación de la empresa.": "Only the account owner can submit the company for verification.",
  "Selecciona un rol válido. El responsable principal no se asigna desde una invitación.": "Select a valid role. The account owner cannot be appointed through an invitation.",
  "Solo el responsable principal puede designar administradores.": "Only the account owner can appoint administrators.",
  "Selecciona los permisos del miembro.": "Select the member's permissions.",
  "Debes indicar expresamente cada permiso.": "You must explicitly specify each permission.",
  "No puedes conceder permisos que no tienes.": "You cannot grant permissions you do not have.",
  "La invitación no existe o el enlace no es válido.": "The invitation does not exist or the link is invalid.",
  "El estado local no es compatible. Conserva una copia y reinicia la prueba.": "The local state is incompatible. Keep a copy and restart the test.",
  "No se pudo guardar el cambio local. Vuelve a intentarlo.": "The local change could not be saved. Please try again.",
  "Tu cuenta no tiene acceso activo a esta empresa. Si has recibido una invitación, abre su enlace para aceptarla.": "Your account does not have active access to this company. If you received an invitation, open its link to accept it.",
  "La web corporativa debe usar https://.": "The company website must use https://.",
  "Selecciona entre 1 y 12 servicios.": "Select between 1 and 12 services.",
  "Completa la verificación de la empresa antes de invitar al equipo.": "Complete company verification before inviting the team.",
  "Esta persona ya forma parte del equipo.": "This person is already part of the team.",
  "Ya hay una invitación pendiente para este correo.": "There is already a pending invitation for this email address.",
  "El miembro no tiene acceso activo.": "The member does not have active access.",
  "El responsable principal está protegido. Su sustitución requiere una nueva acreditación.": "The account owner is protected. Replacing them requires new verification.",
  "No puedes modificar tus propios permisos.": "You cannot change your own permissions.",
  "Solo el responsable principal puede modificar a otro administrador.": "Only the account owner can make changes to another administrator.",
  "No puedes revocar tu propio acceso desde aquí.": "You cannot revoke your own access here.",
  "Solo el responsable principal puede revocar a otro administrador.": "Only the account owner can revoke another administrator's access.",
  "Esta invitación ya no está pendiente.": "This invitation is no longer pending.",
  "Solo el responsable principal puede cancelar la invitación de un administrador.": "Only the account owner can cancel an administrator's invitation.",
  "La empresa debe completar su verificación antes de incorporar nuevos miembros.": "The company must complete verification before adding new members.",
  "La invitación ha caducado. Pide una nueva al administrador.": "The invitation has expired. Ask the administrator for a new one.",
  "Esta invitación ya se ha utilizado o ha sido revocada.": "This invitation has already been used or has been revoked.",
  "Ya formas parte de esta empresa.": "You are already part of this company.",
  "La persona que te invitó ya no puede gestionar el equipo. Pide una nueva invitación.": "The person who invited you can no longer manage the team. Request a new invitation.",
  "La documentación ya está en revisión.": "The documentation is already under review.",
  "Selecciona un método de acreditación válido.": "Select a valid verification method.",
  "Confirma la autorización para representar a la empresa.": "Confirm your authorisation to represent the company.",
  "Adjunta un PDF de hasta 5 MB.": "Attach a PDF of up to 5 MB.",
  "El archivo debe ser un documento PDF válido.": "The file must be a valid PDF document.",
  "El documento debe tener extensión .pdf.": "The document must have a .pdf extension.",
  "Solo el responsable principal y el equipo Diime pueden consultar esta documentación.": "Only the account owner and the Diime team can view this documentation.",
  "Todavía no se ha presentado documentación.": "No documentation has been submitted yet.",
  "El documento privado no está disponible.": "The private document is unavailable.",
  "La revisión corresponde al equipo Diime; el representante no puede aprobar su propia solicitud.": "The Diime team performs the review; the representative cannot approve their own application.",
  "No hay una solicitud pendiente de revisión.": "There is no application awaiting review.",
  "La decisión no es válida.": "The decision is invalid.",
  "La empresa no está disponible.": "The company is unavailable.",
  "Esta empresa debe completar su verificación antes de recibir nuevas solicitudes.": "This company must complete verification before receiving new requests.",
  "Solo el titular puede gestionar la empresa": "Only the account owner can manage the company",
  "Utiliza el enlace personal de invitación de la empresa": "Use your personal company invitation link",
  "Confirma tu correo antes de crear una empresa": "Confirm your email before creating a company",
  "Indica el nombre, CIF y documento del titular de la empresa": "Enter the company name, tax ID (CIF) and the account owner's identity document",
  "Ya perteneces a otra empresa": "You already belong to another company",
  "Indica un correo y cargo válidos": "Enter a valid email address and job title",
  "Invitación no válida": "Invalid invitation",
  "La empresa ya no está disponible": "The company is no longer available",
  "La invitación ha caducado o ya se ha utilizado": "The invitation has expired or has already been used",
  "Inicia sesión con el correo verificado al que se dirigió la invitación": "Sign in with the verified email address the invitation was sent to",
  "Completa tu perfil profesional antes de unirte al equipo": "Complete your professional profile before joining the team",
  "La invitación no está pendiente o no pertenece a tu empresa": "The invitation is no longer pending or does not belong to your company",
  "El titular no puede darse de baja de su propia empresa": "The account owner cannot leave their own company",
  "Indica el cargo del profesional": "Enter the professional's job title",
  "El profesional no pertenece al equipo activo": "The professional is not an active team member",
  "Revisa el nombre, descripción y servicios de la empresa": "Review the company's name, description and services",
  "La web debe comenzar por https:// o http://": "The website address must start with https:// or http://",
  "El logo debe ser una imagen alojada mediante https://": "The logo must be an image hosted at an https:// address",
  "La operación empresarial requiere una sesión personal": "Acting on behalf of a company requires you to sign in to your personal account",
  "La operación debe conservar al profesional que la realiza": "The operation must retain the identity of the professional performing it",
  "Ya no perteneces al equipo activo de esta empresa": "You are no longer an active member of this company",
  "No puedes pujar por una solicitud de tu propia empresa": "You cannot bid on a request from your own company",
  "La baja de la empresa impide gestionar sus ofertas recibidas": "The company's removal prevents you from managing its received offers",
  "La identidad y autoría de la operación son inmutables": "The identity and authorship recorded for the operation cannot be changed",
  "La baja de la empresa impide operar en su nombre": "The company's removal prevents you from acting on its behalf",
  "No puedes contratar en nombre de esta empresa": "You cannot hire on behalf of this company",
  "El autor de la oferta ya no pertenece a la empresa; solicita una nueva oferta": "The person who submitted the offer no longer belongs to the company; request a new offer",
  "La empresa no puede contratarse a sí misma": "The company cannot hire itself",
  "La identidad y autoría del contrato son inmutables": "The identity and authorship recorded for the contract cannot be changed",
  "El destino de cobro del contrato es inmutable": "The contract's payment destination cannot be changed",
  "Solo el cliente puede preparar este pago": "Only the customer can prepare this payment",
  "El trabajo no admite preparar un pago": "A payment cannot be prepared for this job",
  "La cuenta de cobros no está configurada": "The payment account has not been set up",
  "El destinatario de cobros ya está fijado": "The payment recipient has already been fixed",
  "No se puede cambiar el destinatario de un pago ya preparado": "The recipient of a payment that has already been prepared cannot be changed",
  "La empresa del contrato no tiene un titular de cobros identificado": "The company named in the contract has no identified payment account holder",
  "El destino no pertenece al titular del contrato": "The payment destination does not belong to the contract's account holder",
  "El contrato no tiene un destinatario de cobros fijado": "The contract has no fixed payment recipient",
  "Indica permisos válidos": "Enter valid permissions",
  "Los permisos deben ser valores booleanos conocidos": "Permissions must use recognised boolean values",
  "No tienes permiso para realizar esta operación de empresa": "You do not have permission to perform this company operation",
  "Solo el responsable principal puede nombrar administradores": "Only the account owner can appoint administrators",
  "No puedes conceder permisos que no tienes": "You cannot grant permissions you do not have",
  "La autorización de esta invitación ya no está vigente": "This invitation is no longer authorised",
  "Completa tu perfil personal antes de unirte al equipo": "Complete your personal profile before joining the team",
  "La persona no pertenece al equipo activo": "This person is not an active team member",
  "El responsable principal no puede ser revocado ni sustituido por esta acción": "This action cannot revoke or replace the account owner",
  "El rol indicado no es válido": "The specified role is invalid",
  "Solo el responsable principal puede gestionar administradores o sus propios permisos": "Only the account owner can manage administrators or their own permissions",
  "Indica un cargo válido": "Enter a valid job title",
  "No puedes revocar esta invitación": "You cannot revoke this invitation",
  "Solo los administradores pueden asignar encargos": "Only administrators can assign jobs",
  "El encargo no pertenece a esta empresa": "This job does not belong to this company",
  "El encargo ya está cerrado": "This job is already closed",
  "La persona asignada debe estar activa y tener permiso para encargos": "The assigned person must be active and have permission to manage jobs",
  "No puedes actualizar este encargo": "You cannot update this job",
  "El encargo no admite avances mientras no esté en progreso o tenga una incidencia pendiente": "Progress cannot be updated unless the job is in progress and has no pending issue",
  "Indica un progreso entre 0 y 100": "Enter progress between 0 and 100",
  "No tienes permiso para esta operación empresarial": "You do not have permission for this company operation",
  "La representación de la empresa debe estar verificada antes de operar": "The company's representation must be verified before it can operate",
  "No puedes contratar por una empresa pendiente de verificación o sin permiso para encargos": "You cannot hire for a company awaiting verification or without permission to manage jobs",
  "La oferta no tiene una autorización empresarial vigente": "The offer has no current company authorisation",
  "No puedes reasignar el encargo del cliente": "You cannot reassign the customer's job",
  "No puedes reasignar el encargo del proveedor": "You cannot reassign the provider's job",
  "Ya no tienes permiso para operar este encargo empresarial": "You no longer have permission to manage this company job",
  "Revisa la autorización, el representante y el documento PDF": "Review the authorisation, representative and PDF document",
  "Adjunta un documento PDF de hasta 5 MB": "Attach a PDF document of up to 5 MB",
  "La empresa ya está verificada o tiene una revisión pendiente": "The company is already verified or has a pending review",
  "Solo el equipo administrador de Diime puede revisar la representación": "Only the Diime administration team can review company representation",
  "Indica una decisión y las comprobaciones realizadas": "Enter a decision and the checks performed",
  "No hay una revisión pendiente para esta empresa": "There is no pending review for this company",
  "No puedes aprobar ni revisar tu propia solicitud": "You cannot approve or review your own application",
  "No tienes permiso para revisar empresas": "You do not have permission to review companies",
  "No tienes acceso al documento de representación": "You do not have access to the representation document",
  "Trabajo no disponible": "Job unavailable",
  "La oferta no corresponde a este trabajo": "The offer does not match this job",
  "Oferta no disponible": "Offer unavailable",
  "La oferta no corresponde a esta demanda": "The offer does not match this request",
  "El destinatario no corresponde a esta oferta": "The recipient does not match this offer",
  "Demanda no disponible": "Request unavailable",
  "Proveedor no disponible": "Provider unavailable",
  "Empresa no disponible": "Company unavailable",
  "Contexto de empresa no válido": "Invalid company context",
  "La conversación está bloqueada": "This conversation is blocked",
  "No tienes permiso para responder": "You do not have permission to reply",
  "Mensaje no válido": "Invalid message",
  "No se puede identificar la parte que solicita la cancelación": "The party requesting cancellation cannot be identified",
  "La parte que solicitó la cancelación es inmutable": "The party that requested cancellation cannot be changed",
  "No tienes permiso para gestionar los cobros de este trabajo": "You do not have permission to manage payments for this job",
  "Empresa no encontrada": "Company not found",
  "Solo el responsable principal puede configurar Stripe": "Only the account owner can configure Stripe",
  "Cuenta Stripe no válida": "Invalid Stripe account",
  "Una cuenta personal no puede convertirse en cuenta de empresa": "A personal account cannot be converted into a company account",
  "Profesional no disponible": "Professional unavailable",
  "Una cuenta de empresa no puede convertirse en cuenta personal": "A company account cannot be converted into a personal account",
  "Estado Stripe no válido": "Invalid Stripe status",
  "Solo un cliente autorizado puede preparar este pago": "Only an authorised customer can prepare this payment",
  "Las empresas del contrato deben estar verificadas antes de preparar nuevos pagos": "The companies named in the contract must be verified before new payments can be prepared",
  "La empresa proveedora necesita un responsable de trabajo activo y estar verificada": "The provider company must be verified and have an active person in charge of the job",
  "El destino no pertenece al titular del contrato o no está habilitado": "The payment destination does not belong to the contract's account holder or is not enabled",
  "Solo un cliente autorizado confirma": "Only an authorised customer can confirm",
  "La cancelación no está aceptada por una contraparte autorizada": "The cancellation has not been accepted by an authorised counterparty",
  "La cancelación histórica requiere conciliar su parte solicitante": "The requesting party for this historical cancellation must be reconciled",
  "Solo la contraparte autorizada puede responder a la cancelación": "Only the authorised counterparty can respond to the cancellation",
  "Cancelación no aceptada por contraparte autorizada": "Cancellation not accepted by an authorised counterparty",
  "Acción de cancelación no válida": "Invalid cancellation action",
  "El trabajo ya no admite modificar esta cancelación": "This job no longer allows changes to this cancellation",
  "Archivos adjuntos no válidos": "Invalid attachments",
  "Ya hay una solicitud de cancelación pendiente": "A cancellation request is already pending",
  "Solo la parte que solicitó la cancelación puede modificarla mientras esté pendiente": "Only the party that requested cancellation can change it while it is pending",
  "Solo la parte que abrió la disputa puede retirarla.": "Only the party that opened the dispute can withdraw it.",
  "La disputa no existe.": "The dispute does not exist.",
  "Esta disputa ya no está abierta: no se puede retirar.": "This dispute is no longer open and cannot be withdrawn.",
  "Un contracargo bancario debe gestionarse en Stripe y no puede retirarse aquí.": "A bank chargeback must be handled in Stripe and cannot be withdrawn here.",
  "Diime ya ha iniciado la resolución económica. No se puede retirar la disputa.": "Diime has already started the financial settlement. The dispute cannot be withdrawn.",
  "Este expediente necesita conciliar su pago antes de poder retirarse.": "This case's payment must be reconciled before it can be withdrawn.",
  "No se pudo completar la operación. Vuelve a intentarlo.": "The operation could not be completed. Please try again.",
  "No se pudo completar la operación local.": "The local operation could not be completed.",
  "El responsable principal no se modifica desde la demostración.": "The account owner cannot be changed in the demo.",
  "Selecciona la empresa que deseas revisar.": "Select the company you want to review.",
  "No hay documentación disponible para esta empresa.": "No documentation is available for this company.",
  "No se pudo cargar tu empresa. Vuelve a intentarlo.": "Your company could not be loaded. Please try again.",
  "Solo el responsable principal puede configurar la cuenta bancaria y acceder al panel de la empresa.": "Only the account owner can configure the bank account and access the company's payment dashboard.",
  "No tienes permiso para consultar los cobros de esta empresa.": "You do not have permission to view this company's payments.",
  "No se pudieron consultar los cobros de la empresa.": "The company's payments could not be retrieved.",
  "No se pudo leer tu perfil de cobros.": "Your payment profile could not be retrieved.",
  "La cuenta de cobros ha cambiado. Actualiza el estado para volver a comprobarlo.": "The payment account has changed. Refresh its status to check again.",
  "Ya no tienes permiso para consultar los cobros de esta empresa.": "You no longer have permission to view this company's payments.",
  "La cuenta de cobros ha cambiado. Actualiza el estado antes de continuar.": "The payment account has changed. Refresh its status before continuing.",
  "Ya no tienes permiso para configurar la cuenta de la empresa.": "You no longer have permission to configure the company's account.",
  "Ya no tienes permiso para acceder al panel de la empresa.": "You no longer have permission to access the company's payment dashboard.",
  "Todavía no formas parte de una empresa.": "You are not part of a company yet.",
  "La contratación no tiene un titular de cobros identificado.": "The contract has no identified payment account holder.",
  "No se pudo actualizar la cancelación.": "The cancellation could not be updated.",
  "No se pudo identificar la parte que solicita la cancelación.": "The party requesting cancellation could not be identified.",
  "Solo la otra parte puede responder a esta cancelación.": "Only the other party can respond to this cancellation.",
  "El espacio de empresas de prueba solo está disponible en el entorno local.": "The test company workspace is only available in the local environment.",
  "Esta función local solo se puede abrir desde localhost.": "This local feature can only be opened from localhost.",
  "La identidad local no es válida. Elige una de las cuentas de prueba.": "The local identity is invalid. Choose one of the test accounts.",
  "No se pudo abrir el espacio de empresa local.": "The local company workspace could not be opened.",
  "No se pudo abrir esta invitación local.": "This local invitation could not be opened.",
  "No se pudo abrir el documento local.": "The local document could not be opened.",
  "La cuenta de cobros no corresponde a tu actividad personal. Contacta con soporte para revisar la titularidad. Se conserva la cuenta y su historial.": "The payment account does not match your personal activity. Contact support to review its ownership. The account and its history are retained.",
  "La cuenta de cobros no corresponde a esta empresa. Contacta con soporte para revisar la titularidad. Se conserva el destino de los contratos existentes.": "The payment account does not belong to this company. Contact support to review its ownership. The payment destination for existing contracts is retained.",
  "Continuar": "Continue",
  "Las invitaciones de empresa se aceptan desde el enlace individual enviado por el titular.": "Company invitations are accepted through the individual link sent by the account owner.",
  "Confirma tu correo y continúa para aceptar la invitación desde tu cuenta.": "Confirm your email and continue to accept the invitation from your account.",
  "Esta invitación pertenece a otra cuenta. Inicia sesión con el correo al que se dirigió la invitación.": "This invitation belongs to another account. Sign in with the email address it was sent to.",
  "Iniciar sesión con otra cuenta": "Sign in with another account",
  "No se pudo aceptar la invitación. Vuelve a intentarlo.": "The invitation could not be accepted. Please try again.",
  "Invitación de empresa": "Company invitation",
  "Tu cuenta puede actuar en nombre de la empresa con los permisos concedidos.": "Your account can act on behalf of the company with the permissions granted.",
  "Entrar en Mi empresa": "Go to My company",
  "Caduca": "Expires",
  "Podrás actuar con estos permisos": "You will have these permissions",
  "Esta invitación pertenece a otra cuenta. Inicia sesión con el correo indicado para aceptarla.": "This invitation belongs to another account. Sign in with the specified email address to accept it.",
  "Esta invitación ya no está disponible.": "This invitation is no longer available.",
  "Aceptar y unirme a la empresa": "Accept and join the company",
  "Tu cuenta sigue siendo personal. La empresa conservará el historial de las acciones que realices en su nombre.": "Your account remains personal. The company will keep a record of the actions you take on its behalf.",
  "Ver perfil de la empresa": "View company profile",
  "Cobros de la empresa": "Company payments",
  "Tu cuenta no tiene permiso para consultar los cobros de esta empresa.": "Your account does not have permission to view this company's payments.",
  "El responsable principal puede concederte acceso de consulta. Atender solicitudes o preparar presupuestos no da acceso al saldo ni a los datos bancarios.": "The account owner can grant you viewing access. Handling requests or preparing quotes does not grant access to the balance or bank details.",
  "Los servicios contratados a la empresa se cobran en su cuenta, independientemente de quién los gestione.": "Payments for services contracted with the company go to its account, regardless of who manages them.",
  "Sin conectar": "Not connected",
  "Titular de los cobros": "Payment account holder",
  "Una cuenta de cobros para todo el equipo": "One payment account for the whole team",
  "Sin datos": "No data",
  "Esta empresa de prueba no tiene una cuenta Stripe conectada. Los saldos y movimientos aparecerán cuando se integre la cuenta de cobros de la empresa.": "This test company has no connected Stripe account. Balances and transactions will appear once the company's payment account is integrated.",
  "Cómo activar los cobros": "How to enable payments",
  "La activación y los cambios de titularidad o cuenta bancaria corresponden al responsable principal.": "The account owner handles activation and changes to ownership or bank details.",
  "Del pago al ingreso": "From payment to payout",
  "El empleado puede gestionar el trabajo con sus permisos. Su cuenta bancaria personal no recibe el pago de la empresa.": "Employees can manage the job within their permissions. Their personal bank accounts do not receive the company's payment.",
  "La salida de un miembro no cambia el destinatario de los cobros ni el historial. La empresa gestiona por su cuenta la remuneración de su equipo.": "A member leaving does not change the payment recipient or history. The company manages its team's remuneration separately.",
  "Activar cobros a nombre de la empresa": "Enable payments in the company's name",
  "Este es el recorrido previsto. La versión local no abre Stripe ni crea una cuenta de cobros.": "This is the planned process. The local version does not open Stripe or create a payment account.",
  "1. Representación acreditada en Diime": "1. Representation verified by Diime",
  "El responsable principal acredita la autorización para gestionar la empresa.": "The account owner provides evidence of authorisation to manage the company.",
  "2. Alta de la empresa en Stripe": "2. Register the company with Stripe",
  "Se completa la información de la sociedad, sus representantes y los demás datos que Stripe solicite.": "Provide information about the company, its representatives and any other details Stripe requests.",
  "3. Cuenta bancaria de la empresa": "3. Company bank account",
  "El responsable configura el destino bancario mediante el formulario seguro de Stripe. Solo se habilitan pagos cuando la cuenta reúne los requisitos.": "The account owner sets up the receiving bank account using Stripe's secure form. Payments are enabled only when the account meets the requirements.",
  "La verificación de Stripe para cobrar y la autorización para administrar una empresa en Diime son comprobaciones distintas.": "Stripe's verification for receiving payments and authorisation to manage a company on Diime are separate checks.",
  "No se pudo completar la acción. Vuelve a intentarlo.": "The action could not be completed. Please try again.",
  "Ver perfil público": "View public profile",
  "Puedes enviar pujas y contratar con el perfil de la empresa. Elige la empresa al publicar o pujar; cada acción quedará asociada a tu cuenta.": "You can bid and hire using the company profile. Select the company when posting or bidding; each action will be linked to your account.",
  "Ver solicitudes": "View requests",
  "Publicar solicitud": "Post a request",
  "Equipo": "Team",
  "Perfil de empresa": "Company profile",
  "Información que aparece en vuestro perfil público.": "Information shown on your public profile.",
  "Zona de trabajo": "Service area",
  "Web corporativa": "Company website",
  "Separa cada servicio con una coma.": "Separate services with commas.",
  "Solo el titular puede editar el perfil de la empresa.": "Only the account owner can edit the company profile.",
  "Profesionales vinculados": "Linked professionals",
  "Cada persona mantiene su perfil personal y aparece en el equipo con su cargo.": "Each person keeps their personal profile and appears in the team with their job title.",
  "Invitar miembro": "Invite a member",
  "Invitación lista para compartir": "Invitation ready to share",
  "Solo esa cuenta podrá aceptarla. No se ha enviado ningún correo.": "Only that account can accept it. No email has been sent.",
  "Enlace de invitación": "Invitation link",
  "Copiar enlace": "Copy link",
  "El enlace caduca a los 7 días y solo puede aceptarse una vez.": "The link expires after 7 days and can only be accepted once.",
  "Miembro del equipo": "Team member",
  "Titular": "Account owner",
  "Esta persona todavía no ha añadido una presentación.": "This person has not added a bio yet.",
  "Editar cargo": "Edit job title",
  "Dar de baja": "Remove member",
  "Invitaciones pendientes": "Pending invitations",
  "Cancelar invitación": "Cancel invitation",
  "Actividad de la empresa": "Company activity",
  "Queda registrado quién realiza cada acción con el perfil de la empresa, incluso después de dejar el equipo.": "Each action taken using the company profile records who performed it, even after they leave the team.",
  "Aquí quedarán registradas las acciones del equipo.": "Team actions will be recorded here.",
  "Correo de su cuenta Diime": "Their Diime account email",
  "Cargo en la empresa": "Job title at the company",
  "Al aceptar podrá enviar pujas y contratar en nombre de la empresa. Solo el titular gestiona el equipo.": "Once they accept, they can bid and hire on behalf of the company. Only the account owner manages the team.",
  "Dejará de aparecer en el equipo y perderá el acceso para actuar en nombre de la empresa. Sus acciones anteriores se conservarán.": "They will no longer appear in the team or have access to act on behalf of the company. Their previous actions will be retained.",
  "Confirmar baja": "Confirm removal",
  "No se pudo crear la invitación.": "The invitation could not be created.",
  "Invitación creada. Comparte el enlace con la persona indicada.": "Invitation created. Share the link with the intended person.",
  "Permisos actualizados.": "Permissions updated.",
  "No se pudieron guardar los cambios. Vuelve a intentarlo.": "The changes could not be saved. Please try again.",
  "No se pudo copiar automáticamente. Selecciona y copia el enlace.": "The link could not be copied automatically. Select and copy it manually.",
  "Adjunta un documento PDF de hasta 5 MB.": "Attach a PDF document of up to 5 MB.",
  "Documentación recibida y pendiente de revisión por Diime.": "Documents received and awaiting review by Diime.",
  "Gestión de empresa": "Company management",
  "Perfil guardado. Los cambios ya aparecen en el perfil público.": "Profile saved. The changes now appear on the public profile.",
  "Nombre comercial": "Trading name",
  "A qué se dedica la empresa": "What the company does",
  "Explica vuestra actividad, experiencia y forma de trabajar.": "Describe your activity, experience and approach to work.",
  "Tu rol permite consultar este perfil, pero no editarlo.": "Your role allows you to view this profile, but not edit it.",
  "Datos de la empresa": "Company details",
  "Razón social": "Registered company name",
  "Los cambios en la identidad legal requieren una nueva revisión.": "Changes to the legal identity require a new review.",
  "Ver acreditación": "View verification documents",
  "Solicitudes de la empresa": "Company requests",
  "El cliente contrata a la empresa. La persona que lo atiende queda identificada.": "The customer contracts with the company. The person handling the request is identified.",
  "Recibida": "Received",
  "Responsable": "Person in charge",
  "Pendiente de asignar": "Awaiting assignment",
  "Todavía no hay solicitudes": "No requests yet",
  "Las solicitudes del perfil público aparecerán aquí.": "Requests from the public profile will appear here.",
  "miembros activos": "active members",
  "invitaciones pendientes": "pending invitations",
  "Tu acceso a la empresa está activo.": "Your company access is active.",
  "Cada persona accede con su cuenta y actúa según los permisos que le concedas.": "Each person signs in with their own account and acts within the permissions you grant them.",
  "Verifica la representación para ampliar el equipo": "Verify representation to expand the team",
  "Las nuevas invitaciones estarán disponibles cuando Diime apruebe la documentación.": "New invitations will be available once Diime approves the documents.",
  "Ir a verificación": "Go to verification",
  "Dirigida a": "Addressed to",
  "Abrir invitación": "Open invitation",
  "Tú": "You",
  "Gestionar permisos": "Manage permissions",
  "Cuenta principal protegida": "Owner account protected",
  "Cada enlace caduca y solo puede aceptarse una vez.": "Each link expires and can only be accepted once.",
  "Invitación cancelada. El enlace ya no permite unirse.": "Invitation cancelled. The link can no longer be used to join.",
  "Accesos personales y revocables": "Individual access that can be revoked",
  "Al revocar a un miembro pierde el acceso de empresa. Sus acciones y los trabajos realizados se conservan en el historial.": "Removing a member revokes their company access. Their actions and completed jobs remain in the history.",
  "Los permisos económicos se guardan para el diseño de roles. Esta versión local no permite realizar cobros ni cambiar cuentas bancarias.": "Financial permissions are stored as part of the role design. This local version does not process payments or change bank accounts.",
  "Actividad reciente": "Recent activity",
  "Representación de la empresa": "Company representation",
  "Acreditación del representante y autorización para gestionar la cuenta.": "Verification of the representative and authorisation to manage the account.",
  "Observación de Diime": "Diime's comment",
  "Responsable de la cuenta Diime": "Diime account owner",
  "Sin asignar": "Unassigned",
  "Representante legal acreditado": "Verified legal representative",
  "Pendiente de acreditación": "Awaiting verification",
  "Presentado el": "Submitted on",
  "Acceso restringido": "Restricted access",
  "Descargar documento para revisión": "Download document for review",
  "Actualizar acreditación": "Update verification documents",
  "Documentación de representación": "Representation documents",
  "Adjunta una autorización para la cuenta principal y la acreditación del representante en un único PDF.": "Attach authorisation for the owner account and proof of the representative's authority in one PDF.",
  "Método de acreditación": "Verification method",
  "Documento firmado con certificado de representante": "Document signed with a representative's digital certificate",
  "Revisión de identidad, poderes y autorización": "Review of identity, powers and authorisation",
  "Nombre del representante legal": "Legal representative's name",
  "Cargo o facultades de representación": "Position or powers of representation",
  "Administrador único, apoderado…": "Sole director, authorised representative…",
  "Autorización y acreditación": "Authorisation and verification",
  "PDF de hasta 5 MB. Solo visible para el proceso de revisión.": "PDF of up to 5 MB. Only accessible during the review process.",
  "Confirmo que tengo autorización para aportar esta documentación y solicitar la gestión de la empresa en Diime.": "I confirm that I am authorised to provide these documents and request management of the company on Diime.",
  "Enviar a revisión": "Submit for review",
  "Revisión de Diime": "Diime review",
  "Resolver acreditación": "Review verification request",
  "Solo el administrador de plataforma puede resolver esta solicitud. La decisión y su autor quedan registrados.": "Only a platform administrator can decide this request. The decision and its author are recorded.",
  "Solicitante": "Applicant",
  "Cargo declarado": "Declared job title",
  "En esta instalación local puedes recorrer la decisión con documentos de prueba. No se valida criptográficamente la firma ni se consulta el Registro Mercantil.": "In this local installation, you can try the decision process using test documents. Signatures are not cryptographically validated and the Commercial Registry is not consulted.",
  "Nota de revisión": "Review note",
  "Explica las comprobaciones o qué documentación falta.": "Describe the checks made or the documents still required.",
  "Solicitud aprobada. El estado de la empresa se ha actualizado.": "Request approved. The company's status has been updated.",
  "Aprobar en local": "Approve locally",
  "Información adicional solicitada. El responsable puede volver a presentar la documentación.": "Additional information requested. The account owner can resubmit the documents.",
  "Pedir información": "Request information",
  "Cómo funciona": "How it works",
  "La verificación acredita identidad y representación. La calidad del servicio se refleja en las reseñas de los clientes.": "Verification confirms identity and representation. Customer reviews reflect the quality of the service.",
  "En esta prueba local utiliza elena@empresa.example y luego cambia a la cuenta Invitada para aceptar.": "In this local test, use elena@empresa.example, then switch to the Guest account to accept.",
  "Rol en la cuenta": "Account role",
  "Administrador de la cuenta": "Account administrator",
  "Permisos individuales": "Individual permissions",
  "El rol de administrador de la cuenta no acredita la representación legal de la empresa.": "The account administrator role does not prove legal authority to represent the company.",
  "Revocar acceso a la empresa": "Revoke company access",
  "Revocar acceso": "Revoke access",
  "Perderá inmediatamente sus permisos de empresa. Se conservarán sus acciones, los trabajos y las reseñas; los encargos pendientes podrán reasignarse.": "They will immediately lose their company permissions. Their actions, jobs and reviews will be retained; pending jobs can be reassigned.",
  "Acceso revocado. El historial de la empresa se conserva.": "Access revoked. The company's history is retained.",
  "No se pudo cambiar la cuenta de prueba.": "The test account could not be switched.",
  "No se pudo cambiar la cuenta.": "The account could not be switched.",
  "Entorno local de empresas": "Local company environment",
  "Entorno local": "Local environment",
  "Datos de prueba guardados en este ordenador": "Test data stored on this computer",
  "Ver empresa": "View company",
  "Ver profesional": "View professional",
  "Ver como": "View as",
  "Cuenta de prueba": "Test account",
  "Ilustración del proyecto: {titulo}": "Project illustration: {titulo}",
  "Participación en un trabajo de la empresa": "Contribution to a company project",
  "Contactar empresa": "Contact company",
  "No se ha podido guardar la solicitud. Inténtalo de nuevo.": "The request could not be saved. Please try again.",
  "Pedir presupuesto": "Request a quote",
  "Solicitud guardada": "Request saved",
  "Cuéntanos tu proyecto": "Tell us about your project",
  "Puedes seguir explorando el perfil de la empresa.": "You can continue exploring the company profile.",
  "Tu solicitud se dirige a {empresa}": "Your request is addressed to {empresa}",
  "Volver al perfil": "Back to profile",
  "Por ejemplo, reformar un baño": "For example, renovating a bathroom",
  "Detalles del proyecto": "Project details",
  "Describe el trabajo, la zona y cuándo te gustaría realizarlo.": "Describe the job, the area and when you would like it done.",
  "Pedir presupuesto no confirma una contratación ni genera un pago.": "Requesting a quote does not confirm a booking or create a payment.",
  "Navegación del perfil": "Profile navigation",
  "Empresa verificada": "Verified company",
  "Todavía sin valoraciones": "No ratings yet",
  "Se abre en otra pestaña": "Opens in another tab",
  "Proveedor del servicio: {empresa} · Te atienden las personas autorizadas de su equipo.": "Service provider: {empresa} · Authorised team members will assist you.",
  "Miembros": "Members",
  "Sobre la empresa": "About the company",
  "Reseñas": "Reviews",
  "La empresa todavía no ha añadido su presentación.": "The company has not added an introduction yet.",
  "Trabajos realizados por {empresa}.": "Projects completed by {empresa}.",
  "Todavía no hay trabajos publicados": "No published projects yet",
  "La empresa podrá mostrar aquí sus proyectos terminados.": "The company can showcase its completed projects here.",
  "Valoraciones de servicios contratados a esta empresa.": "Reviews of services contracted with this company.",
  "{cantidad} de 5 estrellas": "{cantidad} out of 5 stars",
  "Servicio de la empresa": "Company service",
  "Todavía no hay valoraciones": "No reviews yet",
  "Las valoraciones de sus clientes aparecerán aquí.": "Customer reviews will appear here.",
  "Profesionales que actúan en nombre de la empresa.": "Professionals acting on behalf of the company.",
  "El equipo todavía no es público": "The team is not public yet",
  "Puedes solicitar un presupuesto directamente a la empresa.": "You can request a quote directly from the company.",
  "Qué significa «Empresa verificada»": "What ‘Verified company’ means",
  "En este entorno local la verificación es una simulación. No acredita a una empresa real.": "Verification in this local environment is simulated. It does not verify a real company.",
  "Volver a {empresa}": "Back to {empresa}",
  "El presupuesto y la contratación corresponden a {empresa}.": "The quote and contract are with {empresa}.",
  "Esta persona ya no tiene acceso para actuar en nombre de la empresa. Su participación en los trabajos anteriores se conserva.": "This person no longer has access to act on behalf of the company. Their contributions to previous jobs are retained.",
  "Todavía no se han publicado especialidades.": "No specialities have been published yet.",
  "Participación en trabajos contratados a {empresa}.": "Contributions to jobs contracted with {empresa}.",
  "Todavía no hay participaciones publicadas.": "No contributions have been published yet.",
  "Las valoraciones de estos trabajos pertenecen a la empresa y se consultan en su perfil.": "Reviews of these jobs belong to the company and can be viewed on its profile.",
  "Crear mi empresa": "Create my company",
  "Tu perfil quedará vinculado como titular. Después podrás invitar a otros profesionales desde Mi empresa.": "Your profile will be linked as the account owner. You can then invite other professionals from My company.",
  "Si has recibido una invitación, abre su enlace desde la cuenta a la que está dirigida.": "If you received an invitation, open its link while signed in to the account it is addressed to.",
  "Gestionado por {nombre}": "Managed by {nombre}",
  "Puedes cambiar de cuenta desde la barra del entorno local.": "You can switch accounts from the local environment toolbar.",
  "Actuar como": "Act as",
  "Mi perfil personal": "My personal profile",
  "La operación quedará a nombre de la empresa y se registrará que la has realizado tú.": "The action will be carried out in the company's name and recorded as performed by you.",
  "Empresa no encontrada | Diime": "Company not found | Diime",
  "Tu espacio de empresa": "Your company workspace",
  "Cargo actualizado.": "Job title updated.",
  "Invitar a una persona": "Invite a person",
  "La invitación está vinculada a su correo. Podrá aceptarla desde su propia cuenta.": "The invitation is linked to their email address. They can accept it from their own account.",
  "El cargo se mostrará en el equipo del perfil público de la empresa.": "The job title will appear in the team section of the company's public profile.",
  "Crear invitación": "Create invitation",
  "Creó la empresa": "Created the company",
  "Oferta creado": "Created an offer",
  "Oferta actualizado": "Updated an offer",
  "Solicitud creado": "Created a request",
  "Solicitud actualizado": "Updated a request",
  "Contrato creado": "Created a contract",
  "Contrato actualizado": "Updated a contract",
  "Actualizó el perfil de la empresa": "Updated the company profile",
  "Creó una invitación": "Created an invitation",
  "Canceló una invitación": "Cancelled an invitation",
  "Se unió a la empresa": "Joined the company",
  "Actualizó el cargo de un miembro": "Updated a member's job title",
  "Dio de baja a un miembro": "Removed a member",
  "Envió una puja": "Submitted a bid",
  "Actualizó una puja": "Updated a bid",
  "Publicó una solicitud": "Posted a request",
  "Aceptó una oferta": "Accepted an offer",
  "Contrató un trabajo": "Contracted a job",
  "Actualizó un trabajo": "Updated a job",
  "Ilustración del proyecto": "Project illustration",
  "Proyecto realizado": "Completed project",
  "Proyecto sin fotografías": "Project without photos",
  "No se pudo abrir el chat.": "The chat could not be opened.",
  "Responsable principal": "Account owner",
  "Editar el perfil": "Edit profile",
  "Presentación, servicios y web corporativa.": "Introduction, services and company website.",
  "Atender solicitudes": "Handle requests",
  "Consultar los proyectos asignados y atender al cliente.": "View assigned projects and assist customers.",
  "Enviar presupuestos": "Send quotes",
  "Proponer precios en nombre de la empresa.": "Propose prices on behalf of the company.",
  "Gestionar encargos": "Manage jobs",
  "Organizar y asignar los proyectos del equipo.": "Organise and assign the team's projects.",
  "Gestionar el equipo": "Manage the team",
  "Invitar y gestionar miembros dentro de su nivel de permisos.": "Invite and manage members within your permission level.",
  "Ver cobros": "View payments",
  "Consultar los movimientos económicos de la empresa.": "View the company's financial transactions.",
  "Gestionar cobros": "Manage payments",
  "Gestionar las operaciones de cobro. La titularidad y la cuenta bancaria corresponden al responsable principal.": "Manage payment operations. Ownership and bank account settings belong to the account owner.",
  "La cuenta de cobros no corresponde al titular de esta contratación.": "The payment account does not belong to the owner of this contract.",
  "La empresa debe configurar una cuenta de cobros a su nombre antes de recibir este pago.": "The company must set up a payment account in its own name before receiving this payment.",
  "La cuenta de cobros no corresponde al profesional independiente de esta contratación.": "The payment account does not belong to the independent professional in this contract.",
  "La contratación no tiene un titular de cobros de empresa identificado.": "This contract has no identified company payment account owner.",
  "El titular del servicio aún no ha configurado su cuenta de cobros. No se realizará ningún cargo.": "The service provider has not yet set up their payment account. No charge will be made.",
  "La cuenta de cobros del titular del servicio aún no está habilitada. No se realizará ningún cargo.": "The service provider's payment account is not yet enabled. No charge will be made.",
  "Ya no puedes realizar pagos en nombre de esta empresa.": "You can no longer make payments on behalf of this company.",
  "La liquidación no tiene el destinatario de empresa fijado.": "The settlement has no fixed company recipient.",
  "El titular de cobros de la sesión no coincide con el contrato.": "The session's payment account owner does not match the contract.",
  "El profesional ya no pertenece al equipo activo de la empresa": "The professional is no longer an active member of the company's team",
  "La empresa seleccionada no es válida.": "The selected company is not valid.",
  "Ya no tienes acceso para actuar en nombre de esta empresa.": "You no longer have access to act on behalf of this company.",
  "No se pudo comprobar la identidad de las empresas.": "The companies' identities could not be verified.",
  "Aprobar verificación": "Approve verification",
  "Buscar operaciones": "Search operations",
  "Cambiar responsable": "Change person in charge",
  "Crear la cuenta no acredita la representación legal. El perfil se publicará cuando Diime complete la revisión.": "Creating the account does not verify legal authority. The profile will be published once Diime completes its review.",
  "Enlace al logotipo": "Logo URL",
  "Gestionar miembro": "Manage member",
  "Gestionarás la cuenta como responsable principal. Después podrás completar el perfil, acreditar la representación e invitar al equipo.": "You will manage the account as its owner. You can then complete the profile, provide evidence of representation and invite your team.",
  "Identidad de la empresa y representación comprobadas.": "Company identity and representation reviewed.",
  "La cuenta principal y la representación legal se acreditan por separado.": "Account ownership and legal representation are verified separately.",
  "La nueva persona continuará la gestión. El contrato, el proveedor y el destino de cobro se conservan.": "The new person will continue managing the job. The contract, service provider and payment destination stay the same.",
  "Las acciones conservan la identidad de la persona que las realizó, aunque deje el equipo.": "Actions retain the identity of the person who performed them, even after they leave the team.",
  "Las operaciones de la empresa aparecerán aquí con la persona que las realiza.": "Company operations will appear here with the person carrying them out.",
  "Mostrar en el equipo público": "Show on the public team",
  "No hace falta tener un perfil profesional público para gestionar la empresa.": "A public professional profile is not required to manage the company.",
  "No hay actividad para estos filtros.": "No activity matches these filters.",
  "No hay operaciones para estos filtros": "No operations match these filters",
  "No se ha enviado ningún correo. El enlace es personal, de un solo uso y caduca en 7 días.": "No email has been sent. The link is personal, can be used once and expires in 7 days.",
  "Operaciones de la empresa": "Company operations",
  "Operaciones": "Operations",
  "Perfil de la empresa": "Company profile",
  "Persona que actuó": "Person who acted",
  "Persona que actuó o responsable": "Person who acted or person in charge",
  "Personas que la empresa presenta en su equipo público.": "People the company displays on its public team.",
  "Responsable actual": "Current person in charge",
  "Se han revisado los datos de la empresa y la autorización de la persona responsable de su cuenta en Diime. Este distintivo no certifica la calidad del servicio: consulta sus trabajos y las reseñas de sus clientes.": "The company details and the authorization of its Diime account owner have been reviewed. This badge does not certify service quality: check the company’s work and customer reviews.",
  "Se mostrarán su nombre, cargo y presentación. Su correo y sus permisos seguirán siendo privados.": "Their name, job title and introduction will be shown. Their email address and permissions will remain private.",
  "Seleccionar persona": "Select a person",
  "Separa los servicios con comas.": "Separate services with commas.",
  "Sin cargo indicado": "No job title specified",
  "Solo pueden asignarse miembros activos con permiso para gestionar encargos.": "Only active members with permission to manage jobs can be assigned.",
  "Tipo de actividad": "Activity type",
  "Todas las actividades": "All activities",
  "Todo el equipo": "All team members",
  "Tu DNI/NIE como responsable de la cuenta": "Your DNI/NIE as account owner",
  "Tu acceso permite consultar el perfil. Para editarlo necesitas permiso.": "Your access lets you view the profile. Editing requires permission.",
  "Título, descripción o persona": "Title, description or person",
  "Ver perfil profesional": "View professional profile",
  "Verificación de la empresa": "Company verification",
  "Consulta las solicitudes, ofertas y trabajos de todo el equipo.": "View requests, offers and jobs from the entire team.",
  "Aquí aparecen las operaciones que puedes consultar con tus permisos.": "These are the operations you can view with your permissions.",
  "La empresa contrata": "The company is hiring",
  "La empresa presta el servicio": "The company is providing the service",
  "Responsable actualizado. La empresa conserva el contrato y su historial.": "Person in charge updated. The company retains the contract and its history.",
  "Visible en el equipo público": "Visible on the public team",
  "Solo visible dentro de la empresa": "Visible only within the company",
  "Miembro actualizado.": "Member updated.",
  "Perfil actualizado.": "Profile updated.",
  "Invitación cancelada.": "Invitation cancelled.",
  "Actualizó los permisos de un miembro": "Updated a member’s permissions",
  "Actualizó una solicitud": "Updated a request",
  "Cambió el responsable de un trabajo": "Changed the person in charge of a job",
  "Envió la documentación de representación": "Submitted representation documents",
  "Revisó la acreditación": "Reviewed the verification",
  "Documentación enviada. Diime revisará la representación antes de publicar la empresa.": "Documents submitted. Diime will review the representation before publishing the company.",
  "No se pudo enviar la documentación. Vuelve a intentarlo.": "Documents could not be submitted. Please try again.",
  "Revisión guardada.": "Review saved.",
  "No se pudo descargar el documento.": "The document could not be downloaded.",
  "Diime ha revisado la identidad de la empresa y su representación. El perfil puede mostrarse al público.": "Diime has reviewed the company’s identity and representation. Its profile can be shown publicly.",
  "Tu documentación está en revisión. Puedes seguir preparando el perfil y el equipo.": "Your documents are under review. You can continue preparing the profile and team.",
  "Completa la acreditación para publicar el perfil y operar en nombre de la empresa.": "Complete verification to publish the profile and act on behalf of the company.",
  "Representante legal declarado": "Declared legal representative",
  "Al aceptar, tu nombre y cargo aparecerán en el equipo público de la empresa.": "When you accept, your name and job title will appear on the company’s public team.",
  "Tu participación será visible solo dentro de la empresa.": "Your membership will be visible only within the company.",
  "Abierta": "Open",
  "Publicada": "Published",
  "Cerrada": "Closed",
  "Caducada": "Expired",
  "Administrador de plataforma": "Platform administrator",
  "Importe acordado": "Agreed amount",
  "Cancelación": "Cancellation",
  "Actualizar trabajo": "Update job",
  "Al entregar el trabajo, el cliente podrá revisarlo y confirmar su finalización.": "Once you deliver the job, the customer can review it and confirm completion.",
  "Guardar progreso": "Save progress",
  "Entregar trabajo": "Deliver job",
  "Trabajo entregado. Queda pendiente la confirmación del cliente.": "Job delivered. Customer confirmation is pending.",
  "Progreso actualizado.": "Progress updated.",
  "Verificación de empresas": "Company verification",
  "Revisa la identidad de la empresa y las facultades de su representante antes de publicar el perfil.": "Review the company’s identity and its representative’s authority before publishing the profile.",
  "No hay solicitudes de verificación de empresas.": "There are no company verification requests.",
  "NIF": "Tax identification number",
  "Descargar documento": "Download document",
  "Resultado de la revisión": "Review outcome",
  "Indica qué se ha comprobado o qué información falta.": "State what has been checked or which information is missing.",
  "He comprobado la identidad de la empresa y la representación de esta persona. Esta revisión no acredita licencias ni especialidades profesionales.": "I have checked the company’s identity and this person’s authority to represent it. This review does not verify professional licences or specialisms.",
  "Verificar y publicar empresa": "Verify and publish company",
  "Solicitar información": "Request information",
  "Confirmar entrega": "Confirm delivery",
  "Ver conversación": "View conversation",
  "Requiere perfil profesional para enviar ofertas.": "A professional profile is required to submit offers.",
  "Explica por qué quieres cancelar el servicio. La otra parte deberá aceptar o rechazar la solicitud.": "Explain why you want to cancel the service. The other party must accept or reject the request.",
  "Explica qué no cumple lo acordado. Se abrirá una disputa y el pago quedará retenido mientras Diime la revisa.": "Explain what does not match the agreement. A dispute will be opened and the payment will remain held while Diime reviews it.",
  "El trabajo quedará cancelado. Si hubo un pago, se tramitará el reembolso y se conservarán los gastos de servicio que correspondan según las condiciones del contrato.": "The job will be cancelled. If a payment was made, a refund will be processed and applicable service fees will be retained under the contract terms.",
  "Explica por qué te opones. Se abrirá una disputa para que Diime revise los argumentos de ambas partes.": "Explain why you object. A dispute will be opened so Diime can review both parties’ arguments.",
  "Cancelación solicitada. La otra parte podrá responder.": "Cancellation requested. The other party can respond.",
  "Cancelación aceptada. El estado del trabajo se ha actualizado.": "Cancellation accepted. The job status has been updated.",
  "Disputa abierta. Diime revisará los argumentos y el pago permanecerá retenido.": "Dispute opened. Diime will review the arguments and the payment will remain held.",
  "Aceptar la cancelación requiere permiso para gestionar cobros.": "Accepting cancellation requires permission to manage payments.",
  "La empresa solicitó la cancelación. Está pendiente la respuesta de la otra parte.": "The company requested cancellation. The other party’s response is pending.",
  "La parte solicitante requiere revisión antes de responder a esta cancelación.": "The requesting party needs to be reviewed before this cancellation can be answered.",
  "Cancelación pendiente": "Cancellation pending",
  "Rechazar cancelación": "Reject cancellation",
  "Resolución": "Resolution",
  "Seleccionar provincias": "Select provinces",
  "Seleccionar servicios": "Select services",
  "Zona guardada anteriormente": "Previously saved area",
  "Logotipo de la empresa": "Company logo",
  "Vista previa del logotipo": "Logo preview",
  "Cambiar logotipo": "Change logo",
  "Subir logotipo": "Upload logo",
  "Quitar logotipo": "Remove logo",
  "PNG, JPG o WebP de hasta 3 MB. Se subirá al guardar los cambios.": "PNG, JPG or WebP up to 3 MB. It will be uploaded when you save your changes.",
  "Guardando cambios…": "Saving changes…",
  "Elige una imagen PNG, JPG o WebP.": "Choose a PNG, JPG or WebP image.",
  "El logotipo debe ocupar como máximo 3 MB.": "The logo must be no larger than 3 MB.",
  "No se pudo subir el logotipo. Vuelve a intentarlo.": "The logo could not be uploaded. Please try again.",
  "Selecciona al menos una provincia y un servicio.": "Select at least one province and one service.",
  "Debes iniciar sesión para subir el logo.": "You must sign in to upload the logo.",
  "No se pudo comprobar el acceso a tu empresa. Vuelve a intentarlo.": "Access to your company could not be checked. Please try again.",
  "No tienes permiso para cambiar el logo de esta empresa.": "You do not have permission to change this company’s logo.",
  "El logo no puede superar los 3 MB.": "The logo must not exceed 3 MB.",
  "Adjunta una imagen para el logo.": "Attach an image for the logo.",
  "No se pudo leer el archivo del logo.": "The logo file could not be read.",
  "La empresa activa ha cambiado. Recarga la página antes de guardar.": "The active company has changed. Reload the page before saving.",
  "El logo debe ser una imagen PNG, JPEG o WebP.": "The logo must be a PNG, JPEG or WebP image.",
  "El archivo no coincide con una imagen PNG, JPEG o WebP válida.": "The file does not match a valid PNG, JPEG or WebP image.",
  "No se pudo finalizar la subida del logo. Vuelve a intentarlo.": "The logo upload could not be completed. Please try again.",
  "No se pudo subir el logo. Vuelve a intentarlo.": "The logo could not be uploaded. Please try again.",
}
