// Canonical system notification templates. Captured user text stays unchanged.
export const EN_NOTIFICACIONES: Record<string, string> = {
  "El cliente ha rechazado tu entrega": "The client has rejected your delivery",
  "El cliente considera que \"{0}\" no cumple lo acordado. La transferencia sigue bloqueada y el equipo de Diime decidirá según las pruebas y los términos. Motivo: {1}": "The client considers that \"{0}\" does not meet the agreed requirements. The transfer remains blocked and the Diime team will decide based on the evidence and terms. Reason: {1}",
  "El cliente ha rechazado la entrega. El equipo de Diime decidirá según las pruebas y los términos acordados. Motivo: {0}": "The client has rejected the delivery. The Diime team will decide based on the evidence and agreed terms. Reason: {0}",
  "Disputa retirada": "Dispute withdrawn",
  "Se ha retirado la disputa sobre \"{0}\". El trabajo continúa con normalidad.": "The dispute about \"{0}\" has been withdrawn. Work continues as normal.",
  "Se ha retirado la disputa sobre \"{0}\"; ya no requiere revisión.": "The dispute about \"{0}\" has been withdrawn; it no longer requires review.",
  "Incidencia resuelta": "Support issue resolved",
  "Incidencia cerrada": "Support issue closed",
  "Tu incidencia \"{0}\" se ha marcado como resuelta.": "Your support issue \"{0}\" has been marked as resolved.",
  "Tu incidencia \"{0}\" se ha marcado como cerrada.": "Your support issue \"{0}\" has been marked as closed.",
  "Tu incidencia \"{0}\" se ha marcado como resuelta. Respuesta del equipo: {1}": "Your support issue \"{0}\" has been marked as resolved. Team response: {1}",
  "Tu incidencia \"{0}\" se ha marcado como cerrada. Respuesta del equipo: {1}": "Your support issue \"{0}\" has been marked as closed. Team response: {1}",
  "Nueva oferta en tu demanda": "New offer for your request",
  "Has recibido una oferta en \"{0}\".": "You have received an offer for \"{0}\".",
  "Una oferta ha sido actualizada": "An offer has been updated",
  "El profesional ha modificado su oferta en \"{0}\". Revísala en Mis Solicitudes.": "The professional has updated their offer for \"{0}\". Review it in My Requests.",
  "El profesional ha modificado su oferta en \"{0}\" (nuevo precio: {1}€). Revísala en Mis Solicitudes.": "The professional has updated their offer for \"{0}\" (new price: €{1}). Review it in My Requests.",
  "Un profesional ha retirado su oferta": "A professional has withdrawn their offer",
  "Una de las ofertas que habías recibido en \"{0}\" ya no está disponible.": "One of the offers you received for \"{0}\" is no longer available.",
  "Han aceptado tu puja": "Your bid has been accepted",
  "Tu oferta para \"{0}\" ha sido aceptada. Cuando el cliente complete el pago protegido, el trabajo aparecerá en Gestión de Proyectos.": "Your offer for \"{0}\" has been accepted. Once the client completes the protected payment, the job will appear in Project Management.",
  "Han rechazado tu oferta": "Your offer has been rejected",
  "Tu oferta para \"{0}\" ha sido rechazada.": "Your offer for \"{0}\" has been rejected.",
  "Notificaciones de Diime activadas": "Diime notifications enabled",
  "Esta es una prueba. Los mensajes mostrarán aquí el remitente y una vista previa.": "This is a test. Messages will show the sender and a preview here.",
  "Han cambiado una demanda en la que pujaste": "A request you bid on has changed",
  "El cliente ha modificado \"{0}\". Revisa tu oferta por si ya no encaja con las nuevas condiciones.": "The client has updated \"{0}\". Review your offer in case it no longer matches the new requirements.",
  "Han retirado una demanda en la que pujaste": "A request you bid on has been withdrawn",
  "El cliente ha borrado \"{0}\", así que tu oferta ya no sigue adelante. Puedes seguir pujando en otras demandas.": "The client has deleted \"{0}\", so your offer will not proceed. You can continue bidding on other requests.",
  "Solicitud de cancelación": "Cancellation request",
  "La otra parte quiere cancelar \"{0}\". Acepta o rechaza la cancelación en Mis solicitudes.": "The other party wants to cancel \"{0}\". Accept or reject the cancellation in My Requests.",
  "La otra parte quiere cancelar \"{0}\". Acepta o rechaza la cancelación en Mis trabajos.": "The other party wants to cancel \"{0}\". Accept or reject the cancellation in My Jobs.",
  "Solicitud de cancelación actualizada": "Cancellation request updated",
  "La otra parte ha actualizado sus argumentos o archivos para cancelar \"{0}\".": "The other party has updated their reasons or files for cancelling \"{0}\".",
  "Solicitud de cancelación retirada": "Cancellation request withdrawn",
  "La otra parte ha retirado la solicitud de cancelación de \"{0}\". El servicio continúa.": "The other party has withdrawn the cancellation request for \"{0}\". The service continues.",
  "Cancelación aceptada": "Cancellation accepted",
  "Cancelación rechazada: disputa abierta": "Cancellation rejected: dispute opened",
  "La otra parte ha aceptado cancelar \"{0}\". El trabajo queda cancelado.": "The other party has agreed to cancel \"{0}\". The job is now cancelled.",
  "La otra parte ha rechazado cancelar \"{0}\". Se ha abierto una disputa que resolverá el equipo de Diime según los términos de la contratación (en caso de duda, a favor del cliente).": "The other party has refused to cancel \"{0}\". A dispute has been opened, which the Diime team will resolve under the contract terms (in the client's favour in case of doubt).",
  "Progreso actualizado: {0}%": "Progress updated: {0}%",
  "El profesional ha actualizado el progreso de \"{0}\".": "The professional has updated the progress of \"{0}\".",
  "Entrega: {0}": "Delivery: {0}",
  "{0} te ha entregado \"{1}\". Revísalo y confirma la finalización para liberar el pago.": "{0} has delivered \"{1}\". Review it and confirm completion to release the payment.",
  "El trabajo ha sido entregado y está pendiente de confirmación del cliente.": "The work has been delivered and is awaiting the client's confirmation.",
  "Tu puja no ha sido seleccionada": "Your bid was not selected",
  "El cliente ha contratado a otro profesional para \"{0}\". Gracias por participar: puedes seguir pujando en otras demandas.": "The client has hired another professional for \"{0}\". Thank you for taking part: you can continue bidding on other requests.",
  "Contracargo bancario en Stripe": "Bank chargeback in Stripe",
  "El pago del trabajo {0} tiene un contracargo. Revísalo inmediatamente en Stripe y en Diime.": "The payment for job {0} has a chargeback. Review it immediately in Stripe and Diime.",
  "Tu perfil profesional ha sido verificado": "Your professional profile has been verified",
  "Se ha retirado la verificación de tu perfil": "Your profile verification has been withdrawn",
  "El equipo de Diime ha verificado tu perfil profesional. La insignia ya aparece en tu perfil.": "The Diime team has verified your professional profile. The badge now appears on your profile.",
  "El equipo de Diime ha retirado la insignia de verificación de tu perfil profesional.": "The Diime team has removed the verification badge from your professional profile.",
  "El equipo de Diime está revisando tu perfil": "The Diime team is reviewing your profile",
  "Tu solicitud de verificación necesita una corrección": "Your verification request requires a correction",
  "Consulta el estado de tu verificación en Mi perfil. El equipo de Diime puede contactar contigo para completar la revisión.": "Check your verification status in My Profile. The Diime team may contact you to complete the review.",
  "Se ha abierto una disputa": "A dispute has been opened",
  "El trabajo está en disputa. La transferencia queda bloqueada mientras Diime revisa las pruebas.": "The job is in dispute. The transfer remains blocked while Diime reviews the evidence.",
  "Se ha abierto una mediación sobre la cancelación. No se ha realizado ningún pago.": "Mediation has been opened regarding the cancellation. No payment has been made.",
  "Nueva demanda en tu área": "New request in your area",
  "Se ha publicado \"{0}\" ({1}) en {2}. Presupuesto: {3}. Échale un vistazo y envía tu oferta.": "\"{0}\" ({1}) has been posted in {2}. Budget: {3}. Take a look and submit your offer.",
  "Se ha publicado \"{0}\" ({1}). Presupuesto: {2}. Échale un vistazo y envía tu oferta.": "\"{0}\" ({1}) has been posted. Budget: {2}. Take a look and submit your offer.",
  "El cliente ha pagado: puedes empezar": "The client has paid: you can start",
  "El pago de \"{0}\" está confirmado. La transferencia queda pendiente de confirmación o resolución.": "Payment for \"{0}\" is confirmed. The transfer awaits confirmation or dispute resolution.",
  "Nueva disputa para revisar": "New dispute to review",
  "Revisa la disputa de \"{0}\".": "Review the dispute about \"{0}\".",
  "Pago liberado": "Payment released",
  "El cliente confirmó la entrega. Se te ha transferido {0} EUR netos.": "The client confirmed delivery. A net amount of EUR {0} has been transferred to you.",
  "Cancelación reembolsada": "Cancellation refunded",
  "Se ha cancelado el servicio de mutuo acuerdo y se han devuelto íntegramente {0} EUR.": "The service has been cancelled by mutual agreement and EUR {0} has been refunded in full.",
  "Se ha cancelado el servicio de mutuo acuerdo. Se han reembolsado {0} EUR. Diime conserva {1} EUR de comisión del cliente.": "The service has been cancelled by mutual agreement. EUR {0} has been refunded. Diime retains EUR {1} in client service fees.",
  "Disputa resuelta": "Dispute resolved",
  "La mediación de Diime ha concluido. Reembolso al cliente: {0} EUR. Motivo: {1}. La decisión es privada y no impide emprender otras acciones.": "Diime's mediation has concluded. Refund to the client: EUR {0}. Reason: {1}. The decision is private and does not prevent further action.",
  "La mediación de Diime ha concluido. Transferencia neta al proveedor: {0} EUR. Motivo: {1}. La decisión es privada y no impide emprender otras acciones.": "Diime's mediation has concluded. Net transfer to the provider: EUR {0}. Reason: {1}. The decision is private and does not prevent further action.",
  "Pago tardío reembolsado": "Late payment refunded",
  "El pago llegó tras el cierre de su intento y se ha devuelto íntegramente. El servicio no se ha reactivado.": "The payment arrived after its payment attempt had closed and has been refunded in full. The service has not been reactivated.",
  "Mediación resuelta sin pago": "Mediation resolved without payment",
  "La mediación cancela la contratación y la demanda vuelve a estar abierta. No se ha movido dinero. Motivo: {0}": "Mediation cancels the contract and the request is open again. No money has been moved. Reason: {0}",
  "La mediación mantiene la contratación: queda pendiente de pago y el servicio no debe empezar hasta que se pague. Motivo: {0}": "Mediation upholds the contract: payment remains pending and the service must not begin until payment is made. Reason: {0}",
  "Entrega fuera de plazo": "Delivery overdue",
  "La fecha de entrega prevista de \"{0}\" ({1}) ya ha pasado y el trabajo sigue en curso. Habla con el profesional; si no hay avances, puedes abrir una incidencia.": "The expected delivery date for \"{0}\" ({1}) has passed and work is still in progress. Speak to the professional; if there is no progress, you can report an issue.",
  "La fecha de entrega prevista de \"{0}\" ({1}) ya ha pasado. Actualiza el progreso o entrega el trabajo para que el cliente sepa cómo va.": "The expected delivery date for \"{0}\" ({1}) has passed. Update the progress or deliver the work so the client knows its status.",
  "Ver la demanda": "View request",
  "Revisar mi puja": "Review my bid",
  "Ver mis pujas": "View my bids",
  "Ver la oferta": "View offer",
  "Ver el proyecto": "View project",
  "Ver las ofertas": "View offers",
  "Ver el progreso": "View progress",
  "Revisar la entrega": "Review delivery",
  "Ver el pago": "View payment",
  "Ver el reembolso": "View refund",
  "Ver la solicitud": "View request",
  "Revisar la cancelación": "Review cancellation",
  "Ver la disputa": "View dispute",
  "Ver la resolución": "View resolution",
  "Ver la incidencia": "View support issue",
  "Ver mi perfil": "View my profile",
  "Ver la verificación": "View verification",
  "Hola, {0}.": "Hello, {0}.",
  "Hola.": "Hello.",
  "Entra en Diime para verlo con detalle.": "Sign in to Diime to view the details.",
  "Tienes una novedad en Diime.": "You have an update on Diime.",
  "Recibes este correo porque tienes una cuenta en Diime.": "You are receiving this email because you have a Diime account.",
  "Puedes elegir qué avisos recibes o desactivarlos desde": "You can choose which alerts you receive or turn them off in",
  "Mi cuenta": "My account",
  "Recibes este correo porque tienes una cuenta en Diime. Puedes elegir qué avisos recibes en {0}": "You are receiving this email because you have a Diime account. You can choose which alerts you receive at {0}",
  "¡Pago liberado!": "Payment released!",
  "Has cobrado un trabajo": "You have been paid for a job",
  "Ver mis cobros": "View my payouts",
  "¡Cobro protegido, a por ello!": "Payment protected — ready to go!",
  "El cliente ha pagado: ya puedes empezar": "The client has paid: you can start now",
  "Ver el trabajo": "View job",
  "¡Trabajo entregado!": "Work delivered!",
  "Tienes una entrega lista": "A delivery is ready for you",
  "Disputa resuelta a tu favor": "Dispute resolved in your favour",
  "El equipo de Diime te ha dado la razón": "The Diime team has ruled in your favour",
  "Disputa resuelta en tu contra": "Dispute resolved against you",
  "El equipo de Diime ha resuelto la disputa": "The Diime team has resolved the dispute",
  "Nuevo aviso": "New alert",
  "La otra parte quiere cancelar \"{0}\". Acepta o rechaza la cancelación en Mis Solicitudes (pestaña Abiertas).": "The other party wants to cancel \"{0}\". Accept or reject the cancellation in My Requests (Open tab).",
  "La otra parte quiere cancelar \"{0}\". Acepta o rechaza la cancelación en Mis Solicitudes (pestaña En Progreso).": "The other party wants to cancel \"{0}\". Accept or reject the cancellation in My Requests (In Progress tab).",
  "La otra parte quiere cancelar \"{0}\". Acepta o rechaza la cancelación en Mis Pujas.": "The other party wants to cancel \"{0}\". Accept or reject the cancellation in My Bids.",
  "La otra parte quiere cancelar \"{0}\". Acepta o rechaza la cancelación en Gestión de proyectos (pestaña Activos).": "The other party wants to cancel \"{0}\". Accept or reject the cancellation in Project Management (Active tab)."
}
