// Reviewed English translations for public pages, legal documents and administration.
export const EN_PAGES: Record<string, string> = {
  "Dashboard": "Dashboard",
  "Operaciones": "Operations",
  "Usuarios": "Users",
  "Verificaciones": "Verifications",
  "Trabajos y justificantes": "Jobs and receipts",
  "Disputas": "Disputes",
  "Incidencias": "Issues",
  "Soporte": "Support",
  "Pagos": "Payments",
  "Admin": "Admin",
  "Diime Admin": "Diime Admin",
  "Administración": "Administration",
  "Stripe": "Stripe",
  "Abrir saldo y movimientos de Diime en una pestaña nueva": "Open Diime's balance and transactions in a new tab",
  "Administrador": "Administrator",
  "Cerrar sesión": "Sign out",
  "Trabajo": "Job",
  "Total Usuarios": "Total users",
  "Profesionales": "Professionals",
  "Trabajos Activos": "Active jobs",
  "Disputas Abiertas": "Open disputes",
  "abiertas o en revisión": "open or under review",
  "Pagos en Escrow": "Payments held",
  "Bienvenido al panel de administración de Diime": "Welcome to the Diime administration dashboard",
  "Ingresos de Diime": "Diime revenue",
  "Comisiones cobradas por la plataforma": "Fees collected by the platform",
  "Gastos de servicio a clientes (10%)": "Client service fees (10%)",
  "Gastos de servicio a profesionales (tarifa actual": "Professional service fees (current rate",
  "Retenciones en reembolsos": "Amounts retained on refunds",
  "Últimos cobros": "Recent fees collected",
  "Comisión ingresada al liberar cada pago": "Fee received when each payment is released",
  "Todavía no se ha liberado ningún pago.": "No payments have been released yet.",
  "Sin fecha": "No date",
  "Acciones Rápidas": "Quick actions",
  "Ver Usuarios": "View users",
  "Gestionar usuarios registrados": "Manage registered users",
  "Consultar todas las contrataciones": "View all engagements",
  "Resolver Disputas": "Resolve disputes",
  "Mediar conflictos entre usuarios": "Mediate conflicts between users",
  "Gestionar Incidencias": "Manage issues",
  "Reportes de fraude, abuso y soporte": "Reports of fraud, abuse and support issues",
  "Ver Pagos": "View payments",
  "Monitorizar transacciones": "Monitor transactions",
  "Pendiente de pago": "Awaiting payment",
  "En progreso": "In progress",
  "Entregado": "Delivered",
  "Completado": "Completed",
  "Rechazado": "Rejected",
  "En disputa": "In dispute",
  "Error": "Error",
  "Faltan datos": "Missing information",
  "Elige una resolución y escribe la justificación.": "Choose a resolution and provide your reasons.",
  "Reparto no válido": "Invalid allocation",
  "El reembolso parcial debe ser mayor que 0 y menor que el precio del servicio.": "The partial refund must be greater than 0 and less than the service price.",
  "Esta decisión ejecutará el reembolso y/o la transferencia real en Stripe y no podrá modificarse después. ¿Continuar?": "This decision will execute a real refund and/or transfer in Stripe and cannot be changed afterwards. Continue?",
  "Esta mediación cambiará el estado de la contratación. No hay un pago que repartir. ¿Continuar?": "This mediation will change the engagement status. There is no payment to allocate. Continue?",
  "Disputa resuelta": "Dispute resolved",
  "Se ha aplicado la resolución y el movimiento de fondos.": "The resolution and movement of funds have been applied.",
  "Se ha aplicado la mediación sin mover dinero.": "The mediation has been applied without moving any money.",
  "Cliente": "Client",
  "Proveedor": "Provider",
  "Volver a disputas": "Back to disputes",
  "Disputa iniciada por el": "Dispute opened by the",
  "Abierta": "Open",
  "Resuelta": "Resolved",
  "Pago protegido": "Protected payment",
  "Estado del pago:": "Payment status:",
  "Justificante y servicio contratado": "Receipt and contracted service",
  "Consulta la propuesta aceptada, los conceptos, los importes y los términos del encargo.": "Review the accepted proposal, line items, amounts and terms of the engagement.",
  "Ver justificante": "View receipt",
  "Motivo de la disputa": "Reason for the dispute",
  "Argumentos y pruebas de la cancelación": "Cancellation arguments and evidence",
  "Solicita cancelar ·": "Requests cancellation ·",
  "Motivo": "Reason",
  "No indicó un motivo.": "No reason provided.",
  "Archivos aportados (": "Files provided (",
  "No adjuntó archivos.": "No files attached.",
  "Rechaza cancelar ·": "Declines cancellation ·",
  "Argumentos": "Arguments",
  "No indicó argumentos.": "No arguments provided.",
  "Conversación cliente ↔ proveedor": "Client ↔ provider conversation",
  "No hay mensajes registrados.": "No messages recorded.",
  "Historial del trabajo": "Job history",
  "Sin actualizaciones registradas.": "No updates recorded.",
  "Otras pruebas del servicio": "Other evidence of the service",
  "Pruebas y archivos adjuntos": "Evidence and attachments",
  "No se han adjuntado archivos.": "No files have been attached.",
  "Gestionar contracargo bancario": "Manage bank chargeback",
  "Conciliar el pago de este expediente": "Reconcile the payment for this case",
  "La entidad bancaria está disputando este cargo. Revisa su plazo y presenta las pruebas en Stripe. Antes de emitir otros movimientos, concilia el resultado bancario y las transferencias ya realizadas.": "The bank is disputing this charge. Check the deadline and submit evidence in Stripe. Before making any further movements of funds, reconcile the bank's decision with transfers already made.",
  "El expediente no tiene un pago identificado con seguridad. Revisa el cargo en Stripe y vincúlalo al expediente antes de resolver; los intentos abandonados no son dinero retenido.": "No payment has been reliably identified for this case. Check the charge in Stripe and link it to the case before resolving it; abandoned payment attempts are not held funds.",
  "Abrir disputas en Stripe": "Open disputes in Stripe",
  "Resolver mediación sin pago": "Resolve mediation without payment",
  "Resolver disputa": "Resolve dispute",
  "Cancelar la contratación": "Cancel the engagement",
  "La demanda vuelve a estar abierta; no hay reembolso": "The request reopens; there is no refund",
  "Mantener la contratación": "Keep the engagement",
  "El cliente debe pagar antes de iniciar el servicio": "The client must pay before the service begins",
  "Reembolsar al cliente": "Refund the client",
  "Liberar al proveedor": "Release to the provider",
  "Transferir su neto en Stripe": "Transfer their net amount in Stripe",
  "Reembolso parcial": "Partial refund",
  "Repartir el importe": "Split the amount",
  "Importe a reembolsar al cliente (€)": "Amount to refund to the client (€)",
  "El resto (": "The remainder (",
  "€ brutos) se adjudica al proveedor. Su comisión se prorratea según ese importe.": "€ gross) is allocated to the provider. Their fee is prorated on that amount.",
  "Vista previa cerrada del reparto": "Final allocation preview",
  "Reembolso al cliente": "Client refund",
  "Bruto adjudicado al proveedor": "Gross amount allocated to the provider",
  "Comisión cliente (se conserva íntegra)": "Client fee (retained in full)",
  "Comisión proveedor prorrateada": "Prorated provider fee",
  "Transferencia neta al proveedor": "Net transfer to the provider",
  "Comisiones brutas de Diime": "Diime's gross fees",
  "Stripe descuenta sus propios costes a Diime. El admin no puede asignar a Diime ninguna parte adicional del servicio.": "Stripe deducts its own costs from Diime. The admin cannot allocate any additional share of the service price to Diime.",
  "Justificación de la resolución *": "Reasons for the resolution *",
  "Explica la decisión basándote en la conversación y las pruebas...": "Explain the decision based on the conversation and evidence...",
  "Se ejecutarán en Stripe los movimientos mostrados arriba con protección frente a duplicados.": "The movements shown above will be executed in Stripe with protection against duplicates.",
  "Guardar decisión de mediación": "Save mediation decision",
  "Ejecutar resolución en Stripe": "Execute resolution in Stripe",
  "Resolución:": "Resolution:",
  "Contratación cancelada sin pago": "Engagement cancelled without payment",
  "Contratación mantenida; pendiente de pago": "Engagement kept; awaiting payment",
  "Pago liberado al proveedor": "Payment released to the provider",
  "Resuelta el": "Resolved on",
  "No hay disputas en esta sección.": "There are no disputes in this section.",
  "vs": "vs",
  "Revisar y resolver": "Review and resolve",
  "Ver detalle": "View details",
  "Centro de Disputas": "Dispute centre",
  "Revisa la conversación y las pruebas, y resuelve liberando o reembolsando los fondos.": "Review the conversation and evidence, then resolve the dispute by releasing or refunding the funds.",
  "Abiertas": "Open",
  "Resueltas": "Resolved",
  "Tasa resolución": "Resolution rate",
  "Cargando disputas...": "Loading disputes...",
  "Abiertas (": "Open (",
  "Resueltas (": "Resolved (",
  "Fraude": "Fraud",
  "Abuso o conducta": "Abuse or conduct",
  "Problema de pago": "Payment problem",
  "Problema técnico": "Technical problem",
  "Perfil / verificación": "Profile / verification",
  "Otro": "Other",
  "En revisión": "Under review",
  "Cerrada": "Closed",
  "Incidencia actualizada": "Issue updated",
  "Los cambios se han guardado.": "Your changes have been saved.",
  "Incidencia resuelta": "Issue resolved",
  "Se ha avisado a quien la reportó.": "The person who reported it has been notified.",
  "Centro de Incidencias": "Issue centre",
  "Gestiona reportes de fraude, abuso, problemas de pago y soporte técnico": "Manage reports of fraud, abuse, payment problems and technical support",
  "Buscar por asunto, descripción o email...": "Search by subject, description or email...",
  "Categoría": "Category",
  "Todas las categorías": "All categories",
  "En revisión (": "Under review (",
  "Todas (": "All (",
  "Incidencia": "Issue",
  "Reportada el": "Reported on",
  "Reportado por": "Reported by",
  "Usuario reportado": "Reported user",
  "Descripción": "Description",
  "Estado": "Status",
  "Prioridad": "Priority",
  "Baja": "Low",
  "Media": "Medium",
  "Alta": "High",
  "Crítica": "Critical",
  "Notas internas del admin": "Internal admin notes",
  "Acciones tomadas, comunicaciones, conclusiones...": "Actions taken, communications, conclusions...",
  "Cancelar": "Cancel",
  "Guardando...": "Saving...",
  "Guardar cambios": "Save changes",
  "Marcar como resuelta": "Mark as resolved",
  "Cargando incidencias...": "Loading issues...",
  "No hay incidencias en esta categoría": "There are no issues in this category",
  "Ver y gestionar": "View and manage",
  "Marcar resuelta": "Mark as resolved",
  "No se pudo cargar operaciones": "Could not load operations",
  "No se pudo resolver": "Could not resolve",
  "Evento resuelto": "Event resolved",
  "Volverá a abrirse automáticamente si el fallo se repite.": "It will reopen automatically if the failure happens again.",
  "Webhooks fallidos": "Failed webhooks",
  "Revisar en Stripe y reintentar el mismo evento.": "Review in Stripe and retry the same event.",
  "Webhooks atascados": "Stuck webhooks",
  "Procesando durante más de 15 minutos.": "Processing for more than 15 minutes.",
  "Liquidaciones fallidas": "Failed settlements",
  "Confirmar el movimiento en Stripe antes de reintentar.": "Confirm the movement of funds in Stripe before retrying.",
  "Liquidaciones atascadas": "Stuck settlements",
  "Disputas fuera de SLA": "Disputes past the SLA deadline",
  "Abiertas durante más de 24 horas.": "Open for more than 24 hours.",
  "Incidencias críticas": "Critical issues",
  "Requieren atención inmediata.": "Require immediate attention.",
  "Demandas sin oferta": "Requests with no offers",
  "Madrid, abiertas y sin oferta después de 4 horas.": "Madrid requests still open with no offers after 4 hours.",
  "Pagos, comunicaciones, moderación y matching del piloto de Madrid.": "Payments, communications, moderation and matching for the Madrid pilot.",
  "Actualizar": "Refresh",
  "Total accionable": "Total requiring action",
  "Alertas técnicas": "Technical alerts",
  "Operación y matching": "Operations and matching",
  "No hay elementos fuera de SLA.": "There are no items past the SLA deadline.",
  "Último control:": "Last check:",
  "Fallos registrados por la aplicación": "Failures recorded by the application",
  "Email, push y errores técnicos agregados sin datos personales completos.": "Aggregated email, push and technical errors without full personal details.",
  "Marcar resuelto": "Mark as resolved",
  "Pago retenido": "Payment held",
  "Liberado": "Released",
  "Reembolsado": "Refunded",
  "Moviendo fondos": "Moving funds",
  "Profesional": "Professional",
  "Monto": "Amount",
  "Comision": "Fee",
  "Neto Prof.": "Provider net",
  "Fecha": "Date",
  "No hay transacciones en esta categoria": "There are no transactions in this category",
  "Trabajo eliminado": "Deleted job",
  "Gestion de Pagos": "Payment management",
  "Monitoriza todas las transacciones y pagos de la plataforma": "Monitor all transactions and payments on the platform",
  "Saldo y movimientos en Stripe": "Balance and transactions in Stripe",
  "Pagos retenidos": "Payments held",
  "transacciones": "transactions",
  "Comisiones": "Fees",
  "Total ganado": "Total earned",
  "reembolsos": "refunds",
  "En custodia (": "Held (",
  "Liberadas (": "Released (",
  "En disputa (": "In dispute (",
  "Reembolsadas (": "Refunded (",
  "Consulta todas las contrataciones y abre el documento generado para el cliente o para el proveedor.": "View all engagements and open the document generated for the client or provider.",
  "Contrataciones": "Engagements",
  "En curso o revisión": "In progress or under review",
  "Completados": "Completed",
  "Justificantes disponibles": "Receipts available",
  "Con vista cliente y proveedor": "With client and provider views",
  "No se pudieron cargar los trabajos:": "Could not load jobs:",
  "Todas las contrataciones": "All engagements",
  "No se pudo actualizar": "Could not update",
  "Verificación retirada": "Verification removed",
  "Ha ocurrido un error inesperado. Inténtalo de nuevo.": "An unexpected error occurred. Please try again.",
  "Usuarios Registrados": "Registered users",
  "Gestiona todos los usuarios de la plataforma": "Manage all platform users",
  "Revisar verificaciones": "Review verifications",
  "Total": "Total",
  "Verificados": "Verified",
  "Clientes": "Clients",
  "Buscar por nombre, email o ubicacion...": "Search by name, email or location...",
  "Filtrar por tipo": "Filter by type",
  "Todos los usuarios": "All users",
  "Administradores": "Administrators",
  "No se encontraron usuarios": "No users found",
  "Usuario": "User",
  "Tipo": "Type",
  "Verificación": "Verification",
  "Contacto": "Contact",
  "Ubicacion": "Location",
  "Registro": "Registration",
  "Acciones": "Actions",
  "Verificado": "Verified",
  "Pendiente": "Pending",
  "Ver perfil": "View profile",
  "Retirar": "Remove",
  "Revisar verificación": "Review verification",
  "¿Retirar la verificación?": "Remove verification?",
  "este profesional": "this professional",
  "Retirar verificación": "Remove verification",
  "Marcar en revisión": "Mark as under review",
  "La solicitud quedará en revisión por el equipo de Diime.": "The request will be reviewed by the Diime team.",
  "Verificar proveedor": "Verify provider",
  "Confirma que el equipo ha contactado con el proveedor y revisado su perfil antes de conceder la insignia «Verificado por Diime». Las licencias y titulaciones requieren una comprobación específica.": "Confirm that the team has contacted the provider and reviewed their profile before awarding the “Verified by Diime” badge. Licences and qualifications require a specific check.",
  "Solicitar corrección": "Request a correction",
  "El proveedor podrá corregir su solicitud y volver a enviarla. No tendrá la insignia de verificación.": "The provider will be able to correct and resubmit their request. They will not have the verification badge.",
  "La solicitud quedará cerrada y el proveedor no tendrá la insignia de verificación. Explica el motivo para que sepa cómo proceder.": "The request will be closed and the provider will not have the verification badge. Explain the reason so they know how to proceed.",
  "Proveedor sin nombre": "Unnamed provider",
  "No se pudieron cargar las solicitudes.": "Could not load requests.",
  "No se pudieron cargar las solicitudes. Inténtalo de nuevo.": "Could not load requests. Please try again.",
  "No se pudo cargar el historial.": "Could not load the history.",
  "No se pudo cargar el historial. Inténtalo de nuevo.": "Could not load the history. Please try again.",
  "Confirma que has contactado con el proveedor y revisado su perfil.": "Confirm that you have contacted the provider and reviewed their profile.",
  "Escribe un comentario para que el proveedor sepa qué debe corregir o por qué se retira la verificación.": "Write a comment so the provider knows what to correct or why verification is being removed.",
  "No se pudo guardar la decisión.": "Could not save the decision.",
  "No se pudo confirmar el resultado. Actualiza la bandeja antes de volver a intentarlo.": "Could not confirm the result. Refresh the inbox before trying again.",
  "Revisa solicitudes de particulares y proveedores que trabajan a nombre de una empresa.": "Review requests from individuals and providers acting on behalf of a company.",
  "Reintentar": "Try again",
  "Pendientes": "Pending",
  "Buscar proveedor": "Find a provider",
  "Nombre, empresa, email o teléfono": "Name, company, email or phone number",
  "Todos los estados": "All statuses",
  "Cargando solicitudes…": "Loading requests…",
  "Solicitudes de verificación": "Verification requests",
  "de": "of",
  "solicitudes": "requests",
  "Todavía no hay solicitudes de verificación.": "There are no verification requests yet.",
  "No hay solicitudes que coincidan con estos filtros.": "No requests match these filters.",
  "Sin nombre disponible": "No name available",
  "Particular": "Individual",
  "Sin email disponible": "No email available",
  "Perfil": "Profile",
  "(nueva pestaña)": "(new tab)",
  "Revisar": "Review",
  "Revisar solicitud": "Review request",
  "Empresa": "Company",
  " · Particular": " · Individual",
  "He contactado con el proveedor y revisado su perfil.": "I have contacted the provider and reviewed their profile.",
  "Comentario para el proveedor": "Comment for the provider",
  "El proveedor podrá ver este comentario en su solicitud.": "The provider will be able to see this comment on their request.",
  "Nota interna (opcional)": "Internal note (optional)",
  "Solo la verá el equipo de administración de Diime.": "Only the Diime administration team will see this.",
  "Actualizar solicitud": "Update request",
  "Volver a la solicitud": "Back to the request",
  "Guardando…": "Saving…",
  "Confirmar decisión": "Confirm decision",
  "Actualiza la bandeja antes de tomar otra decisión.": "Refresh the inbox before making another decision.",
  "Email": "Email",
  "No disponible": "Unavailable",
  "Teléfono": "Phone",
  "Actividad": "Activity",
  "No indicada": "Not specified",
  "Actúa como": "Acts as",
  "Cargo no indicado": "Role not specified",
  "Mensaje del proveedor": "Provider's message",
  "Sin mensaje adjunto.": "No message attached.",
  "Último comentario para el proveedor": "Latest comment for the provider",
  "Decisión de Diime": "Diime's decision",
  "Esta solicitud está cerrada. El proveedor debe volver a solicitar la verificación para iniciar una nueva revisión.": "This request is closed. The provider must request verification again to start a new review.",
  "Historial": "History",
  "Cargando historial…": "Loading history…",
  "Sin cambios registrados.": "No changes recorded.",
  "Nota interna": "Internal note",
  "Volver a usuarios": "Back to users",
  "No se pudo cargar el usuario.": "Could not load the user.",
  "reseñas": "reviews",
  "Sin correo disponible": "No email available",
  "Sin teléfono": "No phone number",
  "Sin ubicación": "No location",
  "Sin documento": "No identification document",
  "Recibidos": "Received",
  "Prestados": "Provided",
  "Volumen contratado": "Value of services contracted",
  "Historial de trabajos y justificantes": "Job and receipt history",
  "Centro de ayuda | Diime": "Help centre | Diime",
  "Resolvemos tus dudas sobre cómo funciona Diime.": "Answers to your questions about how Diime works.",
  "¿Cómo publico una demanda de servicio?": "How do I post a service request?",
  "Ve a \"Publicar proyecto\" en el menú principal. Describe lo que necesitas, selecciona la categoría, tu provincia y el presupuesto estimado. En pocas horas recibirás ofertas de profesionales.": "Go to “Post a project” in the main menu. Describe what you need, select the category, your province and your estimated budget. You will receive offers from professionals within a few hours.",
  "¿Cómo funciona el pago protegido?": "How does protected payment work?",
  "Cuando aceptas una oferta, pagas mediante Stripe. La transferencia al profesional se aplaza hasta que confirmas la entrega o hasta que Diime resuelve una disputa.": "When you accept an offer, you pay through Stripe. The transfer to the professional is delayed until you confirm delivery or Diime resolves a dispute.",
  "¿Cómo sé que un profesional es de confianza?": "How do I know a professional is trustworthy?",
  "Todos los profesionales pasan por un proceso de verificación. Además, puedes ver sus valoraciones y reseñas de trabajos anteriores, sus certificaciones y su historial en la plataforma.": "All professionals go through a verification process. You can also view their ratings and reviews from previous jobs, their certifications and their history on the platform.",
  "¿Puedo cancelar un trabajo contratado?": "Can I cancel a job I have contracted?",
  "Sí. Si el trabajo aún no ha comenzado, puedes cancelarlo y recibirás el reembolso completo. Si ya está en progreso, se aplica la política de cancelación parcial según los términos acordados.": "Yes. If the job has not started yet, you can cancel it and receive a full refund. If it is already in progress, the partial cancellation policy applies according to the agreed terms.",
  "¿Cómo me registro como profesional?": "How do I register as a professional?",
  "Crea tu cuenta de usuario y luego accede a \"Conviértete en profesional\" desde el menú. Completa tu perfil con tu especialidad, tarifas y experiencia. Nuestro equipo revisará tu solicitud.": "Create your user account, then select “Become a professional” from the menu. Complete your profile with your speciality, rates and experience. Our team will review your application.",
  "¿Cuál es la comisión de Diime?": "What is Diime's fee?",
  "Diime cobra una comisión por el servicio de pago protegido, la gestión de disputas, la verificación de profesionales y el soporte de la plataforma.": "Diime charges a fee for protected payment, dispute management, professional verification and platform support.",
  "Centro de ayuda": "Help centre",
  "Respuestas a las preguntas más frecuentes sobre Diime.": "Answers to the most frequently asked questions about Diime.",
  "¿No encuentras lo que buscas?": "Can't find what you need?",
  "Nuestro equipo está disponible para ayudarte con cualquier duda.": "Our team is here to help with any questions.",
  "Aviso legal | Diime": "Legal notice | Diime",
  "Información legal y de contacto de Diime.": "Diime's legal and contact information.",
  "Aviso legal": "Legal notice",
  "Última actualización: agosto de 2026": "Last updated: August 2026",
  "1. Titular del sitio y del servicio": "1. Owner of the website and service",
  "En cumplimiento del deber de información aplicable, se facilitan los datos de contacto del titular de Diime y del dominio diime.es:": "To comply with the applicable information requirements, the contact details of the owner of Diime and the diime.es domain are provided below:",
  "Domicilio de contacto: Calle Velázquez 83, 1.º izquierda, Madrid, España": "Contact address: Calle Velázquez 83, 1.º izquierda, Madrid, Spain",
  "Correo electrónico:": "Email:",
  "Teléfono:": "Phone:",
  "2. Objeto de Diime": "2. Purpose of Diime",
  "Diime es una plataforma de intermediación que permite a clientes y profesionales ponerse en contacto, publicar y comparar propuestas, comunicarse y gestionar servicios. Salvo que se indique expresamente lo contrario, Diime no presta el servicio profesional contratado ni es parte del contrato celebrado entre cliente y profesional.": "Diime is an intermediary platform that allows clients and professionals to connect, publish and compare proposals, communicate and manage services. Unless expressly stated otherwise, Diime does not provide the contracted professional service and is not a party to the contract between the client and the professional.",
  "3. Condiciones de uso": "3. Terms of use",
  "El acceso a este sitio implica utilizarlo de forma lícita, diligente y conforme a los": "Accessing this website entails using it lawfully, diligently and in accordance with the",
  "Términos y condiciones": "Terms and conditions",
  "y a las": "and the",
  "Normas de la comunidad": "Community guidelines",
  ". Queda prohibido dañar, sobrecargar o interferir en el servicio, suplantar identidades o utilizarlo para actividades ilícitas o que vulneren derechos de terceros.": ". Damaging, overloading or interfering with the service, impersonating others, or using it for unlawful activities or activities that infringe third-party rights is prohibited.",
  "4. Propiedad intelectual": "4. Intellectual property",
  "Los textos, diseños, marcas, código y demás elementos propios de Diime están protegidos por la normativa de propiedad intelectual e industrial. Los contenidos publicados por los usuarios pertenecen a sus respectivos titulares y se utilizan únicamente en la medida necesaria para prestar y moderar el servicio.": "Diime's own text, designs, trade marks, code and other elements are protected by intellectual and industrial property law. Content published by users belongs to its respective owners and is used only to the extent necessary to provide and moderate the service.",
  "5. Responsabilidad y enlaces": "5. Liability and links",
  "Diime aplica medidas razonables para mantener la plataforma disponible y segura, pero no garantiza la disponibilidad ininterrumpida ni la exactitud de la información aportada por terceros. Los enlaces externos se facilitan como referencia y sus contenidos y políticas son responsabilidad de sus titulares.": "Diime takes reasonable measures to keep the platform available and secure, but does not guarantee uninterrupted availability or the accuracy of information provided by third parties. External links are provided for reference; their owners are responsible for their content and policies.",
  "6. Legislación aplicable": "6. Applicable law",
  "Este aviso se rige por la legislación española. Cuando la normativa de consumo no determine otro fuero imperativo, las controversias se someterán a los juzgados y tribunales competentes de Madrid.": "This notice is governed by Spanish law. Where consumer law does not prescribe another mandatory jurisdiction, disputes shall be submitted to the competent courts and tribunals of Madrid.",
  "Política de cookies | Diime": "Cookie policy | Diime",
  "Política de cookies": "Cookie policy",
  "Última actualización: junio 2026": "Last updated: June 2026",
  "¿Qué son las cookies?": "What are cookies?",
  "Las cookies son pequeños ficheros que se almacenan en tu dispositivo cuando visitas una web. Diime utiliza cookies propias y de terceros para mejorar tu experiencia.": "Cookies are small files stored on your device when you visit a website. Diime uses first-party and third-party cookies to improve your experience.",
  "Tipos de cookies que usamos": "Types of cookies we use",
  "Cookies técnicas (necesarias):": "Technical cookies (necessary):",
  "Imprescindibles para el funcionamiento de la plataforma (autenticación, sesión de usuario y pago protegido).": "Essential for the platform to work (authentication, user sessions and protected payment).",
  "Analítica opcional:": "Optional analytics:",
  "actualmente no cargamos una herramienta de analítica opcional. La preferencia se conserva para que cualquier futura activación requiera consentimiento previo.": "we do not currently load an optional analytics tool. Your preference is retained so that any future activation requires prior consent.",
  "App nativa:": "Native app:",
  "la versión de iOS y Android guarda automáticamente la opción «solo necesarias» y no activa analítica opcional.": "the iOS and Android versions automatically save the “necessary only” option and do not activate optional analytics.",
  "Cómo desactivar las cookies": "How to disable cookies",
  "Puedes configurar tu navegador para rechazar cookies. Ten en cuenta que desactivar cookies técnicas puede afectar al funcionamiento de la plataforma.": "You can configure your browser to reject cookies. Bear in mind that disabling technical cookies may affect how the platform works.",
  "Para cualquier consulta sobre el uso de cookies escríbenos a": "For any questions about our use of cookies, email",
  "Normas de la comunidad | Diime": "Community guidelines | Diime",
  "Reglas de publicación, seguridad y moderación de la comunidad de Diime.": "Rules for publishing, safety and moderation in the Diime community.",
  "1. Trato seguro y respetuoso": "1. Safe and respectful conduct",
  "No se permiten amenazas, acoso, discriminación, suplantación, fraude, extorsión ni la publicación de datos personales de terceros sin autorización.": "Threats, harassment, discrimination, impersonation, fraud, extortion and publishing other people's personal data without authorisation are not allowed.",
  "2. Contenido y servicios prohibidos": "2. Prohibited content and services",
  "Se prohíben el contenido sexual explícito, la explotación de menores, la violencia gráfica, el odio, los servicios ilegales, la venta de drogas o armas y cualquier contenido que infrinja derechos de terceros. Las demandas, perfiles, ofertas, mensajes, archivos y valoraciones deben estar relacionados con un servicio profesional legítimo.": "Sexually explicit content, exploitation of minors, graphic violence, hate, illegal services, the sale of drugs or weapons and any content that infringes third-party rights are prohibited. Requests, profiles, offers, messages, files and reviews must relate to a legitimate professional service.",
  "3. Moderación": "3. Moderation",
  "Diime puede filtrar, ocultar o retirar contenido, limitar funciones y suspender o cerrar cuentas cuando haya indicios de abuso o incumplimiento. Los casos urgentes y los reportes se revisan con prioridad.": "Diime may filter, hide or remove content, restrict features, and suspend or close accounts where there are indications of abuse or non-compliance. Urgent cases and reports are reviewed as a priority.",
  "4. Reportar y bloquear": "4. Reporting and blocking",
  "Puedes reportar un perfil, un mensaje o una conducta desde la propia app. También puedes bloquear a otra persona para impedir nuevas conversaciones. Si existe riesgo inmediato, contacta además con los servicios de emergencia o las autoridades competentes.": "You can report a profile, message or conduct within the app. You can also block another person to prevent new conversations. If there is an immediate risk, also contact the emergency services or the competent authorities.",
  "5. Contacto": "5. Contact",
  "Para una revisión de seguridad escribe a": "For a safety review, email",
  "o utiliza la opción": "or select",
  "Política de privacidad | Diime": "Privacy policy | Diime",
  "Política de privacidad": "Privacy policy",
  "Última actualización: septiembre 2026": "Last updated: September 2026",
  "1. Responsable del tratamiento": "1. Data controller",
  "Juan Díez García, con domicilio de contacto en Calle Velázquez 83, 1.º izquierda, Madrid, España, es el responsable del tratamiento de los datos personales recogidos a través de Diime. Puedes contactar en": "Juan Díez García, whose contact address is Calle Velázquez 83, 1.º izquierda, Madrid, Spain, is the controller of the personal data collected through Diime. You can contact him at",
  "o en el": "or on",
  ". El tratamiento se realiza de conformidad con el Reglamento (UE) 2016/679 (RGPD) y la Ley Orgánica 3/2018 (LOPDGDD).": ". Data is processed in accordance with Regulation (EU) 2016/679 (GDPR) and Spanish Organic Law 3/2018 (LOPDGDD).",
  "2. Datos que recogemos": "2. Data we collect",
  "Recogemos nombre, apellidos, email, teléfono, DNI/NIE, provincia o ubicación indicada manualmente, foto de perfil, datos de empresa cuando corresponda, confirmaciones legales, contenido publicado, mensajes, archivos, eventos del calendario de Diime, incidencias, valoraciones e historial de transacciones. Para acreditar el requisito de edad guardamos la fecha y la versión del texto que confirmaste; no te pedimos ni almacenamos tu fecha de nacimiento. También se generan datos técnicos necesarios para prestar y proteger el servicio, como dirección IP, tipo de dispositivo, páginas solicitadas y registros de error. En la app móvil se generan identificadores de instalación y tokens de notificaciones. Cuando activas los avisos con una sesión iniciada, el token se asocia a tu cuenta para enviarte mensajes, ofertas y novedades de tus trabajos; no se utiliza como identificador publicitario.": "We collect your first name, surname, email, phone number, DNI/NIE, manually entered province or location, profile photo, company details where applicable, legal confirmations, published content, messages, files, Diime calendar events, issues, reviews and transaction history. To document compliance with the age requirement, we store the date and version of the text you confirmed; we do not ask for or store your date of birth. Technical data necessary to provide and protect the service is also generated, such as IP address, device type, requested pages and error logs. The mobile app generates installation identifiers and notification tokens. When you enable alerts while signed in, the token is associated with your account to send you messages, offers and job updates; it is not used as an advertising identifier.",
  "3. Finalidad del tratamiento": "3. Purposes of processing",
  "Los datos se utilizan para: gestionar tu cuenta, procesar pagos, verificar identidades, conectar clientes con profesionales, moderar contenido y prevenir fraude, enviar comunicaciones relacionadas con el servicio, atender incidencias y cumplir obligaciones legales.": "We use data to manage your account, process payments, verify identities, connect clients with professionals, moderate content and prevent fraud, send service-related communications, handle issues and comply with legal obligations.",
  "4. Tus derechos": "4. Your rights",
  "Puedes ejercer tus derechos de acceso, rectificación, supresión, oposición, limitación y portabilidad escribiendo a": "You may exercise your rights of access, rectification, erasure, objection, restriction of processing and data portability by emailing",
  "5. Conservación de datos": "5. Data retention",
  "Conservamos tus datos mientras mantengas tu cuenta activa o durante el tiempo necesario para cumplir las finalidades descritas. Tras la baja se eliminan el acceso y la presencia pública. Los registros de contratos, pagos, facturas, fraude, disputas o reclamaciones se conservan solo durante los plazos legales aplicables.": "We retain your data while your account remains active or for as long as necessary to fulfil the purposes described. After account closure, access and your public presence are removed. Records relating to contracts, payments, invoices, fraud, disputes or claims are retained only for the applicable statutory periods.",
  "6. Proveedores": "6. Service providers",
  "Diime utiliza proveedores necesarios para prestar el servicio: Supabase para autenticación y base de datos, Stripe para pagos, Vercel para alojamiento, archivos y registros técnicos, Resend para comunicaciones transaccionales, Firebase Cloud Messaging de Google para notificaciones Android y Apple Push Notification service para notificaciones iOS. Los servicios de notificaciones reciben el identificador de destino y el contenido del aviso, que puede incluir el remitente y una vista previa de un mensaje. Cada proveedor recibe únicamente los datos necesarios para su función y está sujeto a sus obligaciones contractuales y de privacidad. Stripe recoge los datos de tarjeta en su propio formulario; Diime recibe el identificador y el estado de la transacción, pero no el número completo de la tarjeta.": "Diime uses the providers needed to deliver the service: Supabase for authentication and the database, Stripe for payments, Vercel for hosting, files and technical logs, Resend for transactional communications, Google's Firebase Cloud Messaging for Android notifications and Apple Push Notification service for iOS notifications. Notification services receive the destination identifier and alert content, which may include the sender and a message preview. Each provider receives only the data necessary for its role and is subject to its contractual and privacy obligations. Stripe collects card details in its own form; Diime receives the transaction identifier and status, but not the full card number.",
  "7. Eliminación y opciones de privacidad": "7. Deletion and privacy options",
  "Puedes eliminar tu cuenta directamente desde Configuración o iniciar el proceso en": "You can delete your account directly from Settings or start the process at",
  ". También puedes contactar con": ". You can also contact",
  "para ejercer tus derechos o pedir ayuda.": "to exercise your rights or ask for help.",
  "8. Seguimiento y permisos del dispositivo": "8. Tracking and device permissions",
  "Diime no utiliza los datos para rastrearte entre aplicaciones o sitios de otras empresas, no muestra publicidad y no vende datos personales. La app no solicita ubicación GPS; la provincia se introduce manualmente. En Android se utilizan permisos de Internet, estado de red, vibración, recepción de notificaciones y actualización del contador del icono. Puedes desactivar las notificaciones en los ajustes del sistema; en las versiones que lo requieren se solicita permiso para mostrarlas. No se solicita acceso persistente a toda la biblioteca de fotos. Los archivos o imágenes solo se transmiten cuando la persona los selecciona o captura expresamente para adjuntarlos.": "Diime does not use data to track you across other companies' apps or websites, does not display advertising and does not sell personal data. The app does not request GPS location; your province is entered manually. On Android, permissions are used for Internet access, network status, vibration, receiving notifications and updating the app icon badge count. You can disable notifications in your system settings; on versions that require it, permission is requested to display them. Persistent access to your entire photo library is not requested. Files or images are transmitted only when a person expressly selects or captures them to attach them.",
  "Términos y condiciones | Diime": "Terms and conditions | Diime",
  "1. Aceptación de los términos": "1. Acceptance of the terms",
  "Al acceder y utilizar Diime (diime.es), aceptas quedar vinculado por estos Términos y Condiciones. Si no estás de acuerdo con alguno de estos términos, te pedimos que no utilices nuestros servicios.": "By accessing and using Diime (diime.es), you agree to be bound by these Terms and Conditions. If you disagree with any of these terms, please do not use our services.",
  "2. Descripción del servicio": "2. Description of the service",
  "Diime es una plataforma de intermediación que conecta a particulares y empresas que necesitan servicios profesionales (clientes) con profesionales autónomos o empresas que ofrecen dichos servicios (proveedores). Diime no es parte en los contratos de servicios que se celebran entre clientes y proveedores.": "Diime is an intermediary platform that connects individuals and businesses needing professional services (clients) with self-employed professionals or businesses offering those services (providers). Diime is not a party to the service contracts entered into between clients and providers.",
  "3. Registro y cuenta de usuario": "3. Registration and user account",
  "Para registrarte y utilizar Diime debes tener al menos 18 años y capacidad legal para contratar. Si actúas por una empresa, debes estar autorizado para representarla. Durante el alta se te pedirá una confirmación expresa de mayoría de edad; las cuentas no pueden ser utilizadas por menores. El usuario se compromete a proporcionar información veraz, actual y completa, mantenerla actualizada y proteger la confidencialidad de su contraseña.": "To register and use Diime, you must be at least 18 years old and have legal capacity to contract. If you act on behalf of a company, you must be authorised to represent it. During registration, you will be asked to expressly confirm that you are an adult; accounts may not be used by minors. Users undertake to provide truthful, current and complete information, keep it up to date, and protect the confidentiality of their password.",
  "4. Sistema de pago protegido": "4. Protected payment system",
  "El cliente paga antes del inicio del trabajo mediante Stripe. La transferencia al profesional queda aplazada y se ejecuta cuando el cliente confirma la correcta recepción o cuando Diime resuelve una disputa. Este servicio no constituye una cuenta escrow ni un depósito regulado. Los trabajos deben cerrarse dentro del plazo máximo que permita Stripe Connect.": "The client pays through Stripe before the job begins. The transfer to the professional is delayed and executed when the client confirms satisfactory receipt or when Diime resolves a dispute. This service does not constitute an escrow account or a regulated deposit. Jobs must be closed within the maximum period permitted by Stripe Connect.",
  "5. Comisiones": "5. Fees",
  "Diime aplica gastos de servicio sobre cada transacción completada. El porcentaje vigente se indica en la plataforma antes de confirmar cada operación y el importe mostrado incluye el IVA aplicable a los servicios de Diime. Las tarifas están sujetas a cambios con previo aviso de 30 días.": "Diime applies service fees to each completed transaction. The current percentage is shown on the platform before each transaction is confirmed, and the amount displayed includes the VAT applicable to Diime's services. Fees may change with 30 days' prior notice.",
  "El proveedor fija el precio final de su servicio, incluyendo los impuestos que correspondan, y es el único responsable de determinar su tratamiento fiscal, emitir la factura al cliente y declarar e ingresar el IVA cuando resulte aplicable. Diime no calcula, retiene ni declara el IVA correspondiente al servicio prestado por el proveedor.": "The provider sets the final price of their service, including any applicable taxes, and is solely responsible for determining its tax treatment, issuing the invoice to the client, and reporting and remitting VAT where applicable. Diime does not calculate, withhold or report the VAT corresponding to the service provided by the provider.",
  "6. Cancelaciones y reembolsos": "6. Cancellations and refunds",
  "Las condiciones de cancelación y reembolso dependen del estado del trabajo. Antes del inicio, el cliente puede cancelar y recibir un reembolso completo. Una vez iniciado el trabajo, la política de reembolso se aplica de forma proporcional al trabajo realizado, según lo acordado entre las partes.": "Cancellation and refund conditions depend on the job's status. Before the job starts, the client may cancel and receive a full refund. Once work has started, the refund policy applies in proportion to the work carried out, as agreed between the parties.",
  "7. Contenido y conducta de los usuarios": "7. User content and conduct",
  "Al publicar perfiles, demandas, ofertas, mensajes, archivos o valoraciones aceptas las Normas de la comunidad. No se permite contenido ilegal, fraudulento, sexual explícito, violento, discriminatorio, amenazante, que vulnere derechos de terceros o que exponga datos personales sin autorización. Diime puede filtrar, ocultar o retirar contenido y limitar o cerrar cuentas cuando sea necesario para proteger a la comunidad o cumplir la ley.": "By publishing profiles, requests, offers, messages, files or reviews, you accept the Community guidelines. Content that is illegal, fraudulent, sexually explicit, violent, discriminatory, threatening, infringes third-party rights or exposes personal data without authorisation is not allowed. Diime may filter, hide or remove content and restrict or close accounts where necessary to protect the community or comply with the law.",
  "8. Reportes y bloqueo": "8. Reporting and blocking",
  "Los usuarios pueden reportar contenido o conductas desde la plataforma y bloquear a otras personas para impedir nuevas comunicaciones. Diime revisará los reportes y podrá solicitar información adicional. Las reglas completas se encuentran en las": "Users can report content or conduct through the platform and block others to prevent new communications. Diime will review reports and may request additional information. The full rules are set out in the",
  "9. Baja y eliminación de cuenta": "9. Account closure and deletion",
  "Puedes iniciar la eliminación desde Configuración → Eliminar mi cuenta o desde la página pública de eliminación. Se retirará tu presencia pública y se suprimirán los datos que no debamos conservar por obligaciones legales, contables, prevención del fraude o defensa frente a reclamaciones. Antes de confirmar se explicarán las consecuencias sobre trabajos, pagos o disputas pendientes.": "You can start deletion from Settings → Delete my account or from the public account deletion page. Your public presence will be removed and any data that we are not required to retain for legal or accounting obligations, fraud prevention or defence against claims will be deleted. Before confirmation, the consequences for pending jobs, payments or disputes will be explained.",
  "10. Contacto": "10. Contact",
  "Diime es un servicio titularidad de Juan Díez García. Para cualquier consulta relacionada con estos términos, puedes escribir a": "Diime is a service owned by Juan Díez García. For any questions relating to these terms, you can email",
  ". Los datos de contacto del titular se encuentran en el": ". The owner's contact details can be found in the",
  "Sobre nosotros | Diime": "About us | Diime",
  "Conoce Diime, la plataforma española que conecta profesionales cualificados con clientes.": "Discover Diime, the Spanish platform connecting qualified professionals with clients.",
  "Hecho en España": "Made in Spain",
  "Sobre Diime": "About Diime",
  "Somos la plataforma que conecta a personas que necesitan servicios del hogar y la construcción con profesionales de toda España.": "We are the platform connecting people who need home and construction services with professionals across Spain.",
  "Diime nació de una necesidad real: encontrar un fontanero, electricista o carpintero de confianza siempre ha sido complicado. Las plataformas genéricas no estaban pensadas para los servicios de economía real — esos que requieren presencia física, negociación de plazos y garantías de calidad.": "Diime was born out of a real need: finding a trustworthy plumber, electrician or carpenter has always been difficult. General-purpose platforms were not designed for services in the real economy — those requiring a physical presence, negotiated deadlines and quality guarantees.",
  "Nuestra misión es democratizar el acceso a profesionales cualificados en toda España, ofreciendo a los clientes transparencia en precios y valoraciones, y a los profesionales una herramienta para conseguir trabajo de calidad sin comisiones abusivas.": "Our mission is to make qualified professionals accessible to everyone across Spain, giving clients transparent prices and reviews, and professionals a tool for finding quality work without excessive fees.",
  "El sistema de pago protegido de Diime protege tanto al cliente como al profesional: la transferencia queda pendiente hasta que el trabajo esté completado y el cliente confirme la entrega.": "Diime's protected payment system protects both clients and professionals: the transfer remains pending until the job is completed and the client confirms delivery.",
  "Verificados en todas las provincias de España": "Verified across every province in Spain",
  "Pagos protegidos": "Protected payments",
  "La transferencia espera hasta la confirmación de la entrega": "The transfer waits until delivery is confirmed",
  "Media de satisfacción de clientes en la plataforma": "Average client satisfaction on the platform",
  "¿Tienes alguna pregunta?": "Have a question?",
  "Escríbenos a": "Email us at",
  "o visita nuestro centro de ayuda.": "or visit our help centre.",
  "Explorar profesionales": "Explore professionals",
  "Cobros profesionales | Diime": "Professional payouts | Diime",
  "Consulta tu saldo de Stripe y tus próximos ingresos profesionales.": "Check your Stripe balance and upcoming professional payouts.",
  "Tus cobros": "Your payouts",
  "Saldo liberado, disponibilidad y próximos ingresos bancarios gestionados por Stripe.": "Released balance, availability and upcoming bank payouts managed by Stripe.",
  "Demandas de Servicios | Diime": "Service requests | Diime",
  "Explora las demandas de servicios publicadas y envía tus presupuestos": "Explore published service requests and send your quotes",
  "Demandas de Servicios": "Service requests",
  "Explora las solicitudes de servicios publicadas por usuarios. Filtra por tu especialidad y ubicación para encontrar proyectos y enviar tus presupuestos.": "Explore service requests posted by users. Filter by your speciality and location to find projects and send your quotes.",
  "Incidencias | Diime": "Issues | Diime",
  "Reporta problemas y sigue el estado de tus incidencias con el equipo de Diime": "Report problems and track your issues with the Diime team",
  "Reporta problemas con pagos, trabajos u otros usuarios y sigue aquí el estado de cada incidencia. Nuestro equipo las revisa y responde.": "Report problems with payments, jobs or other users and track each issue here. Our team reviews and responds to them.",
  "Mensajes | Diime": "Messages | Diime",
  "Gestiona tus conversaciones con clientes y profesionales": "Manage your conversations with clients and professionals",
  "Mi Perfil | Diime": "My profile | Diime",
  "Gestiona tu perfil profesional, habilidades, experiencia y trabajos pasados": "Manage your professional profile, skills, experience and previous work",
  "Mis Pujas | Diime": "My bids | Diime",
  "Gestiona las pujas que has enviado: edítalas o retíralas mientras no hayan sido aceptadas": "Manage the bids you have sent: edit or withdraw them while they have not been accepted",
  "Mis Pujas": "My bids",
  "Gestiona las pujas que has enviado a los clientes. Puedes editarlas o retirarlas mientras no hayan sido aceptadas.": "Manage the bids you have sent to clients. You can edit or withdraw them while they have not been accepted.",
  "Mis Solicitudes | Diime": "My requests | Diime",
  "Gestiona tus solicitudes de servicios publicadas y revisa las ofertas recibidas": "Manage your published service requests and review the offers you receive",
  "Mis Solicitudes": "My requests",
  "Gestiona las solicitudes de servicios que has publicado. Revisa las ofertas recibidas, el estado de cada solicitud y el progreso de los trabajos contratados.": "Manage the service requests you have posted. Review incoming offers, each request's status and the progress of contracted jobs.",
  "Esperando Pago": "Awaiting payment",
  "El cliente debe realizar el pago para iniciar": "The client must pay before work can begin",
  "En Progreso": "In progress",
  "Trabajo en curso": "Work in progress",
  "Pendiente de confirmación del cliente": "Awaiting the client's confirmation",
  "Trabajo finalizado": "Job completed",
  "Cancelado": "Cancelled",
  "Trabajo cancelado": "Job cancelled",
  "En revisión por el equipo de Diime": "Under review by the Diime team",
  "Progreso actualizado": "Progress updated",
  "Trabajo entregado": "Job delivered",
  "El cliente ha sido notificado para confirmar la entrega": "The client has been notified to confirm delivery",
  "No se pudo identificar al cliente.": "Could not identify the client.",
  "Gestión de Proyectos": "Project management",
  "Cronograma editable, lista de proyectos y eventos personalizados en un solo lugar": "An editable timeline, project list and custom events in one place",
  "Activos": "Active",
  "trabajo": "job",
  "Entregados · pendiente de cobro": "Delivered · awaiting payment release",
  "esperando confirmación del cliente": "awaiting the client's confirmation",
  "Completados · total cobrado (neto)": "Completed · total received (net)",
  "finalizado": "completed",
  "En disputa · retenido": "In dispute · held",
  "en disputa": "in dispute",
  "No tienes trabajos activos": "You have no active jobs",
  "Busca demandas de servicios y envía ofertas para conseguir nuevos proyectos": "Browse service requests and send offers to find new projects",
  "Ver demandas disponibles": "View available requests",
  "No tienes trabajos pendientes de confirmación": "You have no jobs awaiting confirmation",
  "Los trabajos entregados aparecerán aquí hasta que el cliente confirme": "Delivered jobs will appear here until the client confirms them",
  "No tienes trabajos completados": "You have no completed jobs",
  "Los trabajos finalizados y confirmados aparecerán aquí": "Completed and confirmed jobs will appear here",
  "Calendario de proyectos": "Project calendar",
  "Visualiza inicios, entregas, festivos y eventos personales": "View start dates, deliveries, public holidays and personal events",
  "Abrir calendario": "Open calendar",
  "Acciones rapidas": "Quick actions",
  "Mensajes con clientes": "Messages with clients",
  "Pujas enviadas": "Bids sent",
  "Actualizar Progreso": "Update progress",
  "Actualiza el estado de avance del proyecto \"": "Update the progress of the project “",
  "Progreso actual": "Current progress",
  "Mensaje para el cliente (opcional)": "Message for the client (optional)",
  "Describe los avances realizados...": "Describe the progress made...",
  "Marcar como Entregado": "Mark as delivered",
  "Notifica al cliente que el trabajo \"": "Notify the client that the job “",
  "\" está listo": "” is ready",
  "Al marcar como entregado:": "When you mark the job as delivered:",
  "El cliente recibirá una notificación": "The client will receive a notification",
  "Tendrá que revisar y confirmar el trabajo": "They will need to review and confirm the work",
  "Una vez confirmado, se liberará el pago": "Once confirmed, payment will be released",
  "Mensaje de entrega (opcional)": "Delivery message (optional)",
  "Añade detalles sobre la entrega, instrucciones de uso, etc.": "Add delivery details, instructions for use, etc.",
  "Pago confirmado · transferencia pendiente: puedes empezar el trabajo": "Payment confirmed · transfer pending: you can start the job",
  "Progreso": "Progress",
  "Vence hoy": "Due today",
  "Archivos de tu oferta (": "Files from your offer (",
  "Pago recibido:": "Payment received:",
  "netos": "net",
  "Transferencia pendiente: cobrarás": "Transfer pending: you will receive",
  "Esperando pago del cliente": "Awaiting client payment",
  "Liberado el": "Released on",
  "Precio acordado": "Agreed price",
  "− comisión Diime (": "− Diime fee (",
  "Ver justificante y términos": "View receipt and terms",
  "Entregar Trabajo": "Deliver job",
  "El proyecto iniciará cuando el cliente realice el pago": "The project will start when the client pays",
  "Esperando confirmación del cliente": "Awaiting the client's confirmation",
  "Cuando confirme la entrega, el pago se liberará a tu favor. Si no responde, puedes abrir una disputa y el equipo de Diime revisará la entrega para liberarte el pago.": "When they confirm delivery, payment will be released to you. If they do not respond, you can open a dispute and the Diime team will review the delivery to release your payment.",
  "Trabajo en disputa": "Job in dispute",
  "El equipo de Diime lo está revisando. El pago queda retenido hasta la resolución.": "The Diime team is reviewing it. Payment remains held until resolution.",
  "Contactar Cliente": "Contact client",
  "Abrir disputa": "Open dispute",
  "Cobrado": "Received",
  "de cobro": "for payment",
  "Sin conexión | Diime": "Offline | Diime",
  "Sin conexión": "Offline",
  "No hemos podido conectar con Diime. Comprueba tu conexión: en cuanto vuelva, esta pantalla se actualiza sola al recargar.": "We could not connect to Diime. Check your connection: once it is restored, this screen will update when you reload.",
  "Profesional no encontrado": "Professional not found",
  "El perfil que buscas no existe o ha sido eliminado. Puedes explorar otros profesionales disponibles.": "The profile you are looking for does not exist or has been deleted. You can explore other available professionals.",
  "Volver al inicio": "Back to home",
  "Ver profesionales": "View professionals",
  "Perfil no encontrado | Diime": "Profile not found | Diime",
  "Profesional en Diime": "Professional on Diime",
  "Perfil | Diime": "Profile | Diime",
  "24 horas": "24 hours",
  "Experto Verificado": "Verified expert",
  "Disponible": "Available",
  "Proyecto": "Project",
  "Profesionales - Diime": "Professionals - Diime",
  "Encuentra profesionales para tus proyectos de construcción y reformas": "Find professionals for your construction and renovation projects",
  "Encuentra y contacta directamente con profesionales para tu proyecto.": "Find and contact professionals directly for your project.",
  "No especificado": "Not specified",
  "Incluidos en el precio": "Included in the price",
  "No incluidos (a cargo del cliente)": "Not included (paid by the client)",
  "Parcialmente incluidos": "Partially included",
  "Justificante y desglose fiscal | Diime": "Receipt and tax breakdown | Diime",
  "En su nombre:": "On its behalf:",
  "Base imponible del servicio de Diime": "Taxable amount for Diime's service",
  "IVA de Diime (": "Diime VAT (",
  "Pagado · pendiente de liquidación": "Paid · awaiting settlement",
  "Procesando reembolso/transferencia": "Processing refund/transfer",
  "Pagado · liberado al profesional": "Paid · released to the professional",
  "Reembolsado al cliente": "Refunded to the client",
  "Congelado por disputa": "Frozen due to dispute",
  "Justificante de pago y desglose fiscal": "Payment receipt and tax breakdown",
  "Propuesta y términos": "Proposal and terms",
  "días": "days",
  "Según lo acordado entre las partes": "As agreed between the parties",
  "Ref.": "Ref.",
  "· Generado el": "· Generated on",
  "Vista administrativa ·": "Administrative view ·",
  "Diime": "Diime",
  "Detalle del servicio contratado": "Details of the contracted service",
  "Detalle de la propuesta aceptada": "Details of the accepted proposal",
  "Necesidad publicada por el cliente:": "Need posted by the client:",
  "Adjuntos de la publicación de la demanda": "Attachments to the service request",
  "Propuesta del profesional aceptada por el cliente": "Professional's proposal accepted by the client",
  "Servicio incluido:": "Service included:",
  "Notas del profesional:": "Professional's notes:",
  "Adjuntos de la oferta aceptada": "Attachments to the accepted offer",
  "Lugar de realización / entrega": "Place of performance / delivery",
  "A convenir": "To be agreed",
  "Plazo estimado": "Estimated duration",
  "Fecha de inicio": "Start date",
  "Entrega estimada": "Estimated delivery",
  "Condiciones de pago": "Payment terms",
  "Pago único por adelantado mediante Stripe; transferencia aplazada hasta la confirmación o resolución": "Single upfront payment through Stripe; transfer delayed until confirmation or resolution",
  "Al aceptar la puja, el cliente aceptó este detalle del servicio tal y como lo propuso el profesional. Todo lo no incluido expresamente queda fuera del encargo.": "By accepting the bid, the client accepted these service details as proposed by the professional. Anything not expressly included is outside the scope of the engagement.",
  "Importe": "Amount",
  "Servicio profesional contratado": "Contracted professional service",
  "Servicio pendiente de pago": "Service awaiting payment",
  "· Precio final indicado por el proveedor · Ref. TRB-": "· Final price specified by the provider · Ref. TRB-",
  "Gastos de servicio Diime (IVA del": "Diime service fees (VAT at",
  "% incluido)": "% included)",
  "%, mín.": "%, min.",
  "Total pagado por el cliente": "Total paid by the client",
  "Total pendiente de pago por el cliente": "Total awaiting payment by the client",
  "Reembolso del precio del servicio": "Refund of the service price",
  "Coste final tras la resolución": "Final cost after resolution",
  "El precio del servicio es el importe final indicado por el proveedor e incluye los impuestos que le correspondan. Diime no calcula ni retiene esos impuestos.": "The service price is the final amount specified by the provider and includes any applicable taxes. Diime does not calculate or withhold those taxes.",
  "Liquidación del profesional": "Professional's settlement",
  "Importe bruto adjudicado tras la resolución": "Gross amount allocated after resolution",
  "Precio del servicio": "Service price",
  "Neto a percibir por el profesional": "Net amount payable to the professional",
  "Neto previsto para el profesional": "Expected net amount for the professional",
  "Pago liberado al profesional el": "Payment released to the professional on",
  "Reembolsado al cliente:": "Refunded to the client:",
  "La comisión inicial del cliente (": "The original client fee (",
  ") no se reduce: cubre el servicio de pago protegido y gestión de la disputa.": ") is not reduced: it covers the protected payment service and dispute management.",
  "Responsabilidades fiscales": "Tax responsibilities",
  "Servicios de Diime:": "Diime's services:",
  "los gastos de servicio mostrados en este documento incluyen el IVA del": "the service fees shown in this document include VAT at",
  "%. Diime es responsable de declarar el IVA correspondiente a sus propias comisiones.": "%. Diime is responsible for reporting the VAT corresponding to its own fees.",
  "Servicio profesional:": "Professional service:",
  "el proveedor es quien presta el servicio y quien debe determinar su tratamiento fiscal, emitir la factura al cliente y declarar e ingresar el IVA cuando corresponda. Diime no emite esa factura ni declara el IVA del proveedor.": "the provider delivers the service and must determine its tax treatment, issue the invoice to the client, and report and remit VAT where applicable. Diime does not issue that invoice or report the provider's VAT.",
  "Este documento acredita la contratación, el pago y la liquidación, pero no sustituye las facturas fiscales que deban emitir Diime y el proveedor por sus respectivos servicios.": "This document records the engagement, payment and settlement, but does not replace the tax invoices that Diime and the provider must issue for their respective services.",
  "El importe abonado por el cliente queda": "The amount paid by the client is",
  "cobrado mediante Stripe con la transferencia aplazada": "collected through Stripe with the transfer delayed",
  "y solo se abona al profesional cuando el cliente confirma la entrega del trabajo.": "and is paid to the professional only when the client confirms delivery of the work.",
  "Cualquiera de las partes puede solicitar la": "Either party may request",
  "cancelación de mutuo acuerdo": "cancellation by mutual agreement",
  "antes de la entrega. Si la otra parte la acepta y el trabajo ya estaba pagado, el cliente recibe el": "before delivery. If the other party accepts and the job has already been paid for, the client receives a",
  "reembolso íntegro": "full refund",
  "automáticamente.": "automatically.",
  "Si la cancelación se rechaza, se abre automáticamente una": "If cancellation is declined, a",
  "disputa": "dispute",
  "que resuelve el equipo de Diime conforme a estos términos.": "is automatically opened and resolved by the Diime team in accordance with these terms.",
  "En caso de duda, se resolverá a favor del cliente.": "In case of doubt, the decision will be in the client's favour.",
  "Si el cliente rechaza una entrega, se le reembolsa el importe pagado excepto los gastos de servicio de la plataforma, que no son reembolsables.": "If the client rejects a delivery, the amount paid is refunded except for the platform's service fees, which are non-refundable.",
  "La conversación y los archivos intercambiados en Diime forman parte de la documentación del encargo y podrán utilizarse como prueba en caso de disputa.": "The conversation and files exchanged on Diime form part of the engagement documentation and may be used as evidence in the event of a dispute.",
  "La resolución de disputas por parte de Diime es una mediación privada entre las partes y no impide ni sustituye cualquier otra acción legal que cada parte pueda emprender por su cuenta.": "Diime's dispute resolution is private mediation between the parties and does not prevent or replace any other legal action that either party may take independently.",
  "Justificante generado automáticamente por Diime (diime.es) como plataforma intermediaria del pago protegido. Recoge el servicio contratado, los importes, los términos, el reembolso y la liquidación cuando corresponden. La transferencia al profesional se ejecuta tras la confirmación o resolución.": "Receipt automatically generated by Diime (diime.es) as the intermediary platform for protected payment. It records the contracted service, amounts, terms, refund and settlement where applicable. The transfer to the professional is executed after confirmation or resolution.",
  "Documento informativo generado por Diime (diime.es). Recoge la propuesta aceptada, los importes previstos y sus términos, pero la contratación queda pendiente hasta que el cliente complete el pago protegido.": "Information document generated by Diime (diime.es). It records the accepted proposal, expected amounts and terms, but the engagement remains pending until the client completes the protected payment.",
  "Cuenta eliminada": "Account deleted",
  "Miembro desde": "Member since",
  "contratado": "contracted",
  "Sobre mí": "About me",
  "No se pudo renovar el enlace de Stripe": "Could not renew the Stripe link",
  "Vuelve a tu perfil e inténtalo de nuevo.": "Go back to your profile and try again.",
  "Volver a Diime": "Back to Diime",
  "Transferencia pendiente": "Transfer pending",
  "Congelado": "Frozen",
  "Usuario no disponible": "User unavailable",
  "Sin nombre": "Unnamed",
  "Sin pago": "No payment",
  "Sin estado": "No status",
  "No hay trabajos en esta sección.": "There are no jobs in this section.",
  "Buscar por trabajo, referencia o usuario...": "Search by job, reference or user...",
  "Estado del trabajo": "Job status",
  "Servicio": "Service",
  "Papel": "Role",
  "Contraparte": "Other party",
  "Pago": "Payment",
  "Contratación": "Engagement",
  "Justificante": "Receipt",
  "No hay resultados con estos filtros.": "No results match these filters.",
  "Como cliente": "As client",
  "Como proveedor": "As provider",
  "No contratado": "Not contracted",
  "Ver el justificante desde la perspectiva del cliente": "View the receipt from the client's perspective",
  "Vista cliente": "Client view",
  "Ver el justificante y la liquidación del proveedor": "View the provider's receipt and settlement",
  "Vista proveedor": "Provider view",
  "Aún no generada": "Not yet generated",
  "Todos (": "All (",
  "Recibidos (": "Received (",
  "Prestados (": "Provided (",
  "Imprimir / Guardar PDF": "Print / Save PDF",
  "Nombre: Juan Díez García": "Name: Juan Díez García",
  "Nombre:": "Name:",
  "Trabajo:": "Job:",
  "prueba": "evidence",
  "Críticas pendientes": "Pending critical issues",
  "Solicitada:": "Requested:",
  "Actualizada:": "Updated:",
  "Alta:": "Joined:",
  "Proveedor del servicio": "Service provider",
  "Materiales:": "Materials:",
  "5.000+ profesionales": "5,000+ professionals",
  "4.9 de valoración": "4.9 rating",
  "de {total} totales": "out of {total} in total",
  "{cantidad} crítica": "{cantidad} critical",
  "{cantidad} críticas": "{cantidad} critical",
  "{importe} retenidos en custodia": "{importe} held",
  "Devolver {importe} del servicio": "Refund {importe} of the service price",
  "Máx. {importe}": "Max. {importe}",
  "La insignia dejará de mostrarse en el perfil de {nombre}.": "The badge will no longer appear on {nombre}’s profile.",
  "Decisión guardada para {nombre}: {estado}.": "Decision saved for {nombre}: {estado}.",
  "Empresa: {nombre}": "Company: {nombre}",
  "Revisar solicitud de {nombre}": "Review request from {nombre}",
  "El progreso se ha actualizado al {progreso}%": "Progress has been updated to {progreso}%",
  "{cantidad} día restante": "{cantidad} day remaining",
  "{cantidad} días restantes": "{cantidad} days remaining",
  "{cantidad} día de retraso": "{cantidad} day overdue",
  "{cantidad} días de retraso": "{cantidad} days overdue",
  "{cantidad} trabajo finalizado": "{cantidad} completed job",
  "{cantidad} trabajos finalizados": "{cantidad} completed jobs",
  "{cantidad} trabajo contratado": "{cantidad} job contracted",
  "{cantidad} trabajos contratados": "{cantidad} jobs contracted",
  "{cantidad} proyecto completado.": "{cantidad} project completed.",
  "{cantidad} proyectos completados.": "{cantidad} projects completed.",
  "{cantidad} {unidad} desde el inicio del trabajo": "{cantidad} {unidad} from the start of the job",
  "el {fecha}": "on {fecha}",
  "Verificado por Diime": "Verified by Diime",
  "Necesita corrección": "Correction required",
  "baja": "low",
  "media": "medium",
  "alta": "high",
  "critica": "critical",
  "pendiente": "pending",
  "fondos_retenidos": "funds held",
  "liquidando": "settling",
  "completado": "completed",
  "reembolsado": "refunded",
  "en_revision": "under review",
  "abierta": "open",
  "resuelta": "resolved",
  "cerrada": "closed",
  "cliente": "client",
  "proveedor": "provider",
  "profesional": "professional",
  "horas": "hours",
  "día": "day",
  "semanas": "weeks",
  "meses": "months",
  "Actualiza el estado de avance del proyecto \"{titulo}\"": "Update the progress of the project “{titulo}”",
  "Notifica al cliente que el trabajo \"{titulo}\" está listo": "Notify the client that the job “{titulo}” is ready",
  "cancelacion_solicitada": "cancellation requested",
  "cancelacion_actualizada": "cancellation updated",
  "cancelacion_retirada": "cancellation withdrawn",
  "cancelacion_aceptada": "cancellation accepted",
  "disputa_abierta": "dispute opened",
  "progreso": "progress",
  "entrega": "delivery"
}
