export const EN_SERVER: Record<string, string> = {
  "Base de datos no disponible": "Database unavailable",
  "No autenticado": "Not signed in",
  "No tienes permiso para consultar trabajos y justificantes": "You do not have permission to view jobs and payment records",
  "Usuario no válido": "Invalid user",
  "Usuario no encontrado": "User not found",
  "No tienes permiso para ver este perfil": "You do not have permission to view this profile",
  "Solicitud de verificación no válida": "Invalid verification request",
  "No tienes permiso para verificar profesionales": "You do not have permission to verify professionals",
  "El usuario seleccionado no es profesional": "The selected user is not a professional",
  "No se pudo actualizar la verificación. Comprueba que la migración de permisos administrativos esté aplicada.": "Verification could not be updated. Check that the administrator permissions migration has been applied.",
  "No se pudo conectar con la base de datos": "Could not connect to the database",
  "Debes aceptar los Términos y las Normas de la comunidad.": "You must accept the Terms and Community Guidelines.",
  "Para crear una cuenta debes confirmar que tienes 18 años o más.": "To create an account, you must confirm that you are at least 18 years old.",
  "Indica tu DNI/NIE como persona que representa a la empresa": "Enter your DNI/NIE as the person representing the company",
  "Indica el nombre y CIF de tu empresa o utiliza una invitación": "Enter your company’s name and tax ID (CIF), or use an invitation",
  "Has excedido el límite de registros por hora. Por favor espera 1 hora o contacta con soporte para aumentar el límite.": "You have exceeded the hourly sign-up limit. Please wait one hour or contact support to increase the limit.",
  "Este email ya está registrado. Intenta iniciar sesión.": "This email address is already registered. Try signing in.",
  "Error al crear usuario": "Could not create the user",
  "Debes iniciar sesión": "You must sign in",
  "No se ha podido guardar la confirmación. Inténtalo de nuevo.": "Your confirmation could not be saved. Please try again.",
  "La confirmación se guardó, pero no se pudo actualizar la sesión.": "Your confirmation was saved, but your session could not be updated.",
  "No perteneces a ninguna empresa": "You do not belong to a company",
  "Usuario no válido.": "Invalid user.",
  "No se pudo comprobar el perfil.": "The profile could not be checked.",
  "Base de datos no disponible.": "Database unavailable.",
  "Inicia sesión para bloquear a un usuario.": "Sign in to block a user.",
  "No puedes bloquearte a ti mismo.": "You cannot block yourself.",
  "No se pudo comprobar el perfil. Inténtalo de nuevo.": "The profile could not be checked. Please try again.",
  "El usuario ya no está disponible.": "This user is no longer available.",
  "No puedes bloquear al equipo de Diime.": "You cannot block the Diime team.",
  "Falta aplicar la migración de bloqueo de usuarios.": "The user blocking migration has not been applied.",
  "No se pudo conectar a la base de datos": "Could not connect to the database",
  "No tienes permiso para editar este trabajo": "You do not have permission to edit this job",
  "No se pudo conectar con la base de datos.": "Could not connect to the database.",
  "La configuración segura del servidor no está disponible": "The secure server configuration is unavailable",
  "Describe el motivo de la disputa.": "Describe the reason for the dispute.",
  "Explica por qué la entrega no cumple lo acordado.": "Explain why the delivery does not meet the agreement.",
  "No tienes permiso para rechazar la entrega de este trabajo.": "You do not have permission to reject this job’s delivery.",
  "Solo puedes rechazar una entrega que el profesional haya marcado como entregada.": "You can only reject a delivery that the professional has marked as delivered.",
  "No se pudo conectar": "Could not connect",
  "Disputa no encontrada": "Dispute not found",
  "Escribe la justificación de la resolución.": "Explain the reasons for the decision.",
  "Este expediente contiene un contracargo bancario. Debe conciliarse primero en Stripe.": "This case includes a bank chargeback. It must first be reconciled in Stripe.",
  "La disputa fue retirada.": "The dispute has been withdrawn.",
  "La disputa no admite esta resolución.": "This resolution is not available for the dispute.",
  "Introduce un reembolso válido.": "Enter a valid refund amount.",
  "Indica tu DNI/NIE como representante": "Enter your DNI/NIE as the representative",
  "Indica el nombre y CIF de la empresa o utiliza una invitación": "Enter the company’s name and tax ID (CIF), or use an invitation",
  "No se ha podido vincular la empresa": "The company could not be linked",
  "Conexión con la base de datos no disponible.": "The database connection is unavailable.",
  "La configuración segura del servidor no está disponible.": "The secure server configuration is unavailable.",
  "Trabajo no encontrado": "Job not found",
  "Solo el cliente puede realizar el pago": "Only the client can make the payment",
  "Este trabajo ya ha sido pagado": "This job has already been paid for",
  "El trabajo no está vinculado a una oferta y una solicitud válidas.": "The job is not linked to a valid offer and request.",
  "No se pudieron verificar los términos originales de la contratación.": "The original terms of the agreement could not be verified.",
  "Los participantes o documentos de la contratación no coinciden. No se realizará ningún cargo.": "The participants or documents do not match the agreement. You will not be charged.",
  "La oferta o la solicitud ya no están disponibles para completar este pago.": "The offer or request is no longer available to complete this payment.",
  "El precio de la oferta no es válido.": "The offer price is invalid.",
  "El precio del trabajo no coincide con la oferta aceptada. No se realizará ningún cargo.": "The job price does not match the accepted offer. You will not be charged.",
  "Este profesional aún no ha terminado de configurar su cuenta de cobros. No se realizará ningún cargo.": "This professional has not finished setting up their payout account. You will not be charged.",
  "No se pudieron verificar los gastos de servicio aceptados por el profesional. No se realizará ningún cargo.": "The service fees accepted by the professional could not be verified. You will not be charged.",
  "No se pudo comprobar si ya había un pago preparado.": "We could not check whether a payment had already been prepared.",
  "El intento de pago anterior tiene un desglose incoherente. No se realizará ningún cargo.": "The previous payment attempt has an inconsistent breakdown. You will not be charged.",
  "Este trabajo ya tiene un pago completado. Estamos conciliándolo con Stripe.": "A payment has already been completed for this job. We are reconciling it with Stripe.",
  "Este pago está siendo procesado por Stripe. Espera a que termine la conciliación antes de intentarlo de nuevo.": "Stripe is processing this payment. Wait for reconciliation to finish before trying again.",
  "No se pudo conciliar el desglose del intento de pago anterior.": "The breakdown of the previous payment attempt could not be reconciled.",
  "No se pudo cerrar de forma segura el intento de pago anterior.": "The previous payment attempt could not be closed safely.",
  "Este pago llegó después del cierre del intento. Se ha reembolsado íntegramente y el servicio no se ha reactivado.": "This payment arrived after the attempt was closed. It has been fully refunded and the service has not been reactivated.",
  "No se encontró un único pago retenido para confirmar.": "A single held payment could not be found to confirm.",
  "La tabla de incidencias aún no está creada. Ejecuta el script 027.": "The issues table has not been created yet. Run script 027.",
  "No tienes permiso para ver incidencias": "You do not have permission to view reported issues",
  "No tienes permiso": "You do not have permission",
  "Solicitud no encontrada": "Request not found",
  "Solo el cliente puede avisar de su demanda abierta": "Only the client can send alerts about their open request",
  "No se pudo preparar el envío de avisos": "The notifications could not be prepared",
  "No tienes acceso a esta conversación": "You do not have access to this conversation",
  "La conversación está bloqueada.": "This conversation is blocked.",
  "No puedes enviar mensajes a este usuario.": "You cannot send messages to this user.",
  "Demanda no válida": "Invalid request",
  "Trabajo no válido": "Invalid job",
  "No puedes iniciar una conversación contigo mismo.": "You cannot start a conversation with yourself.",
  "Para escribir a un cliente, abre el chat desde una de sus demandas.": "To message a client, open the chat from one of their requests.",
  "El trabajo ya no está disponible.": "This job is no longer available.",
  "Este trabajo no corresponde a la conversación.": "This job does not belong to this conversation.",
  "La demanda no corresponde a este trabajo.": "This request does not belong to this job.",
  "La demanda ya no está disponible.": "This request is no longer available.",
  "Esta demanda ya no admite nuevos contactos.": "This request no longer accepts new contacts.",
  "La demanda no corresponde a esta conversación.": "This request does not belong to this conversation.",
  "Para poder escribir desde una demanda, primero crea tu perfil profesional en Mi perfil.": "To message someone from a request, first create your professional profile in My profile.",
  "No puedes iniciar una conversación con este usuario.": "You cannot start a conversation with this user.",
  "No se pudo vincular el chat con esta demanda.": "The chat could not be linked to this request.",
  "No tienes permiso para iniciar conversaciones administrativas": "You do not have permission to start administrative conversations",
  "El usuario ya no está disponible": "This user is no longer available",
  "No se pudo localizar al equipo de soporte.": "The support team could not be found.",
  "No hay ningún perfil de soporte disponible.": "No support profile is available.",
  "Preferencias no válidas": "Invalid preferences",
  "No autenticado. Por favor inicia sesión.": "You are not signed in. Please sign in.",
  "Debes crear un perfil profesional antes de enviar ofertas. Ve a 'Mi Perfil' para configurarlo.": "You must create a professional profile before sending offers. Go to ‘My profile’ to set it up.",
  "No puedes enviar una oferta a tu propia demanda.": "You cannot send an offer for your own request.",
  "Esta demanda ya no admite nuevas ofertas.": "This request no longer accepts new offers.",
  "El precio propuesto debe ser mayor que 0.": "The proposed price must be greater than 0.",
  "La unidad de tiempo de la oferta no es válida.": "The offer’s time unit is invalid.",
  "El tiempo estimado debe ser mayor que 0.": "The estimated time must be greater than 0.",
  "Debes aceptar los gastos de servicio de la plataforma para enviar la oferta.": "You must accept the platform’s service fees to send the offer.",
  "Ya has enviado una oferta para esta solicitud.": "You have already sent an offer for this request.",
  "No se pudo consultar el estado de tus contratos. Inténtalo de nuevo.": "The status of your contracts could not be checked. Please try again.",
  "No tienes permiso para editar esta oferta.": "You do not have permission to edit this offer.",
  "No puedes editar una oferta que ya ha sido aceptada.": "You cannot edit an offer that has already been accepted.",
  "Debes revisar y aceptar los gastos de servicio de esta oferta antes de guardarla.": "You must review and accept this offer’s service fees before saving it.",
  "No se pudieron verificar los gastos de servicio aceptados en esta oferta.": "The service fees accepted for this offer could not be verified.",
  "No tienes permiso para eliminar esta oferta.": "You do not have permission to delete this offer.",
  "No puedes eliminar una oferta que ya ha sido aceptada.": "You cannot delete an offer that has already been accepted.",
  "Esta oferta ya está cerrada.": "This offer is already closed.",
  "La oferta ha cambiado. Actualiza la página e inténtalo de nuevo.": "The offer has changed. Refresh the page and try again.",
  "La puja ya no está marcada como perdida. Actualiza la página e inténtalo de nuevo.": "The bid is no longer marked as lost. Refresh the page and try again.",
  "Oferta no encontrada": "Offer not found",
  "No tienes permiso para aceptar esta oferta": "You do not have permission to accept this offer",
  "Oferta no encontrada.": "Offer not found.",
  "No tienes permiso para rechazar esta oferta.": "You do not have permission to reject this offer.",
  "Esta oferta ya no está pendiente de respuesta.": "This offer is no longer awaiting a response.",
  "Solo puedes retirar una oferta pendiente desde esta acción.": "This action can only withdraw a pending offer.",
  "La oferta ya no se puede retirar. Si está contratada, solicita la cancelación del trabajo.": "The offer can no longer be withdrawn. If it has been contracted, request cancellation of the job.",
  "Supabase no está configurado.": "Supabase is not configured.",
  "No tienes permiso para acceder a operaciones.": "You do not have permission to access operations.",
  "Supabase service role no está configurado.": "The Supabase service role is not configured.",
  "Completa título y descripción.": "Complete the title and description.",
  "Ese trabajo no está disponible para el portfolio.": "That job is not available for the portfolio.",
  "No autorizado": "Not authorised",
  "Elige al menos una categoría de servicio para recibir demandas.": "Choose at least one service category to receive requests.",
  "Elige al menos una provincia en la que quieras cubrir demandas.": "Choose at least one province where you want to receive requests.",
  "Guarda juntos el presupuesto mínimo y el máximo.": "Save the minimum and maximum budget together.",
  "El presupuesto mínimo de los avisos no puede superar el máximo.": "The minimum alert budget cannot exceed the maximum.",
  "Token de notificaciones inválido": "Invalid notification token",
  "Este dispositivo todavía no está registrado. Pulsa primero Activar.": "This device is not registered yet. Press Enable first.",
  "No tienes permiso para dejar una resena en este trabajo": "You do not have permission to review this job",
  "Solo puedes dejar resena en trabajos completados": "You can only review completed jobs",
  "Ya has dejado una resena para este trabajo": "You have already reviewed this job",
  "Ya has valorado todos los trabajos completados con este profesional.": "You have already reviewed all your completed jobs with this professional.",
  "Solo puedes valorar a un profesional cuando hayáis completado un trabajo juntos.": "You can only review a professional after completing a job together.",
  "El servidor no está configurado correctamente. Falta la conexión con Supabase.": "The server is not configured correctly. The Supabase connection is missing.",
  "No autenticado. Por favor inicia sesión para publicar un proyecto.": "You are not signed in. Please sign in to post a project.",
  "Selecciona una categoría válida.": "Select a valid category.",
  "El presupuesto debe usar importes no negativos y el mínimo no puede superar el máximo.": "Budget amounts must be non-negative and the minimum cannot exceed the maximum.",
  "La fecha necesaria debe ser una fecha válida que no esté en el pasado.": "The required date must be a valid date that is not in the past.",
  "No tienes permiso para editar esta demanda.": "You do not have permission to edit this request.",
  "Solo puedes editar demandas que sigan abiertas (sin ofertas aceptadas).": "You can only edit requests that are still open (with no accepted offers).",
  "No puedes editar esta demanda mientras tenga una oferta aceptada o un trabajo activo.": "You cannot edit this request while it has an accepted offer or an active job.",
  "No se pudo guardar la categoría seleccionada.": "The selected category could not be saved.",
  "No tienes permiso para borrar esta demanda.": "You do not have permission to delete this request.",
  "No puedes borrar una demanda con un trabajo en curso.": "You cannot delete a request with a job in progress.",
  "Tu perfil de cobros ha cambiado. Actualiza el estado para volver a comprobarlo.": "Your payout profile has changed. Refresh the status to check it again.",
  "No se pudieron verificar los datos de tu empresa.": "Your company details could not be verified.",
  "Completa primero el alta de cobros.": "Complete payout registration first.",
  "No se pudo confirmar la contratación. Inténtalo de nuevo.": "The agreement could not be confirmed. Please try again.",
  "Usa la acción de entrega, confirmación, cancelación o disputa correspondiente al trabajo.": "Use the appropriate delivery, confirmation, cancellation or dispute action for this job.",
  "Los archivos adjuntos no son válidos.": "The attachments are invalid.",
  "Hay un archivo adjunto no válido.": "One of the attachments is invalid.",
  "No tienes permiso sobre este trabajo": "You do not have permission for this job",
  "Este trabajo ya no admite cancelación de mutuo acuerdo (usa la disputa si hay un problema).": "This job can no longer be cancelled by mutual agreement (open a dispute if there is a problem).",
  "Ya hay una solicitud de cancelación pendiente para este trabajo.": "There is already a pending cancellation request for this job.",
  "Explica por qué quieres cancelar el servicio.": "Explain why you want to cancel the service.",
  "Esta solicitud ya no está pendiente y no se puede editar.": "This request is no longer pending and cannot be edited.",
  "Solo quien solicitó la cancelación puede editarla.": "Only the person who requested cancellation can edit it.",
  "La solicitud ya ha sido respondida y no se puede editar.": "This request has already been answered and cannot be edited.",
  "Esta solicitud ya no está pendiente y no se puede retirar.": "This request is no longer pending and cannot be withdrawn.",
  "Solo quien solicitó la cancelación puede retirarla.": "Only the person who requested cancellation can withdraw it.",
  "La solicitud ya ha sido respondida y no se puede retirar.": "This request has already been answered and cannot be withdrawn.",
  "No hay ninguna solicitud de cancelación pendiente.": "There is no pending cancellation request.",
  "Tú solicitaste la cancelación; debe responder la otra parte.": "You requested the cancellation; the other party must respond.",
  "Explica por qué te opones a la cancelación para que el equipo de Diime pueda decidir.": "Explain why you oppose cancellation so that the Diime team can decide.",
  "El progreso debe ser un número entero entre 0 y 100.": "Progress must be a whole number between 0 and 100.",
  "No tienes permiso para actualizar este trabajo": "You do not have permission to update this job",
  "Solo puedes actualizar el progreso de un trabajo pagado y en curso, sin cancelación pendiente.": "You can only update progress on a paid job in progress with no pending cancellation.",
  "Solo se puede entregar un trabajo que esté en progreso.": "Only a job in progress can be delivered.",
  "Hay una cancelación pendiente. Debe resolverse antes de entregar el trabajo.": "A cancellation is pending. It must be resolved before delivering the work.",
  "El estado del trabajo ha cambiado. Actualiza la página antes de continuar.": "The job’s status has changed. Refresh the page before continuing.",
  "No se pudo cargar tu verificación. Inténtalo de nuevo.": "Your verification could not be loaded. Please try again.",
  "Primero completa tu perfil profesional.": "Complete your professional profile first.",
  "No se pudo comprobar la empresa de tu perfil.": "The company on your profile could not be checked.",
  "El mensaje debe tener como máximo 2.000 caracteres.": "The message must contain no more than 2,000 characters.",
  "No se pudo registrar tu solicitud. Inténtalo de nuevo.": "Your request could not be registered. Please try again.",
  "No se pudieron cargar las solicitudes de verificación.": "The verification requests could not be loaded.",
  "No se pudieron cargar los datos de contacto de los proveedores.": "The providers’ contact details could not be loaded.",
  "El proveedor no es válido.": "The provider is invalid.",
  "No se pudo cargar el historial de la verificación.": "The verification history could not be loaded.",
  "La revisión no es válida.": "The review is invalid.",
  "Actualiza la solicitud antes de tomar una decisión.": "Refresh the request before making a decision.",
  "Los comentarios no son válidos.": "The comments are invalid.",
  "El comentario supera el límite de caracteres.": "The comment exceeds the character limit.",
  "Indica al proveedor el motivo para que pueda revisarlo.": "Tell the provider the reason so that they can address it.",
  "No se pudo comprobar el estado de la solicitud.": "The request’s status could not be checked.",
  "No se pudo guardar la revisión.": "The review could not be saved.",
  "No tienes permiso para acceder al panel de disputas": "You do not have permission to access the disputes panel",
  "No se pudo abrir la disputa.": "The dispute could not be opened.",
  "No se ha podido retirar la disputa.": "The dispute could not be withdrawn.",
  "No se pudo resolver la disputa. El reparto iniciado se conserva para reintentarlo.": "The dispute could not be resolved. The settlement already started is preserved so you can retry.",
  "No se pudo preparar el pago.": "The payment could not be prepared.",
  "El intento de pago fue sustituido. Vuelve a intentarlo.": "The payment attempt was replaced. Please try again.",
  "No se pudo conciliar el pago.": "The payment could not be reconciled.",
  "No se pudo completar la liquidación.": "The settlement could not be completed.",
  "No se pudo conciliar la cancelación. Puedes reintentar sin duplicar el reembolso.": "The cancellation could not be reconciled. You can retry without duplicating the refund.",
  "No se ha podido retirar la incidencia.": "The reported issue could not be withdrawn.",
  "No se pudo obtener el estado operativo.": "The operational status could not be retrieved.",
  ", ": ", ",
  "Apple o Google no aceptaron la notificación de prueba.": "Apple or Google did not accept the test notification.",
  "Necesitas un perfil profesional antes de configurar cobros.": "You need a professional profile before setting up payouts.",
  "No se pudo preparar la conexión segura de cobros.": "The secure payout connection could not be prepared.",
  "No se pudo consultar la cuenta de cobros.": "The payout account could not be retrieved.",
  "No se pudo iniciar el alta de cobros con Stripe.": "Payout registration with Stripe could not be started.",
  "No se pudo abrir el panel de cobros.": "The payout dashboard could not be opened.",
  "No se pudo conciliar el pago y abrir la disputa. Puedes reintentar.": "The payment could not be reconciled and the dispute could not be opened. You can retry.",
  "No se puede conectar con Diime. Inténtalo de nuevo.": "Could not connect to Diime. Please try again.",
  "Inicia sesión para continuar.": "Sign in to continue.",
  "No tienes permiso para gestionar verificaciones.": "You do not have permission to manage verifications.",
  "La liquidación anterior requiere conciliar su decisión antes de continuar.": "The previous settlement requires its decision to be reconciled before continuing.",
  "El pago aún no se ha completado.": "The payment has not been completed yet.",
  "No se encontró el pago preparado.": "The prepared payment could not be found.",
  "No tienes permiso para confirmar este pago.": "You do not have permission to confirm this payment.",
  "La sesión de Stripe no coincide con el contrato.": "The Stripe session does not match the contract.",
  "Stripe no ha devuelto el identificador del pago.": "Stripe did not return the payment ID.",
  "El cargo no está capturado y conciliado con Stripe.": "The charge has not been captured and reconciled with Stripe.",
  "Stripe aún está procesando este pago. La operación queda bloqueada para conciliarlo; vuelve a intentarlo cuando termine.": "Stripe is still processing this payment. The operation is blocked for reconciliation; try again once it is complete.",
  "El reparto económico no cuadra con el precio original.": "The settlement breakdown does not match the original price.",
  "consulta fallida": "query failed",
  "RESEND_API_KEY no está configurado.": "RESEND_API_KEY is not configured.",
  "Stripe contiene movimientos duplicados para esta liquidación; requiere conciliación.": "Stripe contains duplicate transactions for this settlement; reconciliation is required.",
  "No se pudo recorrer el historial completo de Stripe.": "The full Stripe history could not be retrieved.",
  "El historial de Stripe requiere una conciliación adicional antes de repetir movimientos.": "The Stripe history requires further reconciliation before repeating transactions.",
  "La liquidación necesita una clave idempotente estable.": "The settlement needs a stable idempotency key.",
  "El PaymentIntent de Stripe no coincide con un pago EUR capturado y conciliado.": "The Stripe PaymentIntent does not match a captured and reconciled EUR payment.",
  "El total cobrado en Stripe no coincide con el reparto guardado.": "The total charged in Stripe does not match the saved breakdown.",
  "El cargo tiene un contracargo bancario; requiere conciliación en Stripe antes de mover fondos.": "The charge has a bank chargeback; reconciliation in Stripe is required before moving funds.",
  "El reembolso existente en Stripe no coincide con el reparto fijado.": "The existing refund in Stripe does not match the agreed settlement breakdown.",
  "El reembolso sigue pendiente en Stripe; aún no se ha transferido nada al profesional.": "The refund is still pending in Stripe; no money has been transferred to the professional yet.",
  "El cargo recibió un contracargo; no se ha emitido la transferencia.": "The charge received a chargeback; the transfer has not been issued.",
  "El profesional no tiene una cuenta Stripe Connect preparada para recibir el pago.": "The professional does not have a Stripe Connect account ready to receive payment.",
  "Stripe no ha devuelto el cargo asociado al pago; no se puede transferir de forma segura.": "Stripe did not return the charge associated with the payment; a safe transfer cannot be made.",
  "La transferencia existente en Stripe no coincide con el reparto fijado.": "The existing transfer in Stripe does not match the agreed settlement breakdown.",
  "La clave privada de Stripe no está configurada. Los pagos no están disponibles.": "The Stripe private key is not configured. Payments are unavailable.",
  "Upload failed": "Upload failed",
  "No se puede iniciar una conversación entre estos usuarios.": "A conversation cannot be started between these users.",
  "No se pueden enviar mensajes entre estos usuarios.": "Messages cannot be sent between these users.",
  "Token push inválido": "Invalid push notification token",
  "Plataforma push inválida": "Invalid push notification platform",
  "No puedes crear un perfil verificado o administrador": "You cannot create a verified or administrator profile",
  "Solo un administrador puede modificar la verificación o el rol administrativo": "Only an administrator can change verification or the administrator role",
  "El estado de verificación no puede estar vacío": "Verification status cannot be empty",
  "No se pueden modificar o eliminar los términos de una oferta vinculada a un trabajo": "The terms of an offer linked to a job cannot be changed or deleted",
  "No se pueden modificar o eliminar los términos de una solicitud vinculada a un trabajo": "The terms of a request linked to a job cannot be changed or deleted",
  "No se puede abrir una conversación con uno mismo": "You cannot start a conversation with yourself",
  "Uno de los usuarios ya no está disponible": "One of the users is no longer available",
  "No se pueden cambiar los participantes de una conversación": "The participants in a conversation cannot be changed",
  "No perteneces a esta conversación": "You are not a participant in this conversation",
  "Para contactar a un cliente hace falta una demanda o trabajo": "A request or job is required to contact a client",
  "El trabajo no corresponde a los participantes del chat": "The job does not belong to the chat participants",
  "La demanda no corresponde al trabajo del chat": "The request does not match the job in this chat",
  "La demanda no corresponde a los participantes del chat": "The request does not belong to the chat participants",
  "La demanda ya no admite nuevos contactos": "The request no longer allows new contacts",
  "La otra parte de una demanda debe ser un proveedor": "The other party to a request must be a provider",
  "Conversación no disponible": "Conversation unavailable",
  "El trabajo no corresponde a la conversación": "The job does not match the conversation",
  "La demanda no corresponde al trabajo": "The request does not match the job",
  "La demanda no corresponde a la conversación": "The request does not match the conversation",
  "La comisión original del profesional es inmutable": "The professional's original commission cannot be changed",
  "No se puede cambiar un reparto después de iniciar su liquidación": "The allocation of funds cannot be changed once settlement has started",
  "Ya existe un escrow abierto para este trabajo": "An open protected payment already exists for this job",
  "Solo el profesional puede volver a abrir su oferta": "Only the professional can reopen their offer",
  "No se puede cambiar la tarifa de una oferta vinculada a un trabajo": "The fee for an offer linked to a job cannot be changed",
  "La oferta tiene historial contractual; crea una oferta nueva para aceptar los gastos vigentes": "This offer has a contract history; create a new offer to accept the current fees",
  "Solo el destinatario puede marcar el mensaje como leído": "Only the recipient can mark the message as read",
  "Los datos de cobros solo los configura el servidor": "Payout details can only be configured by the server",
  "Para vincular una empresa debes usar una invitación válida o crear tu propia empresa": "To link a company, you must use a valid invitation or create your own company",
  "Confirma tu correo antes de vincular una empresa": "Confirm your email before linking a company",
  "Indica el DNI/NIE de la persona que representa a la empresa": "Enter the DNI/NIE of the person representing the company",
  "Completa primero tu perfil personal": "Complete your personal profile first",
  "Token de invitación inválido": "Invalid invitation token",
  "Indica el nombre y CIF de tu empresa": "Enter your company name and Spanish tax ID (CIF)",
  "Ya perteneces a una empresa": "You already belong to a company",
  "Ya perteneces a otra empresa. Contacta con soporte para cambiar la representación": "You already belong to another company. Contact support to change the company you represent",
  "Solo el servidor puede sincronizar Stripe": "Only the server can synchronise Stripe",
  "Estado de Stripe no válido": "Invalid Stripe status",
  "El trabajo no admite preparar un pago en este momento": "A payment cannot be prepared for this job at this time",
  "El destino y la decisión de una liquidación ya iniciada son inmutables": "The destination and decision for a settlement that has already started cannot be changed",
  "Intento no encontrado": "Attempt not found",
  "Sin permiso": "Permission denied",
  "La cancelación ya no admite esta respuesta": "This response to the cancellation is no longer allowed",
  "El trabajo ya no admite abrir una disputa": "A dispute can no longer be opened for this job",
  "La cancelación ya no admite rechazo": "The cancellation can no longer be rejected",
  "Sin pago, solicita primero una cancelación": "If no payment has been made, request a cancellation first",
  "Pago preparado no encontrado": "Prepared payment not found",
  "Stripe no coincide con el pago preparado": "Stripe does not match the prepared payment",
  "Sin permiso o motivo": "Permission or reason missing",
  "La cancelación ya está aceptada": "The cancellation has already been accepted",
  "Ya existe una disputa abierta": "An open dispute already exists",
  "El trabajo ya no admite disputas": "This job no longer allows disputes",
  "La cancelación ya no está pendiente": "The cancellation is no longer pending",
  "Hay un pago pendiente de conciliar o una liquidación en curso": "A payment is awaiting reconciliation or a settlement is in progress",
  "Hay pagos históricos duplicados que requieren conciliación": "Duplicate historical payments require reconciliation",
  "El pago ya tiene una operación en curso": "An operation is already in progress for this payment",
  "No se encontró el pago cobrado; requiere conciliación": "The collected payment was not found; reconciliation is required",
  "El trabajo ya cambió de estado": "The job's status has already changed",
  "Pago no encontrado": "Payment not found",
  "Solo el cliente confirma": "Only the client can confirm",
  "La cancelación no está aceptada": "The cancellation has not been accepted",
  "Solo administración resuelve": "Only administrators can resolve this",
  "La disputa no corresponde a este pago o es un contracargo": "The dispute does not match this payment or is a chargeback",
  "No es un pago tardío": "This is not a late payment",
  "Operación no válida": "Invalid operation",
  "Contracargo bancario: concilia primero en Stripe": "Bank chargeback: reconcile in Stripe first",
  "Existe otra liquidación iniciada": "Another settlement has already started",
  "La decisión económica ya quedó fijada": "The financial decision has already been finalised",
  "El reparto anterior no coincide": "The previous allocation of funds does not match",
  "Importes o cobro sin conciliar": "Amounts or collected payment have not been reconciled",
  "El trabajo no admite liberar fondos": "Funds cannot be released for this job",
  "El trabajo no admite reembolso por cancelación": "This job does not allow a cancellation refund",
  "La disputa ya no admite liquidación": "The dispute can no longer be settled",
  "Reembolso no válido": "Invalid refund",
  "Reparto incoherente": "Inconsistent allocation of funds",
  "El profesional no tiene una cuenta de cobros habilitada": "The professional does not have an enabled payout account",
  "Cancelación no aceptada": "Cancellation not accepted",
  "Queda un pago por conciliar": "A payment still needs to be reconciled",
  "La liquidación no tiene una decisión fijada": "No decision has been finalised for this settlement",
  "Contracargo recibido: concilia los movimientos antes de cerrar": "Chargeback received: reconcile the transactions before closing",
  "Faltan movimientos confirmados de Stripe": "Confirmed Stripe transactions are missing",
  "El trabajo ya no admite confirmar": "This job can no longer be confirmed",
  "La disputa ya no admite este cierre": "The dispute no longer allows this closure",
  "Tipo de cierre no válido": "Invalid closure type",
  "No es una mediación sin pago conciliada": "This is not a reconciled mediation without payment",
  "Resolución sin pago no válida": "Invalid resolution without payment",
  "Contracargo sin pago conciliado": "Chargeback without a reconciled payment",
  "Los contratos se crean y cancelan mediante su flujo autorizado": "Contracts must be created and cancelled through their authorised process",
  "No se pueden modificar los participantes, términos o datos de pago del contrato": "The participants, terms or payment details of the contract cannot be changed",
  "Solo el proveedor puede actualizar la planificación con fechas y horas válidas": "Only the provider can update the schedule, using valid dates and times",
  "La reseña debe corresponder al cliente y al trabajo completado": "The review must match the client and the completed job",
  "La cancelación ya se está resolviendo o el trabajo no admite cancelación": "The cancellation is already being resolved or the job cannot be cancelled",
  "La respuesta a una cancelación debe tramitarse por su flujo autorizado": "The response to a cancellation must be submitted through its authorised process",
  "Retirar la cancelación requiere limpiar sus argumentos y pruebas": "Withdrawing the cancellation requires clearing its reasons and evidence",
  "No puedes responder ni cambiar el autor de tu propia cancelación": "You cannot respond to your own cancellation request or change its author",
  "La solicitud de cancelación no es válida": "The cancellation request is invalid",
  "Explica por qué quieres cancelar el servicio": "Explain why you want to cancel the service",
  "Solo el proveedor puede avanzar o entregar un trabajo pagado y en curso": "Only the provider can update progress or deliver a paid job that is in progress",
  "El progreso debe estar entre 0 y 100": "Progress must be between 0 and 100",
  "La finalización, cancelación y disputa requieren su flujo de pago autorizado": "Completion, cancellation and disputes require their authorised payment process",
  "La fecha de entrega solo se registra al entregar el trabajo": "The delivery date is recorded only when the work is delivered",
  "El contrato no coincide con la oferta, la demanda y sus participantes": "The contract does not match the offer, request and participants",
  "La oferta o la demanda ya no permiten crear este contrato": "The offer or request no longer allows this contract to be created",
  "Esta demanda ya tiene un contrato. Cancélalo y espera su cierre antes de elegir otra oferta": "This request already has a contract. Cancel it and wait for it to close before choosing another offer",
  "Una de las cuentas ya está dada de baja y no admite nuevas contrataciones": "One of the accounts has been closed and cannot enter into new contracts",
  "No tienes permiso para aceptar ofertas de esta demanda": "You do not have permission to accept offers for this request",
  "La oferta no corresponde a esta demanda y proveedor": "The offer does not match this request and provider",
  "Esta demanda tiene contratos históricos duplicados. Contacta con Diime para revisarlos antes de continuar": "This request has duplicate historical contracts. Contact Diime to review them before continuing",
  "El proveedor debe confirmar los gastos de servicio de esta oferta antes de contratar": "The provider must confirm this offer's service fees before a contract can be created",
  "Ya hay una oferta contratada. Cancela ese contrato y espera su cierre antes de elegir otra": "An offer is already under contract. Cancel that contract and wait for it to close before choosing another",
  "Esta oferta ya no está disponible para contratar": "This offer can no longer be accepted for a contract",
  "La oferta contiene un importe o un plazo no válido": "The offer contains an invalid amount or timeframe",
  "La fecha estimada debe ser futura": "The estimated date must be in the future",
  "No se puede eliminar una oferta contratada o de otro proveedor": "You cannot delete an offer that is under contract or belongs to another provider",
  "No se puede trasladar una oferta a otra demanda o proveedor": "An offer cannot be moved to another request or provider",
  "La demanda no está disponible": "The request is unavailable",
  "La cuenta está dada de baja y no puede enviar ofertas": "The account has been closed and cannot send offers",
  "Solo el proveedor puede enviar una oferta a una demanda abierta ajena": "Only the provider can send an offer for another user's open request",
  "El cliente solo puede rechazar una oferta pendiente; aceptar requiere crear su contrato": "The client can only reject a pending offer; accepting it requires creating its contract",
  "Una oferta contratada requiere el flujo de cancelación del trabajo": "An offer that is under contract requires the job cancellation process",
  "Este cambio de estado de oferta no está permitido": "This offer status change is not allowed",
  "Esta demanda ya no admite cambios en sus ofertas": "This request no longer allows changes to its offers",
  "Conserva la oferta contratada en el historial y envía una nueva": "Keep the contracted offer in the history and submit a new one",
  "No tienes permiso sobre esta oferta": "You do not have permission to access this offer",
  "El precio y el plazo de la oferta deben ser válidos y positivos": "The offer's price and timeframe must be valid and positive",
  "La cuenta está dada de baja y no puede publicar demandas": "The account has been closed and cannot post requests",
  "Solo puedes publicar demandas abiertas a tu nombre": "You can only post open requests in your own name",
  "No tienes permiso sobre esta demanda": "You do not have permission to access this request",
  "La demanda forma parte de un historial contractual y debe conservarse": "The request is part of a contract history and must be retained",
  "No se puede cambiar el propietario de una demanda": "The owner of a request cannot be changed",
  "El estado de una demanda contratada lo determina su trabajo y pago": "The status of a request under contract is determined by its job and payment",
  "La baja de la cuenta solo puede tramitarse desde su proceso autorizado": "Account deletion can only be completed through its authorised process",
  "Finaliza o cancela tus contratos y espera a que sus pagos y disputas queden resueltos antes de darte de baja.": "Complete or cancel your contracts and wait for their payments and disputes to be resolved before deleting your account.",
  "Para cambiar la verificación debes usar el expediente de revisión": "To change verification, you must use the review case",
  "Solo un administrador puede modificar el rol administrativo": "Only an administrator can change the administrator role",
  "Inicia sesión y confirma tu correo para solicitar la verificación": "Sign in and confirm your email to request verification",
  "El mensaje no puede superar 2000 caracteres": "The message cannot exceed 2,000 characters",
  "Completa tu perfil profesional antes de solicitar la verificación": "Complete your professional profile before requesting verification",
  "Tu perfil ya está verificado": "Your profile is already verified",
  "Solo un administrador puede revisar la verificación": "Only an administrator can review verification",
  "Estado de revisión no válido": "Invalid review status",
  "La operación antigua solo permite conservar o retirar una insignia": "The legacy operation only allows a badge to be retained or withdrawn",
  "El comentario público admite 2000 caracteres y la nota interna 4000": "The public comment allows 2,000 characters and the internal note 4,000",
  "Indica un motivo público para no aprobar o retirar la verificación": "Provide a public reason for declining or withdrawing verification",
  "No se encontró el perfil profesional": "The professional profile was not found",
  "La solicitud ha cambiado. Actualiza la lista y revisa el expediente vigente": "The request has changed. Refresh the list and review the current case",
  "Para aprobar la verificación, abre y revisa el expediente vigente": "To approve verification, open and review the current case",
  "El profesional debe enviar una solicitud de verificación vigente": "The professional must submit a current verification request",
  "Ha cambiado la empresa. El profesional debe enviar una nueva solicitud": "The company has changed. The professional must submit a new request",
  "La insignia y el expediente no coinciden; revisa el historial": "The badge and review case do not match; check the history",
  "Esta solicitud está cerrada; el profesional debe volver a solicitar la verificación": "This request is closed; the professional must request verification again",
  "El estado de verificación es obligatorio": "Verification status is required",
  "la solicitud parece pedir la compra, venta, fabricación o transporte de drogas ilegales": "the request appears to seek the purchase, sale, manufacture or transport of illegal drugs",
  "No se puede publicar: la solicitud parece pedir la compra, venta, fabricación o transporte de drogas ilegales.": "Cannot publish: the request appears to seek the purchase, sale, manufacture or transport of illegal drugs.",
  "No se puede publicar: la solicitud parece pedir la compra, venta, fabricación o transporte de drogas ilegales. Si se trata de un servicio legítimo, explica claramente su finalidad y las autorizaciones aplicables.": "Cannot publish: the request appears to seek the purchase, sale, manufacture or transport of illegal drugs. If this is a legitimate service, clearly explain its purpose and the applicable authorisations.",
  "la solicitud parece encargar violencia, amenazas o daño contra una persona": "the request appears to commission violence, threats or harm against a person",
  "No se puede publicar: la solicitud parece encargar violencia, amenazas o daño contra una persona.": "Cannot publish: the request appears to commission violence, threats or harm against a person.",
  "No se puede publicar: la solicitud parece encargar violencia, amenazas o daño contra una persona. Si se trata de un servicio legítimo, explica claramente su finalidad y las autorizaciones aplicables.": "Cannot publish: the request appears to commission violence, threats or harm against a person. If this is a legitimate service, clearly explain its purpose and the applicable authorisations.",
  "la solicitud parece implicar explotación sexual o contenido sexual de menores": "the request appears to involve sexual exploitation or sexual content involving minors",
  "No se puede publicar: la solicitud parece implicar explotación sexual o contenido sexual de menores.": "Cannot publish: the request appears to involve sexual exploitation or sexual content involving minors.",
  "No se puede publicar: la solicitud parece implicar explotación sexual o contenido sexual de menores. Si se trata de un servicio legítimo, explica claramente su finalidad y las autorizaciones aplicables.": "Cannot publish: the request appears to involve sexual exploitation or sexual content involving minors. If this is a legitimate service, clearly explain its purpose and the applicable authorisations.",
  "la solicitud parece ofrecer o pedir servicios o contenido sexual explícito": "the request appears to offer or seek sexually explicit services or content",
  "No se puede publicar: la solicitud parece ofrecer o pedir servicios o contenido sexual explícito.": "Cannot publish: the request appears to offer or seek sexually explicit services or content.",
  "No se puede publicar: la solicitud parece ofrecer o pedir servicios o contenido sexual explícito. Si se trata de un servicio legítimo, explica claramente su finalidad y las autorizaciones aplicables.": "Cannot publish: the request appears to offer or seek sexually explicit services or content. If this is a legitimate service, clearly explain its purpose and the applicable authorisations.",
  "la solicitud parece pedir armas ilegales o la fabricación de explosivos": "the request appears to seek illegal weapons or the manufacture of explosives",
  "No se puede publicar: la solicitud parece pedir armas ilegales o la fabricación de explosivos.": "Cannot publish: the request appears to seek illegal weapons or the manufacture of explosives.",
  "No se puede publicar: la solicitud parece pedir armas ilegales o la fabricación de explosivos. Si se trata de un servicio legítimo, explica claramente su finalidad y las autorizaciones aplicables.": "Cannot publish: the request appears to seek illegal weapons or the manufacture of explosives. If this is a legitimate service, clearly explain its purpose and the applicable authorisations.",
  "la solicitud parece pedir falsificación documental o fraude económico": "the request appears to seek document forgery or financial fraud",
  "No se puede publicar: la solicitud parece pedir falsificación documental o fraude económico.": "Cannot publish: the request appears to seek document forgery or financial fraud.",
  "No se puede publicar: la solicitud parece pedir falsificación documental o fraude económico. Si se trata de un servicio legítimo, explica claramente su finalidad y las autorizaciones aplicables.": "Cannot publish: the request appears to seek document forgery or financial fraud. If this is a legitimate service, clearly explain its purpose and the applicable authorisations.",
  "la solicitud parece pedir acceso informático no autorizado o software malicioso": "the request appears to seek unauthorised computer access or malicious software",
  "No se puede publicar: la solicitud parece pedir acceso informático no autorizado o software malicioso.": "Cannot publish: the request appears to seek unauthorised computer access or malicious software.",
  "No se puede publicar: la solicitud parece pedir acceso informático no autorizado o software malicioso. Si se trata de un servicio legítimo, explica claramente su finalidad y las autorizaciones aplicables.": "Cannot publish: the request appears to seek unauthorised computer access or malicious software. If this is a legitimate service, clearly explain its purpose and the applicable authorisations.",
  "la solicitud parece pedir vigilancia o espionaje sin consentimiento": "the request appears to seek surveillance or spying without consent",
  "No se puede publicar: la solicitud parece pedir vigilancia o espionaje sin consentimiento.": "Cannot publish: the request appears to seek surveillance or spying without consent.",
  "No se puede publicar: la solicitud parece pedir vigilancia o espionaje sin consentimiento. Si se trata de un servicio legítimo, explica claramente su finalidad y las autorizaciones aplicables.": "Cannot publish: the request appears to seek surveillance or spying without consent. If this is a legitimate service, clearly explain its purpose and the applicable authorisations.",
  "la solicitud parece pedir el vertido ilegal de residuos o materiales peligrosos": "the request appears to seek the illegal dumping of waste or hazardous materials",
  "No se puede publicar: la solicitud parece pedir el vertido ilegal de residuos o materiales peligrosos.": "Cannot publish: the request appears to seek the illegal dumping of waste or hazardous materials.",
  "No se puede publicar: la solicitud parece pedir el vertido ilegal de residuos o materiales peligrosos. Si se trata de un servicio legítimo, explica claramente su finalidad y las autorizaciones aplicables.": "Cannot publish: the request appears to seek the illegal dumping of waste or hazardous materials. If this is a legitimate service, clearly explain its purpose and the applicable authorisations.",
  "la solicitud parece encargar maltrato o daño deliberado a un animal": "the request appears to commission abuse or deliberate harm to an animal",
  "No se puede publicar: la solicitud parece encargar maltrato o daño deliberado a un animal.": "Cannot publish: the request appears to commission abuse or deliberate harm to an animal.",
  "No se puede publicar: la solicitud parece encargar maltrato o daño deliberado a un animal. Si se trata de un servicio legítimo, explica claramente su finalidad y las autorizaciones aplicables.": "Cannot publish: the request appears to commission abuse or deliberate harm to an animal. If this is a legitimate service, clearly explain its purpose and the applicable authorisations.",
  "la solicitud parece pedir un robo o la manipulación de bienes robados": "the request appears to seek theft or the handling of stolen goods",
  "No se puede publicar: la solicitud parece pedir un robo o la manipulación de bienes robados.": "Cannot publish: the request appears to seek theft or the handling of stolen goods.",
  "No se puede publicar: la solicitud parece pedir un robo o la manipulación de bienes robados. Si se trata de un servicio legítimo, explica claramente su finalidad y las autorizaciones aplicables.": "Cannot publish: the request appears to seek theft or the handling of stolen goods. If this is a legitimate service, clearly explain its purpose and the applicable authorisations.",
  "El contenido incluye términos no permitidos por las Normas de la comunidad. Revísalo antes de publicarlo.": "The content includes terms that are not allowed under the Community Guidelines. Review it before publishing.",
  "Describe una finalidad legitima y las autorizaciones aplicables.": "Describe a legitimate purpose and the applicable authorisations.",
  "Tienes % disputa(s) abierta(s). Hay que resolverlas antes de darte de baja: si desapareces, la otra parte se queda sin nadie con quien cerrarlas.": "You have % open dispute(s). They must be resolved before you delete your account: otherwise, the other party will have nobody to resolve them with.",
  "Tienes {cantidad} disputa(s) abierta(s). Hay que resolverlas antes de darte de baja: si desapareces, la otra parte se queda sin nadie con quien cerrarlas.": "You have {cantidad} open dispute(s). They must be resolved before you delete your account: otherwise, the other party will have nobody to resolve them with."
}
