// Faithful English translations for requests, offers, jobs, payments and calendars.
export const EN_WORKFLOWS: Record<string, string> = {
  "Filtros": "Filters",
  "Categoría profesional": "Professional category",
  "Ubicación": "Location",
  "Publicado": "Posted",
  "Cualquier momento": "Any time",
  "Últimas 24 horas": "Last 24 hours",
  "Última semana": "Last week",
  "Último mes": "Last month",
  "Presupuesto": "Budget",
  "Limpiar filtros": "Clear filters",
  "demandas encontradas": "requests found",
  "Más recientes": "Newest first",
  "Más antiguos": "Oldest first",
  "Mayor presupuesto": "Highest budget",
  "Menor presupuesto": "Lowest budget",
  "Menos ofertas": "Fewest offers",
  "archivo": "file",
  "adjunto": "attached",
  "Es tu demanda": "This is your request",
  "Ofertar": "Make an offer",
  "Escribir": "Message",
  "Ver más": "See more",
  "No se encontraron demandas": "No requests found",
  "Prueba a modificar los filtros o ampliar tu búsqueda": "Try changing the filters or broadening your search",
  "Ver perfil del cliente": "View client profile",
  "Descripción del proyecto": "Project description",
  "Archivos adjuntos (": "Attachments (",
  "Publicación:": "Posted:",
  "Esta demanda la has publicado tú. Puedes gestionarla desde Mis Solicitudes.": "You posted this request. You can manage it from My Requests.",
  "Enviar presupuesto": "Send a quote",
  "Contactar": "Contact",
  "Perfil del cliente": "Client profile",
  "Información pública vinculada a sus demandas.": "Public information linked to their requests.",
  "Cuenta eliminada": "Deleted account",
  "Miembro desde": "Member since",
  "Sobre el cliente": "About the client",
  "Demandas abiertas (": "Open requests (",
  "Y": "And",
  "demanda": "request",
  "más.": "more.",
  "Este cliente no tiene otras demandas abiertas.": "This client has no other open requests.",
  "Valoraciones como cliente": "Client reviews",
  "No hay valoraciones públicas disponibles para este cliente.": "There are no public reviews for this client.",
  "Este es tu perfil de cliente.": "This is your client profile.",
  "Para:": "For:",
  "Precio propuesto (€)": "Proposed price (€)",
  "Tiempo estimado": "Estimated duration",
  "Horas": "Hours",
  "Días": "Days",
  "Semanas": "Weeks",
  "Incluye materiales": "Materials included",
  "Sí, incluido en el precio": "Yes, included in the price",
  "No, solo mano de obra": "No, labour only",
  "Parcialmente incluidos": "Partially included",
  "Descripción de tu propuesta": "Your proposal",
  "Archivos adjuntos (opcional)": "Attachments (optional)",
  "Adjuntar": "Attach",
  "Cobro protegido": "Protected payment",
  "Si el cliente acepta tu oferta, tendrá que pagar antes de que empieces. El dinero quedará protegido durante el trabajo. Cuando entregues el servicio y el cliente confirme que todo está correcto, Diime liberará tu pago.": "If the client accepts your offer, they must pay before you start. The money will remain protected while you work. Once you deliver the service and the client confirms that everything is correct, Diime will release your payment.",
  "Acepto los gastos de servicio de Diime (": "I accept Diime's service fees (",
  "% del precio, mín.": "% of the price, min.",
  "; IVA del": "; including",
  "% incluido). Mi oferta es un precio final y soy responsable de facturar y declarar los impuestos de mi servicio.": "% VAT). My offer is a final price and I am responsible for invoicing and declaring the taxes on my service.",
  "Si el cliente acepta esta oferta de": "If the client accepts this offer of",
  "recibiré": "I will receive",
  "netos": "net",
  "Cancelar": "Cancel",
  "Abiertas": "Open",
  "esperando ofertas": "awaiting offers",
  "En Progreso": "In progress",
  "trabajos en curso": "jobs in progress",
  "Por Confirmar": "Awaiting confirmation",
  "Historial": "History",
  "Disputas": "Disputes",
  "en curso": "in progress",
  "No tienes solicitudes pendientes": "You have no pending requests",
  "Publica una nueva solicitud de servicio desde la página principal": "Post a new service request from the home page",
  "Crear Solicitud": "Create request",
  "Publicada el": "Posted on",
  "Has aceptado la oferta de": "You have accepted the offer from",
  "falta completar el pago": "payment still required",
  "La contratación no se cierra hasta que completes el pago protegido. Mientras tanto, las demás ofertas siguen disponibles.": "The booking is not finalised until you complete the protected payment. Other offers remain available in the meantime.",
  "Pagar ahora": "Pay now",
  "Los datos de la demanda quedan bloqueados mientras haya una oferta aceptada o un trabajo activo.": "The request details are locked while an offer is accepted or a job is active.",
  "Editar": "Edit",
  "Borrar": "Delete",
  "oferta": "offer",
  "recibida": "received",
  "Materiales:": "Materials:",
  "Aceptar Oferta": "Accept offer",
  "Rechazar": "Reject",
  "Ver Perfil": "View profile",
  "Aún no has recibido ofertas. Los profesionales están revisando tu solicitud.": "You have not received any offers yet. Professionals are reviewing your request.",
  "Pendiente de Confirmación": "Awaiting confirmation",
  "Pagado · Protegido": "Paid · Protected",
  "Pendiente de pago": "Awaiting payment",
  "Reembolsado": "Refunded",
  "Mensaje": "Message",
  "Pago pendiente": "Payment pending",
  "El trabajo no empezará hasta que completes el pago protegido.": "The job will not start until you complete the protected payment.",
  "Contratación": "Booking",
  "Ver justificante y términos": "View receipt and terms",
  "Trabajo en disputa": "Job under dispute",
  "El equipo de Diime está revisando el caso. El pago queda retenido hasta que se resuelva (reembolso al cliente o liberación al profesional).": "The Diime team is reviewing the case. Payment remains held until the dispute is resolved (a refund to the client or release to the professional).",
  "Progreso del trabajo": "Job progress",
  "Inicio:": "Start:",
  "Entrega estimada:": "Estimated delivery:",
  "Actualizaciones del profesional": "Updates from the professional",
  "% completado": "% complete",
  "El profesional ha marcado el trabajo como entregado": "The professional has marked the job as delivered",
  "Revisa el trabajo realizado y confirma su finalización para liberar el pago.": "Review the work and confirm completion to release the payment.",
  "Confirmar y Liberar Pago": "Confirm and release payment",
  "Confirmar finalización del trabajo": "Confirm job completion",
  "Al confirmar se libera el pago de": "Confirming will release the payment of",
  "pendiente de liquidación y el trabajo queda cerrado. Esta acción no se puede deshacer. ¿Confirmas que el trabajo se ha completado satisfactoriamente?": "awaiting settlement and close the job. This action cannot be undone. Do you confirm that the job has been completed satisfactorily?",
  "Sí, confirmar y pagar": "Yes, confirm and pay",
  "Rechazar entrega": "Reject delivery",
  "Si rechazas la entrega, el pago sigue retenido y el equipo de Diime decidirá según las pruebas y los términos acordados.": "If you reject delivery, payment remains held and the Diime team will decide based on the evidence and agreed terms.",
  "No tienes proyectos completados": "You have no completed projects",
  "Los proyectos finalizados aparecerán aquí": "Completed projects will appear here",
  "Completado el": "Completed on",
  "Profesional:": "Professional:",
  "Valorado": "Reviewed",
  "Dejar valoración": "Leave a review",
  "Valorar al profesional": "Review the professional",
  "Tu valoración ayuda a otros clientes y motiva a los profesionales a dar lo mejor de sí.": "Your review helps other clients and encourages professionals to do their best.",
  "Puntuación": "Rating",
  "Comentario": "Comment",
  "Omitir": "Skip",
  "Enviar valoración": "Submit review",
  "Rechazar la entrega": "Reject delivery",
  "Si la entrega no cumple lo acordado, puedes rechazarla. El pago": "If the delivery does not meet the agreed terms, you can reject it. Payment",
  "no se reembolsa automáticamente": "is not automatically refunded",
  ": la transferencia queda bloqueada y el equipo de Diime decidirá según las pruebas y los términos acordados.": ": the transfer is blocked and the Diime team will decide based on the evidence and agreed terms.",
  "Se abrirá una disputa. Adjunta tus pruebas en el chat del trabajo (fotos, mensajes): Diime las revisará junto con lo acordado antes de decidir si te reembolsa o libera el pago al profesional.": "A dispute will be opened. Attach your evidence in the job chat (photos, messages): Diime will review it alongside the agreed terms before deciding whether to refund you or release payment to the professional.",
  "Motivo del rechazo *": "Reason for rejection *",
  "Rechazar y abrir disputa": "Reject and open a dispute",
  "Editar demanda": "Edit request",
  "Modifica los datos de tu demanda. Solo es posible mientras siga abierta.": "Update your request details. You can only do this while it is still open.",
  "Tipo de servicio": "Service type",
  "Título": "Title",
  "Descripción": "Description",
  "Presupuesto mín. (€)": "Minimum budget (€)",
  "Presupuesto máx. (€)": "Maximum budget (€)",
  "¿Cuándo necesitas el trabajo?": "When do you need the work done?",
  "En una fecha concreta": "On a specific date",
  "Guardar cambios": "Save changes",
  "Aceptar oferta y continuar al pago": "Accept offer and proceed to payment",
  "Vas a aceptar la oferta de": "You are accepting an offer of",
  "para \"": "for \"",
  "\". Al pagar, Diime añadirá los gastos de servicio de la plataforma (": "\". At checkout, Diime will add the platform service fees (",
  "%, mín. 2€; IVA del": "%, min. €2; including",
  "% incluido). El precio de la oferta es el precio final indicado por el profesional.": "% VAT). The offer price is the final price quoted by the professional.",
  "Precio final del servicio": "Final service price",
  "Gastos de servicio Diime (": "Diime service fees (",
  "%; IVA del": "%; including",
  "% incluido)": "% VAT)",
  "Total a pagar": "Total to pay",
  "Aceptar y pagar": "Accept and pay",
  "¿Rechazar esta oferta?": "Reject this offer?",
  "Se rechazará la oferta de": "The offer of",
  ". El profesional será notificado y no podrás deshacer esta acción.": " will be rejected. The professional will be notified and you cannot undo this action.",
  "Rechazar oferta": "Reject offer",
  "¿Borrar esta demanda?": "Delete this request?",
  "Se eliminará \"": "\"",
  "\" de forma permanente. Esta acción no se puede deshacer.": "\" will be permanently deleted. This action cannot be undone.",
  "Pujas en curso (": "Active bids (",
  "Puedes editarlas o retirarlas mientras el cliente no las acepte. Cuando una puja aceptada se pague, pasará a Gestión de Proyectos como trabajo activo; hasta entonces sigue aquí.": "You can edit or withdraw them until the client accepts them. Once an accepted bid is paid for, it moves to Project Management as an active job; until then, it stays here.",
  "No tienes pujas pendientes": "You have no pending bids",
  "Explora las demandas publicadas y envía tu puja.": "Browse posted requests and send your bid.",
  "Ver demandas": "View requests",
  "Aceptada · esperando pago del cliente": "Accepted · Awaiting client payment",
  "Enviada": "Sent",
  "Precio ofertado": "Offer price",
  "Enviada el": "Sent on",
  "estimados": "estimated",
  "Descripción del Servicio:": "Service description:",
  "El cliente aceptó tu puja pero aún no ha completado el pago protegido. Cuando lo haga, el trabajo aparecerá en Gestión de Proyectos.": "The client accepted your bid but has not completed the protected payment yet. Once they do, the job will appear in Project Management.",
  "Ver demanda": "View request",
  "Contactar Cliente": "Contact client",
  "Editar oferta": "Edit offer",
  "Retirar": "Withdraw",
  "Pujas perdidas (": "Unsuccessful bids (",
  "Puedes revisar qué ofertaste, borrar las pujas que ya no quieras conservar y, si la demanda sigue abierta, enviar una nueva propuesta.": "You can review your offers, delete bids you no longer want to keep and submit a new proposal if the request is still open.",
  "No seleccionada": "Not selected",
  "Ofertaste": "You offered",
  "Volver a pujar": "Bid again",
  "Precio (€)": "Price (€)",
  "Archivos adjuntos": "Attachments",
  "Añadir": "Add",
  "Si el cliente acepta esta oferta, recibiré": "If the client accepts this offer, I will receive",
  "netos.": "net.",
  "Publicada por": "Posted by",
  "Descripción del cliente": "Client description",
  "Mis Trabajos": "My Jobs",
  "Gestiona todos tus trabajos activos y completados": "Manage all your active and completed jobs",
  "Todos": "All",
  "Completados": "Completed",
  "Cancelados": "Cancelled",
  "No tienes trabajos": "You have no jobs",
  "Iniciado:": "Started:",
  "Pago protegido - Estado:": "Protected payment - Status:",
  "Marcar como Completado": "Mark as completed",
  "¿Marcar trabajo como completado?": "Mark this job as completed?",
  "Esta acción notificará al cliente que el trabajo está completado. Si hay un pago en pago protegido, el cliente podrá liberar la transferencia.": "This will notify the client that the job is complete. If a protected payment is held, the client will be able to release the transfer.",
  "Confirmar": "Confirm",
  "Dejar Valoración": "Leave a review",
  "Tipo de Servicio": "Service type",
  "Provincia donde se realizará el servicio": "Province where the service will take place",
  "Título del Proyecto": "Project title",
  "Presupuesto estimado": "Estimated budget",
  "Fecha exacta": "Exact date",
  "Adjuntar fotos": "Attach photos",
  "archivo(s)": "file(s)",
  "Publicar Proyecto": "Post project",
  "Abrir disputa": "Open dispute",
  "Abrir una disputa": "Open a dispute",
  "Úsala si hay un problema con este trabajo y no llegáis a un acuerdo. Al abrirla, la transferencia queda": "Use this if there is a problem with the job and you cannot reach an agreement. Opening a dispute",
  "congelada": "freezes the transfer",
  "y el equipo de Diime revisará la conversación y las pruebas para decidir si se reembolsa al cliente o se libera al proveedor.": "and the Diime team will review the conversation and evidence to decide whether to refund the client or release payment to the provider.",
  "Motivo de la disputa": "Reason for dispute",
  "Aporta el máximo detalle. Las fotos y mensajes del trabajo se incluyen automáticamente como pruebas.": "Provide as much detail as possible. Photos and messages from the job are automatically included as evidence.",
  "La resolución de Diime es una mediación privada entre las partes y": "Diime's decision is private mediation between the parties and",
  "no impide ni sustituye": "does not prevent or replace",
  "cualquier otra acción legal que puedas emprender por tu cuenta fuera de la plataforma.": "any other legal action you may take independently outside the platform.",
  "Abriendo...": "Opening...",
  "Pruebas o documentos (opcional)": "Evidence or documents (optional)",
  "Adjuntar archivos": "Attach files",
  "Imágenes, PDF u otros documentos · máximo 10 MB por archivo.": "Images, PDFs or other documents · maximum 10 MB per file.",
  "La otra parte quiere cancelar este trabajo": "The other party wants to cancel this job",
  "Motivo:": "Reason:",
  "Si aceptas, el trabajo se cancela (y si el cliente ya pagó, se le reembolsa íntegramente). Si rechazas, podrás aportar tus argumentos y archivos; se abrirá una disputa automáticamente y la resolverá el equipo de Diime.": "If you accept, the job is cancelled (and if the client has already paid, they receive a full refund). If you reject, you can provide your arguments and files; a dispute will open automatically for the Diime team to resolve.",
  "Aceptar cancelación": "Accept cancellation",
  "Rechazar la cancelación": "Reject cancellation",
  "Explica por qué debe continuar el servicio o cómo debería resolverse. Al rechazarla se abrirá una disputa y el equipo de Diime contrastará los argumentos y archivos de ambas partes.": "Explain why the service should continue or how it should be resolved. Rejecting the cancellation opens a dispute, and the Diime team will review both parties' arguments and files.",
  "Tus argumentos *": "Your arguments *",
  "Volver": "Back",
  "Rechazar y enviar a revisión": "Reject and submit for review",
  "Has solicitado cancelar este trabajo. Esperando la respuesta de la otra parte.": "You have requested cancellation of this job. Waiting for the other party's response.",
  "Editar solicitud": "Edit request",
  "Retirar solicitud": "Withdraw request",
  "Editar solicitud de cancelación": "Edit cancellation request",
  "Puedes modificar el motivo, quitar pruebas anteriores o añadir otras mientras la solicitud siga pendiente.": "You can edit the reason, remove earlier evidence or add new evidence while the request is pending.",
  "Motivo *": "Reason *",
  "Archivos actuales": "Current files",
  "¿Retirar la solicitud?": "Withdraw the request?",
  "La petición de cancelación desaparecerá, la otra parte ya no tendrá que responder y el servicio continuará en su estado actual.": "The cancellation request will be removed, the other party will no longer need to respond and the service will continue in its current state.",
  "Mantener solicitud": "Keep request",
  "La solicitud de cancelación fue rechazada y el caso pasa a disputa: lo resolverá el equipo de Diime según los términos de la contratación.": "The cancellation request was rejected and the case is now a dispute: the Diime team will resolve it based on the booking terms.",
  "Solicitar cancelación": "Request cancellation",
  "La cancelación debe ser de mutuo acuerdo: la otra parte recibirá un aviso y deberá aceptarla o rechazarla. Si la acepta y el trabajo ya estaba pagado, el cliente recibe el reembolso íntegro automáticamente. Si la rechaza, se abrirá una disputa que resolverá el equipo de Diime.": "Cancellation requires mutual agreement: the other party will be notified and must accept or reject it. If they accept and the job has already been paid for, the client automatically receives a full refund. If they reject, a dispute will open for the Diime team to resolve.",
  "Enviar solicitud": "Send request",
  "Pago protegido hasta la entrega": "Payment protected until delivery",
  "Los fondos se retienen de forma segura hasta que confirmes que el trabajo esta completo": "Funds are held securely until you confirm that the job is complete",
  "Pago Exitoso": "Payment successful",
  "La transferencia al profesional se hará cuando confirmes la entrega o se resuelva una disputa": "Payment will be transferred to the professional when you confirm delivery or a dispute is resolved",
  "Precio del servicio:": "Service price:",
  "Comision de servicio (10%):": "Service fee (10%):",
  "Total a pagar:": "Total to pay:",
  "Elige cómo pagar": "Choose how to pay",
  "Tarjeta, Apple Pay, Google Pay o Link, según disponibilidad": "Card, Apple Pay, Google Pay or Link, subject to availability",
  "Proteccion del Comprador": "Buyer protection",
  "Tus fondos se mantienen seguros hasta que apruebes el trabajo completado": "Your funds are held securely until you approve the completed work",
  "Pago Seguro": "Secure payment",
  "Procesado por Stripe con encriptacion de nivel bancario": "Processed by Stripe with bank-grade encryption",
  "Los fondos se retendran de forma segura hasta que confirmes que el trabajo esta completo. Total:": "Funds will be held securely until you confirm that the job is complete. Total:",
  "No tienes disputas": "You have no disputes",
  "Si surge un desacuerdo sobre un trabajo, aquí verás las disputas que hayas abierto y las que la otra parte haya abierto, con su estado y la decisión del equipo de Diime.": "If a disagreement arises over a job, you will see disputes opened by you or the other party here, together with their status and the Diime team's decision.",
  "Motivo": "Reason",
  "Pruebas aportadas para la cancelación": "Evidence provided for cancellation",
  "Solicita cancelar ·": "Cancellation requested by ·",
  "Rechaza cancelar ·": "Cancellation rejected by ·",
  "Decisión del equipo de Diime": "Diime team's decision",
  "Resuelta el": "Resolved on",
  "La decisión de Diime es una mediación privada entre las partes y en ningún caso te impide emprender por tu cuenta las acciones legales o de otro tipo que consideres.": "Diime's decision is private mediation between the parties and does not prevent you from independently pursuing any legal or other action you consider appropriate.",
  "Aportar pruebas en el chat": "Provide evidence in the chat",
  "Retirar disputa": "Withdraw dispute",
  "Tienes": "You have",
  "disputa": "dispute",
  "en revisión. Mientras dure, el pago sigue confirmado y la transferencia bloqueada. Puedes aportar pruebas en el chat del trabajo.": "under review. While it is ongoing, payment remains confirmed and the transfer remains blocked. You can provide evidence in the job chat.",
  "¿Retirar la disputa?": "Withdraw the dispute?",
  "El equipo de Diime dejará de revisarla y el trabajo continuará donde estaba, con la transferencia pendiente. Si vuelve a hacer falta, podrás abrir una disputa nueva.": "The Diime team will stop reviewing it and the job will return to its previous state, with the transfer pending. You can open a new dispute later if necessary.",
  "Reportar incidencia": "Report an issue",
  "No tienes incidencias": "You have no issues",
  "Si tienes un problema con un pago, un trabajo o con otro usuario, repórtalo y nuestro equipo lo revisará. Aquí verás el estado de cada incidencia.": "If you have a problem with a payment, a job or another user, report it and our team will review it. You can track each issue's status here.",
  "· Reportada el": "· Reported on",
  "Prioridad": "Priority",
  "Trabajo relacionado:": "Related job:",
  "Respuesta del equipo de Diime": "Diime team's response",
  "Retirar incidencia": "Withdraw issue",
  "¿Retirar la incidencia?": "Withdraw the issue?",
  "El equipo de Diime dejará de revisarla. Podrás reportarla de nuevo más adelante si lo necesitas.": "The Diime team will stop reviewing it. You can report it again later if necessary.",
  "Reportar una incidencia": "Report an issue",
  "Describe el problema. Nuestro equipo de soporte lo revisará y te contactará si es necesario.": "Describe the problem. Our support team will review it and contact you if necessary.",
  "Trabajo relacionado (opcional)": "Related job (optional)",
  "Puedes enviar un reporte general aunque todavía no tengas trabajos contratados.": "You can send a general report even if you have not booked any jobs yet.",
  "Sin trabajo relacionado": "No related job",
  "Asunto": "Subject",
  "Categoría": "Category",
  "Fraude o estafa": "Fraud or scam",
  "Abuso o conducta": "Abuse or misconduct",
  "Problema de pago": "Payment problem",
  "Problema técnico": "Technical problem",
  "Perfil / verificación": "Profile / verification",
  "Otro": "Other",
  "Baja": "Low",
  "Media": "Medium",
  "Alta": "High",
  "Crítica": "Critical",
  "Enviando...": "Sending...",
  "Cargando calendario...": "Loading calendar...",
  "Hoy": "Today",
  "Añadir evento": "Add event",
  "más": "more",
  "Inicio trabajo": "Job start",
  "Entrega trabajo": "Job delivery",
  "Inicio servicio": "Service start",
  "Recepción servicio": "Service delivery",
  "Evento personal": "Personal event",
  "Festivo nacional": "National holiday",
  "Próximos eventos": "Upcoming events",
  "No hay próximos eventos": "No upcoming events",
  "Resumen": "Summary",
  "Trabajos": "Jobs",
  "Servicios": "Services",
  "Eventos personales": "Personal events",
  "Añade reuniones, recordatorios u otros eventos personales a tu calendario.": "Add meetings, reminders or other personal events to your calendar.",
  "Título *": "Title *",
  "Fecha inicio *": "Start date *",
  "Fecha fin (opcional)": "End date (optional)",
  "Todo el día": "All day",
  "Notas": "Notes",
  "Color": "Colour",
  "Eliminar": "Delete",
  "Cobros profesionales": "Professional payouts",
  "Consulta lo que tienes en Stripe y cuándo llegará el próximo ingreso a tu banco.": "See your Stripe balance and when the next payout will reach your bank.",
  "Modo de prueba": "Test mode",
  "Comprobando": "Checking",
  "Cuenta de cobros activa": "Payout account active",
  "Acción necesaria": "Action required",
  "Saldo en Stripe": "Stripe balance",
  "Disponible + pendiente": "Available + pending",
  "Disponible": "Available",
  "Listo para enviar al banco": "Ready to send to your bank",
  "Pendiente": "Pending",
  "Aún procesándose en Stripe": "Still processing in Stripe",
  "Otros saldos:": "Other balances:",
  "tiene llegada estimada a tu banco el": "is expected to reach your bank on",
  "El saldo pendiente empezará a estar disponible para enviarlo al banco el": "The pending balance will start becoming available to send to your bank on",
  ". Después se enviará": ". It will then be sent",
  ". Stripe todavía no ha generado una fecha de llegada al banco.": ". Stripe has not provided a bank arrival date yet.",
  "Stripe no ha podido confirmar ahora la fecha del próximo ingreso.": "Stripe cannot currently confirm the next payout date.",
  "El saldo se enviará": "The balance will be sent",
  ". Stripe todavía no ha generado una fecha bancaria exacta.": ". Stripe has not provided an exact bank arrival date yet.",
  "No hay ingresos bancarios programados.": "No bank payouts are scheduled.",
  "Abrir panel de Stripe": "Open Stripe dashboard",
  "Actualizar": "Refresh",
  "Este saldo solo incluye pagos que Diime ya te ha liberado. El dinero de trabajos en curso sigue protegido hasta la confirmación de la entrega o la resolución de una disputa.": "This balance only includes payments Diime has already released to you. Money for ongoing jobs remains protected until delivery is confirmed or a dispute is resolved.",
  "El alta y el panel se abren en una página segura de Stripe. Al terminar volverás automáticamente a Cobros en Diime.": "Registration and the dashboard open on a secure Stripe page. When you finish, you will automatically return to Payouts in Diime.",
  "Volviendo a Diime…": "Returning to Diime…",
  "Si la app no se abre automáticamente, pulsa el botón para continuar donde estabas.": "If the app does not open automatically, press the button to continue where you left off.",
  "Abrir Diime": "Open Diime",
  "Continuar en la web": "Continue on the web",
  "Consultando saldo de Stripe…": "Checking Stripe balance…",
  "No se pudo consultar Stripe": "Could not retrieve Stripe information",
  "Activa Stripe para empezar a recibir tus cobros.": "Activate Stripe to start receiving payouts.",
  "Saldo no disponible": "Balance unavailable",
  "Prueba": "Test",
  "· Pendiente": "· Pending",
  "Error en el pago": "Payment error",
  "Confirmando el pago...": "Confirming payment...",
  "No cierres esta ventana.": "Do not close this window.",
  "Pago realizado con exito": "Payment successful",
  "Los fondos quedan retenidos de forma segura hasta que confirmes la finalizacion del trabajo.": "Funds are held securely until you confirm that the job is complete.",
  "Redirigiendo a Mis Solicitudes...": "Redirecting to My Requests...",
  "Pago Protegido": "Protected payment",
  "Tu dinero está protegido": "Your money is protected",
  "El importe": "The amount",
  "no llega al profesional al pagar": "is not sent to the professional when you pay",
  ": queda retenido por Diime y": ": it is held by Diime and",
  "solo se libera cuando tú confirmes": "is only released when you confirm",
  "que has recibido el servicio correctamente. Si no quedas satisfecho,": "that you have received the service as agreed. If you are not satisfied,",
  "se te reembolsa": "you will be refunded",
  "Desglose del pago": "Payment breakdown",
  "Pago 100% seguro con Stripe": "100% secure payment with Stripe",
  "Fondos retenidos hasta confirmacion": "Funds held until confirmation",
  "Reembolso si no estas satisfecho": "Refund if you are not satisfied",
  "Realizar pago": "Make payment",
  "Elige tarjeta o una opción de pago rápido disponible en tu dispositivo.": "Choose a card or an express payment option available on your device.",
  "Preparando checkout seguro...": "Preparing secure checkout...",
  "Pago completado": "Payment completed",
  "Los fondos quedan retenidos en escrow de forma segura.": "Funds are held securely in escrow.",
  "Solo se liberaran al profesional cuando confirmes la finalizacion del trabajo.": "They will only be released to the professional when you confirm that the job is complete.",
  "Importe pagado": "Amount paid",
  "Estado": "Status",
  "En escrow": "In escrow",
  "Reiniciar demo": "Reset demo",
  "Ir al inicio": "Go to home page",
  "Volver al inicio": "Back to home page",
  "Demo interactiva": "Interactive demo",
  "No se cobrara nada real": "No real charge will be made",
  "Vista previa del pago con escrow": "Escrow payment preview",
  "Asi es como un cliente ve el desglose de comisiones al pagar un trabajo. Modifica el precio acordado para ver como cambian las cifras en tiempo real.": "This is how a client sees the fee breakdown when paying for a job. Change the agreed price to see the figures update in real time.",
  "Precio acordado con el profesional": "Price agreed with the professional",
  "10.000 €": "€10,000",
  "Resumen del trabajo": "Job summary",
  "Renovacion integral cocina 12 m2": "Complete 12 m² kitchen renovation",
  "Demolicion, electricidad, fontaneria, alicatado y montaje de muebles": "Demolition, electrical work, plumbing, tiling and cabinet installation",
  "Profesional: Reformas Garcia S.L.": "Professional: Reformas Garcia S.L.",
  "Madrid, Espana": "Madrid, Spain",
  "Inicio estimado: 12 jun 2026": "Estimated start: 12 Jun 2026",
  "Pago protegido con escrow": "Payment protected with escrow",
  "Tu pago queda retenido de forma segura. Solo se libera al profesional cuando confirmas que el trabajo esta finalizado correctamente.": "Your payment is held securely. It is only released to the professional when you confirm that the job has been completed correctly.",
  "Desglose de tu pago": "Your payment breakdown",
  "Comision plataforma": "Platform fee",
  "Total a pagar hoy": "Total to pay today",
  "Cargado a tu metodo de pago": "Charged to your payment method",
  "Que cubre tu pago": "What your payment covers",
  "El precio acordado con el profesional (": "The price agreed with the professional (",
  ") y los servicios de la plataforma: pago protegido en escrow, mediacion en disputas, soporte 24/7 y garantia de satisfaccion.": ") and platform services: protected escrow payment, dispute mediation, 24/7 support and a satisfaction guarantee.",
  "Metodo de pago": "Payment method",
  "Tarjeta": "Card",
  "Transferencia": "Bank transfer",
  "Numero de tarjeta": "Card number",
  "Caducidad": "Expiry date",
  "Codigo postal": "Postcode",
  "Pagar": "Pay",
  "de forma segura": "securely",
  "Pago cifrado SSL. Procesado por Stripe.": "SSL-encrypted payment. Processed by Stripe.",
  "Esta es una demostracion. No se realiza ningun cargo real ni se almacenan los datos introducidos.": "This is a demonstration. No real charge is made and the information you enter is not stored.",
  "Completado": "Completed",
  "En progreso": "In progress",
  "Pendiente pago": "Awaiting payment",
  "Normal": "Normal",
  "Mi calendario": "My calendar",
  "Aquí ves tanto los": "Here you can see both the",
  "trabajos que tienes que realizar": "jobs you need to carry out",
  "como los": "and the",
  "servicios que te van a realizar a ti": "services being provided to you",
  "trabajos": "jobs",
  "servicios": "services",
  "Carga de Trabajo": "Workload",
  "Total activos": "Total active",
  "Horas estimadas": "Estimated hours",
  "Horas registradas": "Logged hours",
  "trabajo(s) atrasado(s)": "overdue job(s)",
  "No tienes trabajos activos": "You have no active jobs",
  "Cliente:": "Client:",
  "Servicios Solicitados": "Requested services",
  "No has solicitado servicios": "You have not requested any services",
  "Por:": "By:",
  "Entrega:": "Delivery:",
  "Trabajos que realizo": "Jobs I carry out",
  "Servicios que me realizan": "Services provided to me",
  "Mes": "Month",
  "Semana": "Week",
  "mas": "more",
  "Sin actividad programada": "No scheduled activity",
  "Gestionar Trabajo": "Manage job",
  "Edita las fechas y notas del trabajo seleccionado.": "Edit the selected job's dates and notes.",
  "Fecha inicio": "Start date",
  "Fecha estimada fin": "Estimated end date",
  "Notas privadas (solo tu las ves)": "Private notes (only you can see these)",
  "Monto:": "Amount:",
  "Servicio Solicitado": "Requested service",
  "Detalles del servicio que has contratado.": "Details of the service you booked.",
  "Monto": "Amount",
  "Fecha estimada de entrega:": "Estimated delivery date:",
  "Este servicio esta atrasado. Contacta con el profesional.": "This service is overdue. Contact the professional.",
  "Cerrar": "Close",
  "Contactar profesional": "Contact professional",
  "Toda España": "All Spain",
  "Ayer": "Yesterday",
  "Todas las categorías": "All categories",
  "Cliente": "Client",
  "No disponible": "Unavailable",
  "No se ha podido identificar a quien publicó la demanda.": "The person who posted the request could not be identified.",
  "Inicia sesión": "Sign in",
  "Necesitas una cuenta para escribir al cliente.": "You need an account to message the client.",
  "No puedes escribirte a ti mismo.": "You cannot message yourself.",
  "Error": "Error",
  "No se pudo abrir el chat.": "Could not open the chat.",
  "Precio no válido": "Invalid price",
  "El precio propuesto debe ser mayor que 0.": "The proposed price must be greater than 0.",
  "Tiempo no válido": "Invalid duration",
  "El tiempo estimado debe ser mayor que 0.": "The estimated duration must be greater than 0.",
  "Falta aceptar los gastos de servicio": "You must accept the service fees",
  "Debes aceptar los gastos de servicio de Diime antes de enviar la oferta.": "You must accept Diime's service fees before submitting the offer.",
  "No se pudieron subir los archivos": "Could not upload the files",
  "Tu oferta no se ha enviado. Inténtalo de nuevo o quita los adjuntos.": "Your offer has not been sent. Please try again or remove the attachments.",
  "Oferta enviada": "Offer sent",
  "Tu presupuesto ha sido enviado correctamente.": "Your quote has been sent successfully.",
  "No se pudo enviar la oferta": "Could not send the offer",
  "Buscar demandas...": "Search requests...",
  "oferta recibida": "offer received",
  "ofertas recibidas": "offers received",
  "Ubicación no indicada": "Location not provided",
  "Sin categoría": "No category",
  "Cliente no disponible": "Client unavailable",
  "Escribir al cliente": "Message the client",
  "Seleccionar": "Select",
  "Describe tu experiencia, cómo abordarías el trabajo, disponibilidad...": "Describe your experience, how you would approach the job, your availability...",
  "Faltan datos": "Missing details",
  "Selecciona una categoría y añade un título y una descripción (mín. 10 caracteres).": "Select a category and add a title and description (at least 10 characters).",
  "Fecha no válida": "Invalid date",
  "Selecciona una fecha que no esté en el pasado.": "Select a date that is not in the past.",
  "Demanda actualizada": "Request updated",
  "Los cambios se han guardado.": "Your changes have been saved.",
  "No se pudo identificar al destinatario.": "Could not identify the recipient.",
  "Abriendo chat...": "Opening chat...",
  "Preparando la conversación.": "Preparing the conversation.",
  "Demanda borrada": "Request deleted",
  "La demanda se ha eliminado.": "The request has been deleted.",
  "Procesando...": "Processing...",
  "Creando el trabajo y preparando el pago seguro": "Creating the job and preparing secure payment",
  "No se pudo aceptar la oferta": "Could not accept the offer",
  "Inténtalo de nuevo.": "Please try again.",
  "Oferta rechazada": "Offer rejected",
  "El profesional ha sido notificado.": "The professional has been notified.",
  "Trabajo confirmado": "Job confirmed",
  "El pago ha sido liberado al profesional.": "Payment has been released to the professional.",
  "Por favor, indica el motivo del rechazo.": "Please provide a reason for rejecting the delivery.",
  "Entrega rechazada · disputa abierta": "Delivery rejected · Dispute opened",
  "La transferencia queda bloqueada. El equipo de Diime revisará las pruebas y los términos acordados para decidir.": "The transfer is blocked. The Diime team will review the evidence and agreed terms before deciding.",
  "Valoración enviada": "Review submitted",
  "Gracias por tu valoración. Ayuda a otros clientes a elegir mejor.": "Thank you for your review. It helps other clients make better choices.",
  "entrega por revisar": "delivery to review",
  "entregas por revisar": "deliveries to review",
  "un profesional": "a professional",
  "no incluidos": "not included",
  "parcialmente incluidos": "partially included",
  "No tienes proyectos en progreso": "You have no projects in progress",
  "No tienes entregas pendientes de confirmar": "You have no deliveries awaiting confirmation",
  "Cuando aceptes una oferta, el proyecto aparecerá aquí": "When you accept an offer, the project will appear here",
  "Cuando un profesional te entregue un trabajo, aquí podrás confirmarlo y liberar el pago": "When a professional delivers a job, you can confirm it and release payment here",
  "Fecha de entrega vencida": "Delivery overdue",
  "Entrega mañana": "Delivery tomorrow",
  "Muy malo": "Very poor",
  "Malo": "Poor",
  "Aceptable": "Acceptable",
  "Bueno": "Good",
  "Excelente": "Excellent",
  "Describe tu experiencia con este profesional...": "Describe your experience with this professional...",
  "Explica por qué la entrega no cumple lo acordado...": "Explain why the delivery does not meet the agreed terms...",
  "Selecciona un servicio": "Select a service",
  "Perderás la oferta que has recibido, y avisaremos al profesional que la envió.": "You will lose the offer you received, and we will notify the professional who sent it.",
  "No se pudieron cargar tus pujas": "Could not load your bids",
  "Debes revisar y aceptar los gastos de servicio de Diime antes de enviar la oferta.": "You must review and accept Diime's service fees before submitting the offer.",
  "No se ha guardado ningún cambio. Inténtalo de nuevo o quita los adjuntos nuevos.": "No changes have been saved. Please try again or remove the new attachments.",
  "Nueva oferta enviada": "New offer sent",
  "Oferta actualizada": "Offer updated",
  "Has vuelto a pujar y el cliente ha recibido tu nueva propuesta.": "You have bid again and the client has received your new proposal.",
  "Los cambios se han guardado y el cliente ha sido notificado.": "Your changes have been saved and the client has been notified.",
  "Puja borrada": "Bid deleted",
  "La puja perdida se ha eliminado.": "The unsuccessful bid has been deleted.",
  "Oferta retirada": "Offer withdrawn",
  "Tu oferta se ha retirado.": "Your offer has been withdrawn.",
  "No se pudo identificar al cliente.": "Could not identify the client.",
  "Servicio": "Service",
  "Falta confirmar la tarifa de esta oferta. Solicita cancelar el contrato pendiente y envía una nueva oferta revisando los gastos de servicio.": "The fee for this offer still needs to be confirmed. Request cancellation of the pending contract and submit a new offer after reviewing the service fees.",
  "Para que el cliente pueda contratar esta oferta, ábrela en Editar y confirma los gastos de servicio y tu importe neto.": "To allow the client to book this offer, open Edit and confirm the service fees and your net amount.",
  "Ubicación no especificada": "Location not specified",
  "días": "days",
  "Revisa tu propuesta anterior y envíala de nuevo. El cliente la recibirá como una nueva puja.": "Review your earlier proposal and submit it again. The client will receive it as a new bid.",
  "Puedes modificar tu oferta mientras no haya sido aceptada. El cliente recibirá una notificación.": "You can edit your offer until it has been accepted. The client will be notified.",
  "Quitar adjunto": "Remove attachment",
  "Quitar archivo nuevo": "Remove new file",
  "Subiendo...": "Uploading...",
  "Enviar nueva oferta": "Send new offer",
  "¿Borrar esta puja perdida?": "Delete this unsuccessful bid?",
  "¿Retirar esta oferta?": "Withdraw this offer?",
  "esta demanda": "this request",
  "Borrar puja": "Delete bid",
  "Retirar oferta": "Withdraw offer",
  "Demanda": "Request",
  " o más": " or more",
  "Sin descripción.": "No description.",
  "Cancelado": "Cancelled",
  "Trabajo completado": "Job completed",
  "El trabajo ha sido marcado como completado": "The job has been marked as completed",
  "Categoría no especificada": "Category not specified",
  "Selecciona una categoría": "Select a category",
  "Mínimo 5 caracteres": "At least 5 characters",
  "Mínimo 20 caracteres": "At least 20 characters",
  "Ingresa tu ubicación": "Enter your location",
  "Indica la urgencia": "Select the urgency",
  "Selecciona una fecha": "Select a date",
  "La fecha no puede estar en el pasado": "The date cannot be in the past",
  "Tu demanda no se ha publicado. Inténtalo de nuevo o quita los adjuntos.": "Your request has not been posted. Please try again or remove the attachments.",
  "¡Proyecto publicado!": "Project posted!",
  "Los profesionales ya pueden ver tu solicitud y enviarte ofertas.": "Professionals can now view your request and send you offers.",
  "No se pudo publicar": "Could not post your project",
  "Hubo un problema. Inténtalo de nuevo.": "Something went wrong. Please try again.",
  "¿Qué necesitas?": "What do you need?",
  "Provincia de realización del servicio": "Province where the service will take place",
  "Ej: Reforma completa de baño": "E.g. complete bathroom renovation",
  "Describe el trabajo que necesitas...": "Describe the work you need...",
  "¿Cuándo lo necesitas?": "When do you need it?",
  "Publicando...": "Posting...",
  "Ej.: entregué el trabajo acordado y el cliente no confirma la recepción para liberar el pago...": "E.g. I delivered the agreed work and the client has not confirmed receipt to release payment...",
  "Ej.: el servicio no se ha realizado / no cumple lo acordado. Explica qué falló y qué solución pides...": "E.g. the service was not provided / does not meet the agreed terms. Explain what went wrong and what solution you are requesting...",
  "Falta el motivo": "Reason required",
  "Describe qué ha ocurrido.": "Describe what happened.",
  "No se pudo abrir la disputa": "Could not open the dispute",
  "Disputa abierta": "Dispute opened",
  "El pago queda retenido y el equipo de Diime la revisará para resolverla.": "Payment remains held and the Diime team will review the dispute to resolve it.",
  "Archivo demasiado grande": "File too large",
  "Cada archivo puede ocupar como máximo 10 MB.": "Each file must be no larger than 10 MB.",
  "Demasiados archivos": "Too many files",
  "No se pudieron subir todos los archivos. Inténtalo de nuevo o quita los adjuntos.": "Not all files could be uploaded. Please try again or remove the attachments.",
  "Explica por qué quieres cancelar el servicio.": "Explain why you want to cancel the service.",
  "No se pudo solicitar": "Could not submit the request",
  "Cancelación solicitada": "Cancellation requested",
  "La otra parte recibirá tus argumentos y archivos para aceptarla o rechazarla.": "The other party will receive your arguments and files to accept or reject the request.",
  "Faltan tus argumentos": "Your arguments are required",
  "Explica por qué rechazas la cancelación para que el equipo de Diime pueda decidir.": "Explain why you reject the cancellation so that the Diime team can decide.",
  "Cancelación aceptada": "Cancellation accepted",
  "Cancelación rechazada: disputa abierta": "Cancellation rejected: dispute opened",
  "El trabajo ha quedado cancelado. Si el cliente había pagado, se le reembolsa íntegramente.": "The job has been cancelled. If the client had already paid, they will receive a full refund.",
  "Tus argumentos y archivos se han enviado al equipo de Diime para que resuelva.": "Your arguments and files have been sent to the Diime team for a decision.",
  "No se pudo actualizar": "Could not update",
  "Solicitud actualizada": "Request updated",
  "La otra parte podrá ver tus nuevos argumentos y archivos.": "The other party will be able to see your new arguments and files.",
  "No se pudo retirar": "Could not withdraw",
  "Solicitud retirada": "Request withdrawn",
  "El servicio continúa activo y la otra parte ha sido avisada.": "The service remains active and the other party has been notified.",
  "Explica por qué no estás de acuerdo con la cancelación...": "Explain why you disagree with the cancellation...",
  "Explica por qué quieres cancelar...": "Explain why you want to cancel...",
  "Explica brevemente por qué quieres cancelar...": "Briefly explain why you want to cancel...",
  "Preparando pago...": "Preparing payment...",
  "Continuar al Pago": "Continue to payment",
  "En revisión por Diime": "Under review by Diime",
  "Retirada": "Withdrawn",
  "Resuelta a tu favor": "Resolved in your favour",
  "Resuelta en tu contra": "Resolved against you",
  "Resuelta de forma parcial": "Partially resolved",
  "Resuelta a tu favor: se te ha reembolsado el importe.": "Resolved in your favour: you have been refunded.",
  "Resuelta a favor del cliente: se le ha reembolsado el importe.": "Resolved in the client's favour: they have been refunded.",
  "Resuelta a favor del profesional: se le ha liberado el pago.": "Resolved in the professional's favour: payment has been released to them.",
  "Resuelta a tu favor: se te ha liberado el pago.": "Resolved in your favour: payment has been released to you.",
  "Resuelta de forma parcial: se ha reembolsado una parte al cliente.": "Partially resolved: the client has received a partial refund.",
  "Resuelta por el equipo de Diime.": "Resolved by the Diime team.",
  "Disputa retirada": "Dispute withdrawn",
  "El trabajo continúa con normalidad.": "The job continues as normal.",
  "La abriste tú": "Opened by you",
  "Abierta por la otra parte": "Opened by the other party",
  "Abierta": "Open",
  "En revisión": "Under review",
  "Resuelta": "Resolved",
  "Cerrada": "Closed",
  "Incidencia retirada": "Issue withdrawn",
  "Se ha retirado del equipo de Diime.": "It has been withdrawn from the Diime team's review.",
  "Cuéntanos qué ha ocurrido, cuándo y con qué usuarios o trabajo está relacionado...": "Tell us what happened, when, and which users or job it relates to...",
  "Completa asunto y descripción": "Complete the subject and description",
  "Incidencia reportada": "Issue reported",
  "Nuestro equipo la revisará lo antes posible.": "Our team will review it as soon as possible.",
  "Resumen breve del problema": "Brief summary of the problem",
  "Enviar reporte": "Submit report",
  "Lun": "Mon",
  "Mar": "Tue",
  "Mié": "Wed",
  "Jue": "Thu",
  "Vie": "Fri",
  "Sáb": "Sat",
  "Dom": "Sun",
  "Enero": "January",
  "Febrero": "February",
  "Marzo": "March",
  "Abril": "April",
  "Mayo": "May",
  "Junio": "June",
  "Julio": "July",
  "Agosto": "August",
  "Septiembre": "September",
  "Octubre": "October",
  "Noviembre": "November",
  "Diciembre": "December",
  "Verde": "Green",
  "Azul": "Blue",
  "Ámbar": "Amber",
  "Rosa": "Pink",
  "Violeta": "Purple",
  "Cian": "Cyan",
  "Año Nuevo": "New Year's Day",
  "Reyes Magos": "Epiphany",
  "Día del Trabajo": "Labour Day",
  "Asunción de la Virgen": "Assumption of Mary",
  "Fiesta Nacional de España": "Spain's National Day",
  "Todos los Santos": "All Saints' Day",
  "Día de la Constitución": "Constitution Day",
  "Inmaculada Concepción": "Immaculate Conception",
  "Navidad": "Christmas Day",
  "Jueves Santo": "Maundy Thursday",
  "Viernes Santo": "Good Friday",
  "Trabajo": "Job",
  "Inicio del trabajo": "Job start",
  "Entrega prevista": "Expected delivery",
  "Inicio del servicio": "Service start",
  "Recepción prevista": "Expected service delivery",
  "Falta el título": "Title required",
  "Pon un nombre al evento": "Give the event a name",
  "Evento actualizado": "Event updated",
  "Evento creado": "Event created",
  "No se pudo guardar": "Could not save",
  "Evento eliminado": "Event deleted",
  "No se pudo eliminar": "Could not delete",
  "Mes anterior": "Previous month",
  "Mes siguiente": "Next month",
  "Editar evento": "Edit event",
  "Nuevo evento": "New event",
  "Reunión con cliente": "Meeting with client",
  "Opcional": "Optional",
  "Detalles del evento...": "Event details...",
  "Guardando...": "Saving...",
  "Guardar": "Save",
  "Crear": "Create",
  "No se pudo abrir Stripe": "Could not open Stripe",
  "Stripe necesita que completes o actualices algunos datos antes de que podamos transferirte pagos.": "Stripe needs you to complete or update some details before we can transfer payments to you.",
  "Activa tu cuenta de cobros antes de aceptar trabajos de pago.": "Activate your payout account before accepting paid jobs.",
  "Próximo ingreso al banco": "Next bank payout",
  "Próxima disponibilidad": "Next availability",
  "Próximo ingreso": "Next payout",
  "El ingreso ya está en camino.": "The payout is already on its way.",
  "Stripe ya ha programado el ingreso.": "Stripe has already scheduled the payout.",
  "Stripe no ha facilitado el saldo en este momento.": "Stripe has not provided your balance at this time.",
  "Completar datos en Stripe": "Complete your details in Stripe",
  "Activar cobros con Stripe": "Activate payouts with Stripe",
  "Inténtalo de nuevo en unos minutos.": "Please try again in a few minutes.",
  "Recarga la página o contacta con soporte: no se te cobrará dos veces.": "Reload the page or contact support: you will not be charged twice.",
  "Mediacion gratuita en disputas": "Free dispute mediation",
  "MM/AA": "MM/YY",
  "Mie": "Wed",
  "Sab": "Sat",
  "Sin titulo": "Untitled",
  "Guardado": "Saved",
  "La estimacion se ha actualizado correctamente": "The estimate has been updated successfully",
  "Trabajo que realizo": "Job I carry out",
  "Servicio que me realizan": "Service provided to me",
  "Profesional": "Professional",
  "Anade notas sobre este trabajo...": "Add notes about this job...",
  "Hace {count} min": "{count} min ago",
  "Hace {count}h": "{count}h ago",
  "Hace {count} días": "{count} days ago",
  "{count} archivo adjunto": "{count} attached file",
  "{count} archivos adjuntos": "{count} attached files",
  "{count} días restantes": "{count} days remaining",
  "Perderás las {count} ofertas que has recibido, y avisaremos a los profesionales que las enviaron.": "You will lose the {count} offers you received, and we will notify the professionals who sent them.",
  "Archivo {count}": "File {count}",
  "Se borrará tu puja de «{title}». Esta acción no se puede deshacer.": "Your bid for “{title}” will be deleted. This action cannot be undone.",
  "Se retirará tu oferta de «{title}». Esta acción no se puede deshacer.": "Your offer for “{title}” will be withdrawn. This action cannot be undone.",
  " el {date}": " on {date}",
  "en estado «{status}»": "with status “{status}”",
  "Puedes adjuntar un máximo de {count} archivos.": "You can attach up to {count} files.",
  "Quitar {name}": "Remove {name}",
  "Festivo: {name}": "Public holiday: {name}",
  "{amount} llegará {date}": "{amount} will arrive on {date}",
  "El saldo pendiente empezará a estar disponible para enviarlo al banco {date}; después se enviará {schedule}.": "The pending balance will start becoming available to send to your bank on {date}; it will then be sent {schedule}.",
  "Se enviará {schedule}; Stripe aún no ha creado el próximo ingreso.": "It will be sent {schedule}; Stripe has not yet created the next payout.",
  "Tu pago se ha realizado, pero no se pudo registrar la confirmación ({error}). ": "Your payment has been made, but its confirmation could not be recorded ({error}). ",
  "Semana del {date}": "Week of {date}",
  "dias": "days",
  "horas": "hours",
  "semanas": "weeks",
  "si": "included",
  "no": "not included",
  "parcial": "partially included",
  "alta": "High",
  "media": "Medium",
  "baja": "Low",
  "critica": "Critical",
  "pendiente": "Pending",
  "completado": "Completed",
  "cancelado": "Cancelled",
  "en_progreso": "In progress",
  "pendiente_pago": "Awaiting payment",
  "entregado": "Delivered",
  "en_disputa": "Under dispute",
  "fondos_retenidos": "Funds held",
  "liberado": "Released",
  "reembolsado": "Refunded",
  "{count} oferta recibida": "{count} offer received",
  "{count} ofertas recibidas": "{count} offers received",
  "incluidos": "included",
  "ofertas": "offers",
  "completados": "completed",
  "cliente": "client",
  "proveedor": "provider",
  "Y {count} demanda más.": "And {count} more request.",
  "Y {count} demandas más.": "And {count} more requests.",
  "Tienes {count} disputa en revisión. Mientras dure, el pago sigue confirmado y la transferencia bloqueada. Puedes aportar pruebas en el chat del trabajo.": "You have {count} dispute under review. While it is ongoing, payment remains confirmed and the transfer remains blocked. You can provide evidence in the job chat.",
  "Tienes {count} disputas en revisión. Mientras duren, el pago sigue confirmado y la transferencia bloqueada. Puedes aportar pruebas en el chat del trabajo.": "You have {count} disputes under review. While they are ongoing, payment remains confirmed and the transfer remains blocked. You can provide evidence in the job chat."
}
