-- Obsoleto.
--
-- Este script contenía identidades y contraseñas de demostración compartidas.
-- No debe usarse ni ejecutarse en ningún entorno.
--
-- Para preparar cuentas exclusivas de App Review y Google Play usa:
--
--   pnpm ops:create-review-accounts
--
-- El procedimiento y las variables requeridas están en REVIEW_ACCOUNTS.md.
